ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJpdGVtQWN0aW9uIjoiVmlldyBJdGVtIiwiY2F0YWxvZyI6eyJJdGVtQ2xhc3MiOnsiX2lkIjoiaGlnaGxpZ2h0cyJ9fSwidXNlciI6eyJhdHRyaWJ1dGVzIjp7ImdhQ2xpZW50SUQiOiI5MjgxOTk5NTcuMTc0NTQ0MTMwNyJ9LCJhbm9uSWQiOiIyM2MwYzQyOWMzMTUzN2ZiIn0sInNvdXJjZSI6eyJ1cmwiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56Lml0L3Bhc3NlbmdlcmNhcnMvbW9kZWxzL2NhYnJpb2xldC1yb2Fkc3Rlci9jbGUvb3ZlcnZpZXcuaHRtbCIsInVybFJlZmVycmVyIjoiIiwiY2hhbm5lbCI6IldlYiIsImJlYWNvblZlcnNpb24iOjE2LCJjb25maWdWZXJzaW9uIjoiNjMiLCJjb250ZW50Wm9uZXMiOltdfSwiY29uc2VudHMiOltdLCJhY2NvdW50Ijp7fSwicGVyZm9ybWFuY2UiOnsiZG9tTG9hZFRpbWUiOjE4NTMsInNka1BhcnNlVGltZSI6MX0sIl90b29sc0V2ZW50TGlua0lkIjoiMjU4NTIwMTU0NDU1ODkyMTYiLCJkZWJ1ZyI6eyJleHBsYW5hdGlvbnMiOnRydWV9fQ%3D%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x5638d7469cea <unknown>
#1 0x5638d6f1a5f0 <unknown>
#2 0x5638d6f00e86 <unknown>
#3 0x5638d6eff79a <unknown>
#4 0x5638d6effeff <unknown>
#5 0x5638d6effe54 <unknown>
#6 0x5638d6f1e7ff <unknown>
#7 0x5638d6fc39aa <unknown>
#8 0x5638d6f91662 <unknown>
#9 0x5638d6fb7660 <unknown>
#10 0x5638d6f91433 <unknown>
#11 0x5638d6f5dea3 <unknown>
#12 0x5638d6f5eb01 <unknown>
#13 0x5638d742eb3b <unknown>
#14 0x5638d7432a21 <unknown>
#15 0x5638d7415c32 <unknown>
#16 0x5638d7433594 <unknown>
#17 0x5638d73f9eef <unknown>
#18 0x5638d7457d98 <unknown>
#19 0x5638d7457f76 <unknown>
#20 0x5638d7468b36 <unknown>
#21 0x7f5e6e29caa4 <unknown>
#22 0x7f5e6e329c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJhY3Rpb24iOiJQcm9kdWN0IEluZm9ybWF0aW9uIFBhZ2UgLSBvdmVydmlldyAyMzY0IiwidXNlciI6eyJhdHRyaWJ1dGVzIjp7ImdhQ2xpZW50SUQiOiI5MjgxOTk5NTcuMTc0NTQ0MTMwNyJ9LCJhbm9uSWQiOiIyM2MwYzQyOWMzMTUzN2ZiIn0sInNvdXJjZSI6eyJ1cmwiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56Lml0L3Bhc3NlbmdlcmNhcnMvbW9kZWxzL2NhYnJpb2xldC1yb2Fkc3Rlci9jbGUvb3ZlcnZpZXcuaHRtbCIsInVybFJlZmVycmVyIjoiIiwiY2hhbm5lbCI6IldlYiIsImJlYWNvblZlcnNpb24iOjE2LCJjb25maWdWZXJzaW9uIjoiNjMiLCJjb250ZW50Wm9uZXMiOltdfSwiY29uc2VudHMiOltdLCJhY2NvdW50Ijp7fSwiX3Rvb2xzRXZlbnRMaW5rSWQiOiI5ODg2NTE5NTkyODQ2NDc0IiwiZGVidWciOnsiZXhwbGFuYXRpb25zIjp0cnVlfX0%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x5638d7469cea <unknown>
#1 0x5638d6f1a5f0 <unknown>
#2 0x5638d6f00e86 <unknown>
#3 0x5638d6eff79a <unknown>
#4 0x5638d6effeff <unknown>
#5 0x5638d6effe54 <unknown>
#6 0x5638d6f1e7ff <unknown>
#7 0x5638d6fc39aa <unknown>
#8 0x5638d6f91662 <unknown>
#9 0x5638d6fb7660 <unknown>
#10 0x5638d6f91433 <unknown>
#11 0x5638d6f5dea3 <unknown>
#12 0x5638d6f5eb01 <unknown>
#13 0x5638d742eb3b <unknown>
#14 0x5638d7432a21 <unknown>
#15 0x5638d7415c32 <unknown>
#16 0x5638d7433594 <unknown>
#17 0x5638d73f9eef <unknown>
#18 0x5638d7457d98 <unknown>
#19 0x5638d7457f76 <unknown>
#20 0x5638d7468b36 <unknown>
#21 0x7f5e6e29caa4 <unknown>
#22 0x7f5e6e329c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJhY3Rpb24iOiJQcm9kdWN0IEluZm9ybWF0aW9uIFBhZ2UgLSBoaWdobGlnaHRzIDIzNjQiLCJpdGVtQWN0aW9uIjoiVmlldyBJdGVtIiwic291cmNlIjp7InBhZ2VUeXBlIjoicHJvZHVjdF9pbmZvcm1hdGlvbiIsImxvY2FsZSI6Iml0X0lUIiwiY29udGVudFpvbmVzIjpbImdsb2JhbF9QSV9OTCIsInBpX2Jhbm5lcl9OTCIsImVxcy1zcGVjaWFsX05MIl0sInVybCI6Imh0dHBzOi8vd3d3Lm1lcmNlZGVzLWJlbnouaXQvcGFzc2VuZ2VyY2Fycy9tb2RlbHMvY2FicmlvbGV0LXJvYWRzdGVyL2NsZS9vdmVydmlldy5odG1sIiwidXJsUmVmZXJyZXIiOiIiLCJjaGFubmVsIjoiV2ViIiwiYmVhY29uVmVyc2lvbiI6MTYsImNvbmZpZ1ZlcnNpb24iOiI2MyJ9LCJmbGFncyI6eyJwYWdlVmlldyI6dHJ1ZX0sInVzZXIiOnsiYXR0cmlidXRlcyI6eyJnYUNsaWVudElEIjoiOTI4MTk5OTU3LjE3NDU0NDEzMDcifSwiYW5vbklkIjoiMjNjMGM0MjljMzE1MzdmYiJ9LCJwZXJmb3JtYW5jZSI6eyJkb21Mb2FkVGltZSI6MTg1Mywic2RrUGFyc2VUaW1lIjoxfSwiZGVidWciOnsiZXhwbGFuYXRpb25zIjp0cnVlfSwiY2F0YWxvZyI6eyJQcm9kdWN0Ijp7Il9pZCI6IjIzNjQiLCJkaW1lbnNpb25zIjp7IkJhdW11c3RlclNob3J0IjpbIjIzNjQiXX19fSwiY29uc2VudHMiOltdLCJhY2NvdW50Ijp7fSwiX3Rvb2xzRXZlbnRMaW5rSWQiOiI5MjczNzk0MDgwOTIzNTA2In0%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x5638d7469cea <unknown>
#1 0x5638d6f1a5f0 <unknown>
#2 0x5638d6f00e86 <unknown>
#3 0x5638d6eff79a <unknown>
#4 0x5638d6effeff <unknown>
#5 0x5638d6effe54 <unknown>
#6 0x5638d6f1e7ff <unknown>
#7 0x5638d6fc39aa <unknown>
#8 0x5638d6f91662 <unknown>
#9 0x5638d6fb7660 <unknown>
#10 0x5638d6f91433 <unknown>
#11 0x5638d6f5dea3 <unknown>
#12 0x5638d6f5eb01 <unknown>
#13 0x5638d742eb3b <unknown>
#14 0x5638d7432a21 <unknown>
#15 0x5638d7415c32 <unknown>
#16 0x5638d7433594 <unknown>
#17 0x5638d73f9eef <unknown>
#18 0x5638d7457d98 <unknown>
#19 0x5638d7457f76 <unknown>
#20 0x5638d7468b36 <unknown>
#21 0x7f5e6e29caa4 <unknown>
#22 0x7f5e6e329c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJhY3Rpb24iOiJWaXNpdGVkIC0gb3ZlcnZpZXciLCJ1c2VyIjp7ImF0dHJpYnV0ZXMiOnsiZ2FDbGllbnRJRCI6IjkyODE5OTk1Ny4xNzQ1NDQxMzA3In0sImFub25JZCI6IjIzYzBjNDI5YzMxNTM3ZmIifSwic291cmNlIjp7InVybCI6Imh0dHBzOi8vd3d3Lm1lcmNlZGVzLWJlbnouaXQvcGFzc2VuZ2VyY2Fycy9tb2RlbHMvY2FicmlvbGV0LXJvYWRzdGVyL2NsZS9vdmVydmlldy5odG1sIiwidXJsUmVmZXJyZXIiOiIiLCJjaGFubmVsIjoiV2ViIiwiYmVhY29uVmVyc2lvbiI6MTYsImNvbmZpZ1ZlcnNpb24iOiI2MyIsImNvbnRlbnRab25lcyI6W119LCJjb25zZW50cyI6W10sImFjY291bnQiOnt9LCJwZXJmb3JtYW5jZSI6eyJkb21Mb2FkVGltZSI6MTg1Mywic2RrUGFyc2VUaW1lIjoxfSwiX3Rvb2xzRXZlbnRMaW5rSWQiOiIwMjgwNTY4MTgxODk1MDA1NjUiLCJkZWJ1ZyI6eyJleHBsYW5hdGlvbnMiOnRydWV9fQ%3D%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x5638d7469cea <unknown>
#1 0x5638d6f1a5f0 <unknown>
#2 0x5638d6f00e86 <unknown>
#3 0x5638d6eff79a <unknown>
#4 0x5638d6effeff <unknown>
#5 0x5638d6effe54 <unknown>
#6 0x5638d6f1e7ff <unknown>
#7 0x5638d6fc39aa <unknown>
#8 0x5638d6f91662 <unknown>
#9 0x5638d6fb7660 <unknown>
#10 0x5638d6f91433 <unknown>
#11 0x5638d6f5dea3 <unknown>
#12 0x5638d6f5eb01 <unknown>
#13 0x5638d742eb3b <unknown>
#14 0x5638d7432a21 <unknown>
#15 0x5638d7415c32 <unknown>
#16 0x5638d7433594 <unknown>
#17 0x5638d73f9eef <unknown>
#18 0x5638d7457d98 <unknown>
#19 0x5638d7457f76 <unknown>
#20 0x5638d7468b36 <unknown>
#21 0x7f5e6e29caa4 <unknown>
#22 0x7f5e6e329c3c <unknown>

ERROR    root:VerifyPersonalizationAndCapture.py:111 ❌ Image not found in the specified selector. Error: Message: 

ERROR    root:VerifyPersonalizationAndCapture.py:18 ❌ Error attaching screenshot to Allure: [Errno 2] No such file or directory: '/home/runner/work/QA-App-Allure/QA-App-Allure/Tests/BFV1_attempt_1.png'
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6252ee5c50>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/2f24ba7552098db71a5ec0897a5ff465
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6252ee65d0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/2f24ba7552098db71a5ec0897a5ff465
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6252ee6dd0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/2f24ba7552098db71a5ec0897a5ff465
ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJpdGVtQWN0aW9uIjoiVmlldyBJdGVtIiwiY2F0YWxvZyI6eyJJdGVtQ2xhc3MiOnsiX2lkIjoib3ZlcnZpZXcifX0sInVzZXIiOnsiYXR0cmlidXRlcyI6eyJnYUNsaWVudElEIjoiMzAxNDI5ODgyLjE3NDU0NDEzMzkifSwiYW5vbklkIjoiODFiMGEyYmFiODk3MGI0YiJ9LCJzb3VyY2UiOnsidXJsIjoiaHR0cHM6Ly93d3cubWVyY2VkZXMtYmVuei5pdC9wYXNzZW5nZXJjYXJzL21vZGVscy9jYWJyaW9sZXQtcm9hZHN0ZXIvY2xlL292ZXJ2aWV3Lmh0bWwiLCJ1cmxSZWZlcnJlciI6IiIsImNoYW5uZWwiOiJXZWIiLCJiZWFjb25WZXJzaW9uIjoxNiwiY29uZmlnVmVyc2lvbiI6IjYzIiwiY29udGVudFpvbmVzIjpbXX0sImNvbnNlbnRzIjpbXSwiYWNjb3VudCI6e30sIl90b29sc0V2ZW50TGlua0lkIjoiMjY5Mzg1MTA1MTcxNzM5NCIsImRlYnVnIjp7ImV4cGxhbmF0aW9ucyI6dHJ1ZX19: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x555611029cea <unknown>
#1 0x555610ada5f0 <unknown>
#2 0x555610ac0e86 <unknown>
#3 0x555610abf79a <unknown>
#4 0x555610abfeff <unknown>
#5 0x555610abfe54 <unknown>
#6 0x555610ade7ff <unknown>
#7 0x555610b839aa <unknown>
#8 0x555610b51662 <unknown>
#9 0x555610b77660 <unknown>
#10 0x555610b51433 <unknown>
#11 0x555610b1dea3 <unknown>
#12 0x555610b1eb01 <unknown>
#13 0x555610feeb3b <unknown>
#14 0x555610ff2a21 <unknown>
#15 0x555610fd5c32 <unknown>
#16 0x555610ff3594 <unknown>
#17 0x555610fb9eef <unknown>
#18 0x555611017d98 <unknown>
#19 0x555611017f76 <unknown>
#20 0x555611028b36 <unknown>
#21 0x7f103689caa4 <unknown>
#22 0x7f1036929c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJhY3Rpb24iOiJQcm9kdWN0IEluZm9ybWF0aW9uIFBhZ2UgLSBvdmVydmlldyAyMzY0IiwiaXRlbUFjdGlvbiI6IlZpZXcgSXRlbSIsInNvdXJjZSI6eyJwYWdlVHlwZSI6InByb2R1Y3RfaW5mb3JtYXRpb24iLCJsb2NhbGUiOiJpdF9JVCIsImNvbnRlbnRab25lcyI6WyJnbG9iYWxfUElfTkwiLCJwaV9iYW5uZXJfTkwiLCJlcXMtc3BlY2lhbF9OTCJdLCJ1cmwiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56Lml0L3Bhc3NlbmdlcmNhcnMvbW9kZWxzL2NhYnJpb2xldC1yb2Fkc3Rlci9jbGUvb3ZlcnZpZXcuaHRtbCIsInVybFJlZmVycmVyIjoiIiwiY2hhbm5lbCI6IldlYiIsImJlYWNvblZlcnNpb24iOjE2LCJjb25maWdWZXJzaW9uIjoiNjMifSwiZmxhZ3MiOnsicGFnZVZpZXciOnRydWV9LCJ1c2VyIjp7ImF0dHJpYnV0ZXMiOnsiZ2FDbGllbnRJRCI6IjMwMTQyOTg4Mi4xNzQ1NDQxMzM5In0sImFub25JZCI6IjgxYjBhMmJhYjg5NzBiNGIifSwicGVyZm9ybWFuY2UiOnsic2RrUGFyc2VUaW1lIjoxfSwiZGVidWciOnsiZXhwbGFuYXRpb25zIjp0cnVlfSwiY2F0YWxvZyI6eyJQcm9kdWN0Ijp7Il9pZCI6IjIzNjQiLCJkaW1lbnNpb25zIjp7IkJhdW11c3RlclNob3J0IjpbIjIzNjQiXX19fSwiY29uc2VudHMiOltdLCJhY2NvdW50Ijp7fSwiX3Rvb2xzRXZlbnRMaW5rSWQiOiI0NzE5MzgyMzI4MTQ2MzI3NiJ9: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x555611029cea <unknown>
#1 0x555610ada5f0 <unknown>
#2 0x555610ac0e86 <unknown>
#3 0x555610abf79a <unknown>
#4 0x555610abfeff <unknown>
#5 0x555610abfe54 <unknown>
#6 0x555610ade7ff <unknown>
#7 0x555610b839aa <unknown>
#8 0x555610b51662 <unknown>
#9 0x555610b77660 <unknown>
#10 0x555610b51433 <unknown>
#11 0x555610b1dea3 <unknown>
#12 0x555610b1eb01 <unknown>
#13 0x555610feeb3b <unknown>
#14 0x555610ff2a21 <unknown>
#15 0x555610fd5c32 <unknown>
#16 0x555610ff3594 <unknown>
#17 0x555610fb9eef <unknown>
#18 0x555611017d98 <unknown>
#19 0x555611017f76 <unknown>
#20 0x555611028b36 <unknown>
#21 0x7f103689caa4 <unknown>
#22 0x7f1036929c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJhY3Rpb24iOiJWaXNpdGVkIC0gb3ZlcnZpZXciLCJ1c2VyIjp7ImF0dHJpYnV0ZXMiOnsiZ2FDbGllbnRJRCI6IjMwMTQyOTg4Mi4xNzQ1NDQxMzM5In0sImFub25JZCI6IjgxYjBhMmJhYjg5NzBiNGIifSwic291cmNlIjp7InVybCI6Imh0dHBzOi8vd3d3Lm1lcmNlZGVzLWJlbnouaXQvcGFzc2VuZ2VyY2Fycy9tb2RlbHMvY2FicmlvbGV0LXJvYWRzdGVyL2NsZS9vdmVydmlldy5odG1sIiwidXJsUmVmZXJyZXIiOiIiLCJjaGFubmVsIjoiV2ViIiwiYmVhY29uVmVyc2lvbiI6MTYsImNvbmZpZ1ZlcnNpb24iOiI2MyIsImNvbnRlbnRab25lcyI6W119LCJjb25zZW50cyI6W10sImFjY291bnQiOnt9LCJwZXJmb3JtYW5jZSI6eyJzZGtQYXJzZVRpbWUiOjF9LCJfdG9vbHNFdmVudExpbmtJZCI6IjY4OTg2NjI1MDcyNTY5MDQiLCJkZWJ1ZyI6eyJleHBsYW5hdGlvbnMiOnRydWV9fQ%3D%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x555611029cea <unknown>
#1 0x555610ada5f0 <unknown>
#2 0x555610ac0e86 <unknown>
#3 0x555610abf79a <unknown>
#4 0x555610abfeff <unknown>
#5 0x555610abfe54 <unknown>
#6 0x555610ade7ff <unknown>
#7 0x555610b839aa <unknown>
#8 0x555610b51662 <unknown>
#9 0x555610b77660 <unknown>
#10 0x555610b51433 <unknown>
#11 0x555610b1dea3 <unknown>
#12 0x555610b1eb01 <unknown>
#13 0x555610feeb3b <unknown>
#14 0x555610ff2a21 <unknown>
#15 0x555610fd5c32 <unknown>
#16 0x555610ff3594 <unknown>
#17 0x555610fb9eef <unknown>
#18 0x555611017d98 <unknown>
#19 0x555611017f76 <unknown>
#20 0x555611028b36 <unknown>
#21 0x7f103689caa4 <unknown>
#22 0x7f1036929c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJhY3Rpb24iOiJzZXRfdXNlcl9hdHRyaWJ1dGUiLCJhY2NvdW50Ijp7ImF0dHJpYnV0ZXMiOnsibGFzdFBpUGFnZSI6eyJ2ZWhpY2xlUEkiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56Lml0L3Bhc3NlbmdlcmNhcnMvbW9kZWxzL2NhYnJpb2xldC1yb2Fkc3Rlci9jbGUvb3ZlcnZpZXcuaHRtbCIsInZlaGljbGVDb2RlIjoiYTIzNiIsInZlaGljbGVCTSI6IjIzNjQiLCJ2ZWhpY2xlUElIaXN0b3J5IjoiMjM2NCIsInRpbWVzdGFtcCI6MTc0NTQ0MTM0MzE2MiwiZXhwaXJhdGlvbiI6MTIwfX19LCJ1c2VyIjp7ImF0dHJpYnV0ZXMiOnsiZ2FDbGllbnRJRCI6IjMwMTQyOTg4Mi4xNzQ1NDQxMzM5In0sImFub25JZCI6IjgxYjBhMmJhYjg5NzBiNGIifSwic291cmNlIjp7InVybCI6Imh0dHBzOi8vd3d3Lm1lcmNlZGVzLWJlbnouaXQvcGFzc2VuZ2VyY2Fycy9tb2RlbHMvY2FicmlvbGV0LXJvYWRzdGVyL2NsZS9vdmVydmlldy5odG1sIiwidXJsUmVmZXJyZXIiOiIiLCJjaGFubmVsIjoiV2ViIiwiYmVhY29uVmVyc2lvbiI6MTYsImNvbmZpZ1ZlcnNpb24iOiI2MyIsImNvbnRlbnRab25lcyI6W119LCJjb25zZW50cyI6W10sIl90b29sc0V2ZW50TGlua0lkIjoiMTg1OTY1NTI1NjcwNDUyNzciLCJkZWJ1ZyI6eyJleHBsYW5hdGlvbnMiOnRydWV9fQ%3D%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x555611029cea <unknown>
#1 0x555610ada5f0 <unknown>
#2 0x555610ac0e86 <unknown>
#3 0x555610abf79a <unknown>
#4 0x555610abfeff <unknown>
#5 0x555610abfe54 <unknown>
#6 0x555610ade7ff <unknown>
#7 0x555610b839aa <unknown>
#8 0x555610b51662 <unknown>
#9 0x555610b77660 <unknown>
#10 0x555610b51433 <unknown>
#11 0x555610b1dea3 <unknown>
#12 0x555610b1eb01 <unknown>
#13 0x555610feeb3b <unknown>
#14 0x555610ff2a21 <unknown>
#15 0x555610fd5c32 <unknown>
#16 0x555610ff3594 <unknown>
#17 0x555610fb9eef <unknown>
#18 0x555611017d98 <unknown>
#19 0x555611017f76 <unknown>
#20 0x555611028b36 <unknown>
#21 0x7f103689caa4 <unknown>
#22 0x7f1036929c3c <unknown>

ERROR    root:VerifyPersonalizationAndCapture.py:18 ❌ Error attaching screenshot to Allure: [Errno 2] No such file or directory: '/home/runner/work/QA-App-Allure/QA-App-Allure/Tests/BFV1_attempt_2.png'
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f62519e5650>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/2f24ba7552098db71a5ec0897a5ff465
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f62519e5f50>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/2f24ba7552098db71a5ec0897a5ff465
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f62519e6750>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/2f24ba7552098db71a5ec0897a5ff465