ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJhY3Rpb24iOiJWaXNpdGVkIC0gcGFzc2VuZ2VyY2FycyIsInVzZXIiOnsiYXR0cmlidXRlcyI6eyJnYUNsaWVudElEIjoiMTU0NDk3OTQ4My4xNzQ1NDMwMjcyIn0sImFub25JZCI6IjIzZGNmOWExZjFlNTMzZjcifSwic291cmNlIjp7InVybCI6Imh0dHBzOi8vd3d3Lm1lcmNlZGVzLWJlbnouaXQvIiwidXJsUmVmZXJyZXIiOiIiLCJjaGFubmVsIjoiV2ViIiwiYmVhY29uVmVyc2lvbiI6MTYsImNvbmZpZ1ZlcnNpb24iOiI2MyIsImNvbnRlbnRab25lcyI6W119LCJjb25zZW50cyI6W10sImFjY291bnQiOnt9LCJwZXJmb3JtYW5jZSI6eyJkb21Mb2FkVGltZSI6MjkwOSwicGFnZUxvYWRUaW1lIjozNDc5LCJzZGtQYXJzZVRpbWUiOjIsInNka0xvYWRUaW1lIjoxMTAsInNka0Ruc1RpbWUiOjE0fSwiX3Rvb2xzRXZlbnRMaW5rSWQiOiIxMzMzODMyMjA3ODAzMTc4MyIsImRlYnVnIjp7ImV4cGxhbmF0aW9ucyI6dHJ1ZX19: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x55a9ef2e8cea <unknown>
#1 0x55a9eed995f0 <unknown>
#2 0x55a9eed7fe86 <unknown>
#3 0x55a9eed7e79a <unknown>
#4 0x55a9eed7eeff <unknown>
#5 0x55a9eed7ee54 <unknown>
#6 0x55a9eed9d7ff <unknown>
#7 0x55a9eee429aa <unknown>
#8 0x55a9eee10662 <unknown>
#9 0x55a9eee36660 <unknown>
#10 0x55a9eee10433 <unknown>
#11 0x55a9eeddcea3 <unknown>
#12 0x55a9eedddb01 <unknown>
#13 0x55a9ef2adb3b <unknown>
#14 0x55a9ef2b1a21 <unknown>
#15 0x55a9ef294c32 <unknown>
#16 0x55a9ef2b2594 <unknown>
#17 0x55a9ef278eef <unknown>
#18 0x55a9ef2d6d98 <unknown>
#19 0x55a9ef2d6f76 <unknown>
#20 0x55a9ef2e7b36 <unknown>
#21 0x7f69ef09caa4 <unknown>
#22 0x7f69ef129c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJhY3Rpb24iOiJIb21lIFBhZ2UiLCJpdGVtQWN0aW9uIjpudWxsLCJzb3VyY2UiOnsicGFnZVR5cGUiOiJob21lIiwibG9jYWxlIjoiaXRfSVQiLCJjb250ZW50Wm9uZXMiOltdLCJ1cmwiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56Lml0LyIsInVybFJlZmVycmVyIjoiIiwiY2hhbm5lbCI6IldlYiIsImJlYWNvblZlcnNpb24iOjE2LCJjb25maWdWZXJzaW9uIjoiNjMifSwiZmxhZ3MiOnsicGFnZVZpZXciOnRydWV9LCJ1c2VyIjp7ImF0dHJpYnV0ZXMiOnsiZ2FDbGllbnRJRCI6IjE1NDQ5Nzk0ODMuMTc0NTQzMDI3MiJ9LCJhbm9uSWQiOiIyM2RjZjlhMWYxZTUzM2Y3In0sInBlcmZvcm1hbmNlIjp7fSwiZGVidWciOnsiZXhwbGFuYXRpb25zIjp0cnVlfSwiY2F0YWxvZyI6e30sImNvbnNlbnRzIjpbXSwiYWNjb3VudCI6e30sIl90b29sc0V2ZW50TGlua0lkIjoiMTUzNjAyODM1NDk5NDYwNzQifQ%3D%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x55a9ef2e8cea <unknown>
#1 0x55a9eed995f0 <unknown>
#2 0x55a9eed7fe86 <unknown>
#3 0x55a9eed7e79a <unknown>
#4 0x55a9eed7eeff <unknown>
#5 0x55a9eed7ee54 <unknown>
#6 0x55a9eed9d7ff <unknown>
#7 0x55a9eee429aa <unknown>
#8 0x55a9eee10662 <unknown>
#9 0x55a9eee36660 <unknown>
#10 0x55a9eee10433 <unknown>
#11 0x55a9eeddcea3 <unknown>
#12 0x55a9eedddb01 <unknown>
#13 0x55a9ef2adb3b <unknown>
#14 0x55a9ef2b1a21 <unknown>
#15 0x55a9ef294c32 <unknown>
#16 0x55a9ef2b2594 <unknown>
#17 0x55a9ef278eef <unknown>
#18 0x55a9ef2d6d98 <unknown>
#19 0x55a9ef2d6f76 <unknown>
#20 0x55a9ef2e7b36 <unknown>
#21 0x7f69ef09caa4 <unknown>
#22 0x7f69ef129c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJpdGVtQWN0aW9uIjoiVmlldyBJdGVtIiwiY2F0YWxvZyI6eyJJdGVtQ2xhc3MiOnsiX2lkIjoib3ZlcnZpZXcifX0sInVzZXIiOnsiYXR0cmlidXRlcyI6eyJnYUNsaWVudElEIjoiMTU0NDk3OTQ4My4xNzQ1NDMwMjcyIn0sImFub25JZCI6IjIzZGNmOWExZjFlNTMzZjcifSwic291cmNlIjp7InVybCI6Imh0dHBzOi8vd3d3Lm1lcmNlZGVzLWJlbnouaXQvcGFzc2VuZ2VyY2Fycy9tb2RlbHMvY291cGUvY2xlL292ZXJ2aWV3Lmh0bWwiLCJ1cmxSZWZlcnJlciI6IiIsImNoYW5uZWwiOiJXZWIiLCJiZWFjb25WZXJzaW9uIjoxNiwiY29uZmlnVmVyc2lvbiI6IjYzIiwiY29udGVudFpvbmVzIjpbXX0sImNvbnNlbnRzIjpbXSwiYWNjb3VudCI6e30sIl90b29sc0V2ZW50TGlua0lkIjoiMjgyMTM4ODk2MTE5NDIiLCJkZWJ1ZyI6eyJleHBsYW5hdGlvbnMiOnRydWV9fQ%3D%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x55a9ef2e8cea <unknown>
#1 0x55a9eed995f0 <unknown>
#2 0x55a9eed7fe86 <unknown>
#3 0x55a9eed7e79a <unknown>
#4 0x55a9eed7eeff <unknown>
#5 0x55a9eed7ee54 <unknown>
#6 0x55a9eed9d7ff <unknown>
#7 0x55a9eee429aa <unknown>
#8 0x55a9eee10662 <unknown>
#9 0x55a9eee36660 <unknown>
#10 0x55a9eee10433 <unknown>
#11 0x55a9eeddcea3 <unknown>
#12 0x55a9eedddb01 <unknown>
#13 0x55a9ef2adb3b <unknown>
#14 0x55a9ef2b1a21 <unknown>
#15 0x55a9ef294c32 <unknown>
#16 0x55a9ef2b2594 <unknown>
#17 0x55a9ef278eef <unknown>
#18 0x55a9ef2d6d98 <unknown>
#19 0x55a9ef2d6f76 <unknown>
#20 0x55a9ef2e7b36 <unknown>
#21 0x7f69ef09caa4 <unknown>
#22 0x7f69ef129c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJhY3Rpb24iOiJQcm9kdWN0IEluZm9ybWF0aW9uIFBhZ2UgLSBvdmVydmlldyAyMzYzIiwiaXRlbUFjdGlvbiI6IlZpZXcgSXRlbSIsInNvdXJjZSI6eyJwYWdlVHlwZSI6InByb2R1Y3RfaW5mb3JtYXRpb24iLCJsb2NhbGUiOiJpdF9JVCIsImNvbnRlbnRab25lcyI6WyJnbG9iYWxfUElfTkwiLCJwaV9iYW5uZXJfTkwiLCJlcXMtc3BlY2lhbF9OTCJdLCJ1cmwiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56Lml0L3Bhc3NlbmdlcmNhcnMvbW9kZWxzL2NvdXBlL2NsZS9vdmVydmlldy5odG1sIiwidXJsUmVmZXJyZXIiOiIiLCJjaGFubmVsIjoiV2ViIiwiYmVhY29uVmVyc2lvbiI6MTYsImNvbmZpZ1ZlcnNpb24iOiI2MyJ9LCJmbGFncyI6eyJwYWdlVmlldyI6dHJ1ZX0sInVzZXIiOnsiYXR0cmlidXRlcyI6eyJnYUNsaWVudElEIjoiMTU0NDk3OTQ4My4xNzQ1NDMwMjcyIn0sImFub25JZCI6IjIzZGNmOWExZjFlNTMzZjcifSwicGVyZm9ybWFuY2UiOnsic2RrUGFyc2VUaW1lIjoxfSwiZGVidWciOnsiZXhwbGFuYXRpb25zIjp0cnVlfSwiY2F0YWxvZyI6eyJQcm9kdWN0Ijp7Il9pZCI6IjIzNjMiLCJkaW1lbnNpb25zIjp7IkJhdW11c3RlclNob3J0IjpbIjIzNjMiXX19fSwiY29uc2VudHMiOltdLCJhY2NvdW50Ijp7fSwiX3Rvb2xzRXZlbnRMaW5rSWQiOiI5NTA4MTI4OTY1MDE0MjcyIn0%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x55a9ef2e8cea <unknown>
#1 0x55a9eed995f0 <unknown>
#2 0x55a9eed7fe86 <unknown>
#3 0x55a9eed7e79a <unknown>
#4 0x55a9eed7eeff <unknown>
#5 0x55a9eed7ee54 <unknown>
#6 0x55a9eed9d7ff <unknown>
#7 0x55a9eee429aa <unknown>
#8 0x55a9eee10662 <unknown>
#9 0x55a9eee36660 <unknown>
#10 0x55a9eee10433 <unknown>
#11 0x55a9eeddcea3 <unknown>
#12 0x55a9eedddb01 <unknown>
#13 0x55a9ef2adb3b <unknown>
#14 0x55a9ef2b1a21 <unknown>
#15 0x55a9ef294c32 <unknown>
#16 0x55a9ef2b2594 <unknown>
#17 0x55a9ef278eef <unknown>
#18 0x55a9ef2d6d98 <unknown>
#19 0x55a9ef2d6f76 <unknown>
#20 0x55a9ef2e7b36 <unknown>
#21 0x7f69ef09caa4 <unknown>
#22 0x7f69ef129c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJhY3Rpb24iOiJWaXNpdGVkIC0gb3ZlcnZpZXciLCJ1c2VyIjp7ImF0dHJpYnV0ZXMiOnsiZ2FDbGllbnRJRCI6IjE1NDQ5Nzk0ODMuMTc0NTQzMDI3MiJ9LCJhbm9uSWQiOiIyM2RjZjlhMWYxZTUzM2Y3In0sInNvdXJjZSI6eyJ1cmwiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56Lml0L3Bhc3NlbmdlcmNhcnMvbW9kZWxzL2NvdXBlL2NsZS9vdmVydmlldy5odG1sIiwidXJsUmVmZXJyZXIiOiIiLCJjaGFubmVsIjoiV2ViIiwiYmVhY29uVmVyc2lvbiI6MTYsImNvbmZpZ1ZlcnNpb24iOiI2MyIsImNvbnRlbnRab25lcyI6W119LCJjb25zZW50cyI6W10sImFjY291bnQiOnt9LCJwZXJmb3JtYW5jZSI6eyJzZGtQYXJzZVRpbWUiOjF9LCJfdG9vbHNFdmVudExpbmtJZCI6IjM2MTY3NTAyNjQxMDgxODgzIiwiZGVidWciOnsiZXhwbGFuYXRpb25zIjp0cnVlfX0%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x55a9ef2e8cea <unknown>
#1 0x55a9eed995f0 <unknown>
#2 0x55a9eed7fe86 <unknown>
#3 0x55a9eed7e79a <unknown>
#4 0x55a9eed7eeff <unknown>
#5 0x55a9eed7ee54 <unknown>
#6 0x55a9eed9d7ff <unknown>
#7 0x55a9eee429aa <unknown>
#8 0x55a9eee10662 <unknown>
#9 0x55a9eee36660 <unknown>
#10 0x55a9eee10433 <unknown>
#11 0x55a9eeddcea3 <unknown>
#12 0x55a9eedddb01 <unknown>
#13 0x55a9ef2adb3b <unknown>
#14 0x55a9ef2b1a21 <unknown>
#15 0x55a9ef294c32 <unknown>
#16 0x55a9ef2b2594 <unknown>
#17 0x55a9ef278eef <unknown>
#18 0x55a9ef2d6d98 <unknown>
#19 0x55a9ef2d6f76 <unknown>
#20 0x55a9ef2e7b36 <unknown>
#21 0x7f69ef09caa4 <unknown>
#22 0x7f69ef129c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJhY3Rpb24iOiJzZXRfdXNlcl9hdHRyaWJ1dGUiLCJhY2NvdW50Ijp7ImF0dHJpYnV0ZXMiOnsibGFzdFBpUGFnZSI6eyJ2ZWhpY2xlUEkiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56Lml0L3Bhc3NlbmdlcmNhcnMvbW9kZWxzL2NvdXBlL2NsZS9vdmVydmlldy5odG1sIiwidmVoaWNsZUNvZGUiOiJjMjM2IiwidmVoaWNsZUJNIjoiMjM2MyIsInZlaGljbGVQSUhpc3RvcnkiOiIyMzYzIiwidGltZXN0YW1wIjoxNzQ1NDMwMjc4ODg2LCJleHBpcmF0aW9uIjoxMjB9fX0sInVzZXIiOnsiYXR0cmlidXRlcyI6eyJnYUNsaWVudElEIjoiMTU0NDk3OTQ4My4xNzQ1NDMwMjcyIn0sImFub25JZCI6IjIzZGNmOWExZjFlNTMzZjcifSwic291cmNlIjp7InVybCI6Imh0dHBzOi8vd3d3Lm1lcmNlZGVzLWJlbnouaXQvcGFzc2VuZ2VyY2Fycy9tb2RlbHMvY291cGUvY2xlL292ZXJ2aWV3Lmh0bWwiLCJ1cmxSZWZlcnJlciI6IiIsImNoYW5uZWwiOiJXZWIiLCJiZWFjb25WZXJzaW9uIjoxNiwiY29uZmlnVmVyc2lvbiI6IjYzIiwiY29udGVudFpvbmVzIjpbXX0sImNvbnNlbnRzIjpbXSwiX3Rvb2xzRXZlbnRMaW5rSWQiOiIzODI3MTQzNTI4NDg0NjQ4IiwiZGVidWciOnsiZXhwbGFuYXRpb25zIjp0cnVlfX0%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x55a9ef2e8cea <unknown>
#1 0x55a9eed995f0 <unknown>
#2 0x55a9eed7fe86 <unknown>
#3 0x55a9eed7e79a <unknown>
#4 0x55a9eed7eeff <unknown>
#5 0x55a9eed7ee54 <unknown>
#6 0x55a9eed9d7ff <unknown>
#7 0x55a9eee429aa <unknown>
#8 0x55a9eee10662 <unknown>
#9 0x55a9eee36660 <unknown>
#10 0x55a9eee10433 <unknown>
#11 0x55a9eeddcea3 <unknown>
#12 0x55a9eedddb01 <unknown>
#13 0x55a9ef2adb3b <unknown>
#14 0x55a9ef2b1a21 <unknown>
#15 0x55a9ef294c32 <unknown>
#16 0x55a9ef2b2594 <unknown>
#17 0x55a9ef278eef <unknown>
#18 0x55a9ef2d6d98 <unknown>
#19 0x55a9ef2d6f76 <unknown>
#20 0x55a9ef2e7b36 <unknown>
#21 0x7f69ef09caa4 <unknown>
#22 0x7f69ef129c3c <unknown>

ERROR    root:VerifyPersonalizationAndCapture.py:111 ❌ Image not found in the specified selector. Error: Message: 

ERROR    root:VerifyPersonalizationAndCapture.py:18 ❌ Error attaching screenshot to Allure: [Errno 2] No such file or directory: '/home/runner/work/QA-App-Allure/QA-App-Allure/Tests/BFV1_attempt_1.png'
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f666e0dc650>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/d9cda72ff542bc6c11bf9f5d2e590058
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f666e0ddf50>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/d9cda72ff542bc6c11bf9f5d2e590058
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f666e0debd0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/d9cda72ff542bc6c11bf9f5d2e590058
ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJhY3Rpb24iOiJWaXNpdGVkIC0gb3ZlcnZpZXciLCJzb3VyY2UiOnsidXJsIjoiaHR0cHM6Ly93d3cubWVyY2VkZXMtYmVuei5pdC9wYXNzZW5nZXJjYXJzL21vZGVscy9jb3VwZS9jbGUvb3ZlcnZpZXcuaHRtbCIsInVybFJlZmVycmVyIjoiIiwiY2hhbm5lbCI6IldlYiIsImJlYWNvblZlcnNpb24iOjE2LCJjb25maWdWZXJzaW9uIjoiNjMiLCJjb250ZW50Wm9uZXMiOltdfSwidXNlciI6eyJhbm9uSWQiOiI3ZmI0ZDgxMGM2NTdmMjE4In0sImNvbnNlbnRzIjpbXSwiYWNjb3VudCI6e30sInBlcmZvcm1hbmNlIjp7InNka1BhcnNlVGltZSI6Mywic2RrTG9hZFRpbWUiOjJ9LCJfdG9vbHNFdmVudExpbmtJZCI6IjE3NTU0NTAyMzczNTg1MTQ2IiwiZGVidWciOnsiZXhwbGFuYXRpb25zIjp0cnVlfX0%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x55851d731cea <unknown>
#1 0x55851d1e25f0 <unknown>
#2 0x55851d1c8e86 <unknown>
#3 0x55851d1c779a <unknown>
#4 0x55851d1c7eff <unknown>
#5 0x55851d1c7e54 <unknown>
#6 0x55851d1e67ff <unknown>
#7 0x55851d28b9aa <unknown>
#8 0x55851d259662 <unknown>
#9 0x55851d27f660 <unknown>
#10 0x55851d259433 <unknown>
#11 0x55851d225ea3 <unknown>
#12 0x55851d226b01 <unknown>
#13 0x55851d6f6b3b <unknown>
#14 0x55851d6faa21 <unknown>
#15 0x55851d6ddc32 <unknown>
#16 0x55851d6fb594 <unknown>
#17 0x55851d6c1eef <unknown>
#18 0x55851d71fd98 <unknown>
#19 0x55851d71ff76 <unknown>
#20 0x55851d730b36 <unknown>
#21 0x7fc48689caa4 <unknown>
#22 0x7fc486929c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJhY3Rpb24iOiJQcm9kdWN0IEluZm9ybWF0aW9uIFBhZ2UgLSBvdmVydmlldyAyMzYzIiwiaXRlbUFjdGlvbiI6IlZpZXcgSXRlbSIsInNvdXJjZSI6eyJwYWdlVHlwZSI6InByb2R1Y3RfaW5mb3JtYXRpb24iLCJsb2NhbGUiOiJpdF9JVCIsImNvbnRlbnRab25lcyI6WyJnbG9iYWxfUElfTkwiLCJwaV9iYW5uZXJfTkwiLCJlcXMtc3BlY2lhbF9OTCJdLCJ1cmwiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56Lml0L3Bhc3NlbmdlcmNhcnMvbW9kZWxzL2NvdXBlL2NsZS9vdmVydmlldy5odG1sIiwidXJsUmVmZXJyZXIiOiIiLCJjaGFubmVsIjoiV2ViIiwiYmVhY29uVmVyc2lvbiI6MTYsImNvbmZpZ1ZlcnNpb24iOiI2MyJ9LCJmbGFncyI6eyJwYWdlVmlldyI6dHJ1ZX0sInVzZXIiOnsiYW5vbklkIjoiN2ZiNGQ4MTBjNjU3ZjIxOCJ9LCJwZXJmb3JtYW5jZSI6eyJzZGtQYXJzZVRpbWUiOjMsInNka0xvYWRUaW1lIjoyfSwiZGVidWciOnsiZXhwbGFuYXRpb25zIjp0cnVlfSwiY2F0YWxvZyI6eyJQcm9kdWN0Ijp7Il9pZCI6IjIzNjMiLCJkaW1lbnNpb25zIjp7IkJhdW11c3RlclNob3J0IjpbIjIzNjMiXX19fSwiY29uc2VudHMiOltdLCJhY2NvdW50Ijp7fSwiX3Rvb2xzRXZlbnRMaW5rSWQiOiI0MTIxMzcyMTcyNzA0OTMxMyJ9: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x55851d731cea <unknown>
#1 0x55851d1e25f0 <unknown>
#2 0x55851d1c8e86 <unknown>
#3 0x55851d1c779a <unknown>
#4 0x55851d1c7eff <unknown>
#5 0x55851d1c7e54 <unknown>
#6 0x55851d1e67ff <unknown>
#7 0x55851d28b9aa <unknown>
#8 0x55851d259662 <unknown>
#9 0x55851d27f660 <unknown>
#10 0x55851d259433 <unknown>
#11 0x55851d225ea3 <unknown>
#12 0x55851d226b01 <unknown>
#13 0x55851d6f6b3b <unknown>
#14 0x55851d6faa21 <unknown>
#15 0x55851d6ddc32 <unknown>
#16 0x55851d6fb594 <unknown>
#17 0x55851d6c1eef <unknown>
#18 0x55851d71fd98 <unknown>
#19 0x55851d71ff76 <unknown>
#20 0x55851d730b36 <unknown>
#21 0x7fc48689caa4 <unknown>
#22 0x7fc486929c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJpdGVtQWN0aW9uIjoiVmlldyBJdGVtIiwiY2F0YWxvZyI6eyJJdGVtQ2xhc3MiOnsiX2lkIjoib3ZlcnZpZXcifX0sInNvdXJjZSI6eyJ1cmwiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56Lml0L3Bhc3NlbmdlcmNhcnMvbW9kZWxzL2NvdXBlL2NsZS9vdmVydmlldy5odG1sIiwidXJsUmVmZXJyZXIiOiIiLCJjaGFubmVsIjoiV2ViIiwiYmVhY29uVmVyc2lvbiI6MTYsImNvbmZpZ1ZlcnNpb24iOiI2MyIsImNvbnRlbnRab25lcyI6W119LCJ1c2VyIjp7ImFub25JZCI6IjdmYjRkODEwYzY1N2YyMTgifSwiY29uc2VudHMiOltdLCJhY2NvdW50Ijp7fSwiX3Rvb2xzRXZlbnRMaW5rSWQiOiIxNTA0NjA1MDcwMTM1MTYyIiwiZGVidWciOnsiZXhwbGFuYXRpb25zIjp0cnVlfX0%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x55851d731cea <unknown>
#1 0x55851d1e25f0 <unknown>
#2 0x55851d1c8e86 <unknown>
#3 0x55851d1c779a <unknown>
#4 0x55851d1c7eff <unknown>
#5 0x55851d1c7e54 <unknown>
#6 0x55851d1e67ff <unknown>
#7 0x55851d28b9aa <unknown>
#8 0x55851d259662 <unknown>
#9 0x55851d27f660 <unknown>
#10 0x55851d259433 <unknown>
#11 0x55851d225ea3 <unknown>
#12 0x55851d226b01 <unknown>
#13 0x55851d6f6b3b <unknown>
#14 0x55851d6faa21 <unknown>
#15 0x55851d6ddc32 <unknown>
#16 0x55851d6fb594 <unknown>
#17 0x55851d6c1eef <unknown>
#18 0x55851d71fd98 <unknown>
#19 0x55851d71ff76 <unknown>
#20 0x55851d730b36 <unknown>
#21 0x7fc48689caa4 <unknown>
#22 0x7fc486929c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJhY3Rpb24iOiJzZXRfdXNlcl9hdHRyaWJ1dGUiLCJhY2NvdW50Ijp7ImF0dHJpYnV0ZXMiOnsibGFzdFBpUGFnZSI6eyJ2ZWhpY2xlUEkiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56Lml0L3Bhc3NlbmdlcmNhcnMvbW9kZWxzL2NvdXBlL2NsZS9vdmVydmlldy5odG1sIiwidmVoaWNsZUNvZGUiOiJjMjM2IiwidmVoaWNsZUJNIjoiMjM2MyIsInZlaGljbGVQSUhpc3RvcnkiOiIyMzYzIiwidGltZXN0YW1wIjoxNzQ1NDMwMzExNDkwLCJleHBpcmF0aW9uIjoxMjB9fX0sInVzZXIiOnsiYXR0cmlidXRlcyI6eyJnYUNsaWVudElEIjoiMTg2MTQwNjE5MC4xNzQ1NDMwMzA5In0sImFub25JZCI6IjdmYjRkODEwYzY1N2YyMTgifSwic291cmNlIjp7InVybCI6Imh0dHBzOi8vd3d3Lm1lcmNlZGVzLWJlbnouaXQvcGFzc2VuZ2VyY2Fycy9tb2RlbHMvY291cGUvY2xlL292ZXJ2aWV3Lmh0bWwiLCJ1cmxSZWZlcnJlciI6IiIsImNoYW5uZWwiOiJXZWIiLCJiZWFjb25WZXJzaW9uIjoxNiwiY29uZmlnVmVyc2lvbiI6IjYzIiwiY29udGVudFpvbmVzIjpbXX0sImNvbnNlbnRzIjpbXSwiX3Rvb2xzRXZlbnRMaW5rSWQiOiI5MTIxMTk1ODE5MzYyMjcyIiwiZGVidWciOnsiZXhwbGFuYXRpb25zIjp0cnVlfX0%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x55851d731cea <unknown>
#1 0x55851d1e25f0 <unknown>
#2 0x55851d1c8e86 <unknown>
#3 0x55851d1c779a <unknown>
#4 0x55851d1c7eff <unknown>
#5 0x55851d1c7e54 <unknown>
#6 0x55851d1e67ff <unknown>
#7 0x55851d28b9aa <unknown>
#8 0x55851d259662 <unknown>
#9 0x55851d27f660 <unknown>
#10 0x55851d259433 <unknown>
#11 0x55851d225ea3 <unknown>
#12 0x55851d226b01 <unknown>
#13 0x55851d6f6b3b <unknown>
#14 0x55851d6faa21 <unknown>
#15 0x55851d6ddc32 <unknown>
#16 0x55851d6fb594 <unknown>
#17 0x55851d6c1eef <unknown>
#18 0x55851d71fd98 <unknown>
#19 0x55851d71ff76 <unknown>
#20 0x55851d730b36 <unknown>
#21 0x7fc48689caa4 <unknown>
#22 0x7fc486929c3c <unknown>

ERROR    root:VerifyPersonalizationAndCapture.py:18 ❌ Error attaching screenshot to Allure: [Errno 2] No such file or directory: '/home/runner/work/QA-App-Allure/QA-App-Allure/Tests/BFV1_attempt_2.png'
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f666f0b9510>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/d9cda72ff542bc6c11bf9f5d2e590058
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f666c647010>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/d9cda72ff542bc6c11bf9f5d2e590058
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f666c646850>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/d9cda72ff542bc6c11bf9f5d2e590058