ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJhY3Rpb24iOiJWaXNpdGVkIC0gb3ZlcnZpZXciLCJ1c2VyIjp7ImF0dHJpYnV0ZXMiOnsiZ2FDbGllbnRJRCI6IjUxMTk4NTU4My4xNzQ1NDMxODY5In0sImFub25JZCI6IjgxNDgwNjU3YjkwMGI0MDkifSwic291cmNlIjp7InVybCI6Imh0dHBzOi8vd3d3Lm1lcmNlZGVzLWJlbnouaXQvcGFzc2VuZ2VyY2Fycy9tb2RlbHMvY291cGUvY2xlL292ZXJ2aWV3Lmh0bWwiLCJ1cmxSZWZlcnJlciI6IiIsImNoYW5uZWwiOiJXZWIiLCJiZWFjb25WZXJzaW9uIjoxNiwiY29uZmlnVmVyc2lvbiI6IjYzIiwiY29udGVudFpvbmVzIjpbXX0sImNvbnNlbnRzIjpbXSwiYWNjb3VudCI6e30sIl90b29sc0V2ZW50TGlua0lkIjoiMTY1Mjc3OTAzODY4MjUwNDgiLCJkZWJ1ZyI6eyJleHBsYW5hdGlvbnMiOnRydWV9fQ%3D%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x557cb46e9cea <unknown>
#1 0x557cb419a5f0 <unknown>
#2 0x557cb4180e86 <unknown>
#3 0x557cb417f79a <unknown>
#4 0x557cb417feff <unknown>
#5 0x557cb417fe54 <unknown>
#6 0x557cb419e7ff <unknown>
#7 0x557cb42439aa <unknown>
#8 0x557cb4211662 <unknown>
#9 0x557cb4237660 <unknown>
#10 0x557cb4211433 <unknown>
#11 0x557cb41ddea3 <unknown>
#12 0x557cb41deb01 <unknown>
#13 0x557cb46aeb3b <unknown>
#14 0x557cb46b2a21 <unknown>
#15 0x557cb4695c32 <unknown>
#16 0x557cb46b3594 <unknown>
#17 0x557cb4679eef <unknown>
#18 0x557cb46d7d98 <unknown>
#19 0x557cb46d7f76 <unknown>
#20 0x557cb46e8b36 <unknown>
#21 0x7f26dee9caa4 <unknown>
#22 0x7f26def29c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJpdGVtQWN0aW9uIjoiVmlldyBJdGVtIiwiY2F0YWxvZyI6eyJJdGVtQ2xhc3MiOnsiX2lkIjoib3ZlcnZpZXcifX0sInVzZXIiOnsiYXR0cmlidXRlcyI6eyJnYUNsaWVudElEIjoiNTExOTg1NTgzLjE3NDU0MzE4NjkifSwiYW5vbklkIjoiODE0ODA2NTdiOTAwYjQwOSJ9LCJzb3VyY2UiOnsidXJsIjoiaHR0cHM6Ly93d3cubWVyY2VkZXMtYmVuei5pdC9wYXNzZW5nZXJjYXJzL21vZGVscy9jb3VwZS9jbGUvb3ZlcnZpZXcuaHRtbCIsInVybFJlZmVycmVyIjoiIiwiY2hhbm5lbCI6IldlYiIsImJlYWNvblZlcnNpb24iOjE2LCJjb25maWdWZXJzaW9uIjoiNjMiLCJjb250ZW50Wm9uZXMiOltdfSwiY29uc2VudHMiOltdLCJhY2NvdW50Ijp7fSwicGVyZm9ybWFuY2UiOnsic2RrUGFyc2VUaW1lIjoxfSwiX3Rvb2xzRXZlbnRMaW5rSWQiOiI2OTE4MTUwNTQyODU3MDc5IiwiZGVidWciOnsiZXhwbGFuYXRpb25zIjp0cnVlfX0%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x557cb46e9cea <unknown>
#1 0x557cb419a5f0 <unknown>
#2 0x557cb4180e86 <unknown>
#3 0x557cb417f79a <unknown>
#4 0x557cb417feff <unknown>
#5 0x557cb417fe54 <unknown>
#6 0x557cb419e7ff <unknown>
#7 0x557cb42439aa <unknown>
#8 0x557cb4211662 <unknown>
#9 0x557cb4237660 <unknown>
#10 0x557cb4211433 <unknown>
#11 0x557cb41ddea3 <unknown>
#12 0x557cb41deb01 <unknown>
#13 0x557cb46aeb3b <unknown>
#14 0x557cb46b2a21 <unknown>
#15 0x557cb4695c32 <unknown>
#16 0x557cb46b3594 <unknown>
#17 0x557cb4679eef <unknown>
#18 0x557cb46d7d98 <unknown>
#19 0x557cb46d7f76 <unknown>
#20 0x557cb46e8b36 <unknown>
#21 0x7f26dee9caa4 <unknown>
#22 0x7f26def29c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJhY3Rpb24iOiJQcm9kdWN0IEluZm9ybWF0aW9uIFBhZ2UgLSBvdmVydmlldyAyMzYzIiwiaXRlbUFjdGlvbiI6IlZpZXcgSXRlbSIsInNvdXJjZSI6eyJwYWdlVHlwZSI6InByb2R1Y3RfaW5mb3JtYXRpb24iLCJsb2NhbGUiOiJpdF9JVCIsImNvbnRlbnRab25lcyI6WyJnbG9iYWxfUElfTkwiLCJwaV9iYW5uZXJfTkwiLCJlcXMtc3BlY2lhbF9OTCJdLCJ1cmwiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56Lml0L3Bhc3NlbmdlcmNhcnMvbW9kZWxzL2NvdXBlL2NsZS9vdmVydmlldy5odG1sIiwidXJsUmVmZXJyZXIiOiIiLCJjaGFubmVsIjoiV2ViIiwiYmVhY29uVmVyc2lvbiI6MTYsImNvbmZpZ1ZlcnNpb24iOiI2MyJ9LCJmbGFncyI6eyJwYWdlVmlldyI6dHJ1ZX0sInVzZXIiOnsiYXR0cmlidXRlcyI6eyJnYUNsaWVudElEIjoiNTExOTg1NTgzLjE3NDU0MzE4NjkifSwiYW5vbklkIjoiODE0ODA2NTdiOTAwYjQwOSJ9LCJwZXJmb3JtYW5jZSI6eyJzZGtQYXJzZVRpbWUiOjF9LCJkZWJ1ZyI6eyJleHBsYW5hdGlvbnMiOnRydWV9LCJjYXRhbG9nIjp7IlByb2R1Y3QiOnsiX2lkIjoiMjM2MyIsImRpbWVuc2lvbnMiOnsiQmF1bXVzdGVyU2hvcnQiOlsiMjM2MyJdfX19LCJjb25zZW50cyI6W10sImFjY291bnQiOnt9LCJfdG9vbHNFdmVudExpbmtJZCI6IjM3MDI2ODQyOTg3ODM1OTQifQ%3D%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x557cb46e9cea <unknown>
#1 0x557cb419a5f0 <unknown>
#2 0x557cb4180e86 <unknown>
#3 0x557cb417f79a <unknown>
#4 0x557cb417feff <unknown>
#5 0x557cb417fe54 <unknown>
#6 0x557cb419e7ff <unknown>
#7 0x557cb42439aa <unknown>
#8 0x557cb4211662 <unknown>
#9 0x557cb4237660 <unknown>
#10 0x557cb4211433 <unknown>
#11 0x557cb41ddea3 <unknown>
#12 0x557cb41deb01 <unknown>
#13 0x557cb46aeb3b <unknown>
#14 0x557cb46b2a21 <unknown>
#15 0x557cb4695c32 <unknown>
#16 0x557cb46b3594 <unknown>
#17 0x557cb4679eef <unknown>
#18 0x557cb46d7d98 <unknown>
#19 0x557cb46d7f76 <unknown>
#20 0x557cb46e8b36 <unknown>
#21 0x7f26dee9caa4 <unknown>
#22 0x7f26def29c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJhY3Rpb24iOiJzZXRfdXNlcl9hdHRyaWJ1dGUiLCJhY2NvdW50Ijp7ImF0dHJpYnV0ZXMiOnsibGFzdFBpUGFnZSI6eyJ2ZWhpY2xlUEkiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56Lml0L3Bhc3NlbmdlcmNhcnMvbW9kZWxzL2NvdXBlL2NsZS9vdmVydmlldy5odG1sIiwidmVoaWNsZUNvZGUiOiJjMjM2IiwidmVoaWNsZUJNIjoiMjM2MyIsInZlaGljbGVQSUhpc3RvcnkiOiIyMzYzIiwidGltZXN0YW1wIjoxNzQ1NDMxODczMTUzLCJleHBpcmF0aW9uIjoxMjB9fX0sInVzZXIiOnsiYXR0cmlidXRlcyI6eyJnYUNsaWVudElEIjoiNTExOTg1NTgzLjE3NDU0MzE4NjkifSwiYW5vbklkIjoiODE0ODA2NTdiOTAwYjQwOSJ9LCJzb3VyY2UiOnsidXJsIjoiaHR0cHM6Ly93d3cubWVyY2VkZXMtYmVuei5pdC9wYXNzZW5nZXJjYXJzL21vZGVscy9jb3VwZS9jbGUvb3ZlcnZpZXcuaHRtbCIsInVybFJlZmVycmVyIjoiIiwiY2hhbm5lbCI6IldlYiIsImJlYWNvblZlcnNpb24iOjE2LCJjb25maWdWZXJzaW9uIjoiNjMiLCJjb250ZW50Wm9uZXMiOltdfSwiY29uc2VudHMiOltdLCJfdG9vbHNFdmVudExpbmtJZCI6IjIxMDQxMTAyNDA5NjQ3MjE3IiwiZGVidWciOnsiZXhwbGFuYXRpb25zIjp0cnVlfX0%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x557cb46e9cea <unknown>
#1 0x557cb419a5f0 <unknown>
#2 0x557cb4180e86 <unknown>
#3 0x557cb417f79a <unknown>
#4 0x557cb417feff <unknown>
#5 0x557cb417fe54 <unknown>
#6 0x557cb419e7ff <unknown>
#7 0x557cb42439aa <unknown>
#8 0x557cb4211662 <unknown>
#9 0x557cb4237660 <unknown>
#10 0x557cb4211433 <unknown>
#11 0x557cb41ddea3 <unknown>
#12 0x557cb41deb01 <unknown>
#13 0x557cb46aeb3b <unknown>
#14 0x557cb46b2a21 <unknown>
#15 0x557cb4695c32 <unknown>
#16 0x557cb46b3594 <unknown>
#17 0x557cb4679eef <unknown>
#18 0x557cb46d7d98 <unknown>
#19 0x557cb46d7f76 <unknown>
#20 0x557cb46e8b36 <unknown>
#21 0x7f26dee9caa4 <unknown>
#22 0x7f26def29c3c <unknown>

ERROR    root:VerifyPersonalizationAndCapture.py:18 ‚ùå Error attaching screenshot to Allure: [Errno 2] No such file or directory: '/home/runner/work/QA-App-Allure/QA-App-Allure/Tests/BFV1_attempt_1.png'