ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJpdGVtQWN0aW9uIjoiVmlldyBJdGVtIiwiY2F0YWxvZyI6eyJJdGVtQ2xhc3MiOnsiX2lkIjoib3ZlcnZpZXcifX0sInVzZXIiOnsiYXR0cmlidXRlcyI6eyJnYUNsaWVudElEIjoiNzU4OTA3NjYwLjE3NDU0Mzk0MDAifSwiYW5vbklkIjoiODJjNjc2OGE4OTdmNzE0YSJ9LCJzb3VyY2UiOnsidXJsIjoiaHR0cHM6Ly93d3cubWVyY2VkZXMtYmVuei5pdC9wYXNzZW5nZXJjYXJzL21vZGVscy9zYWxvb24vZXFzL292ZXJ2aWV3Lmh0bWwiLCJ1cmxSZWZlcnJlciI6IiIsImNoYW5uZWwiOiJXZWIiLCJiZWFjb25WZXJzaW9uIjoxNiwiY29uZmlnVmVyc2lvbiI6IjYzIiwiY29udGVudFpvbmVzIjpbXX0sImNvbnNlbnRzIjpbXSwiYWNjb3VudCI6e30sIl90b29sc0V2ZW50TGlua0lkIjoiMjY0MjAwNzc5NDAwNjk4NSIsImRlYnVnIjp7ImV4cGxhbmF0aW9ucyI6dHJ1ZX19: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x55614b4f6cea <unknown>
#1 0x55614afa75f0 <unknown>
#2 0x55614af8de86 <unknown>
#3 0x55614af8c79a <unknown>
#4 0x55614af8ceff <unknown>
#5 0x55614af8ce54 <unknown>
#6 0x55614afab7ff <unknown>
#7 0x55614b0509aa <unknown>
#8 0x55614b01e662 <unknown>
#9 0x55614b044660 <unknown>
#10 0x55614b01e433 <unknown>
#11 0x55614afeaea3 <unknown>
#12 0x55614afebb01 <unknown>
#13 0x55614b4bbb3b <unknown>
#14 0x55614b4bfa21 <unknown>
#15 0x55614b4a2c32 <unknown>
#16 0x55614b4c0594 <unknown>
#17 0x55614b486eef <unknown>
#18 0x55614b4e4d98 <unknown>
#19 0x55614b4e4f76 <unknown>
#20 0x55614b4f5b36 <unknown>
#21 0x7fea3b29caa4 <unknown>
#22 0x7fea3b329c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJhY3Rpb24iOiJQcm9kdWN0IEluZm9ybWF0aW9uIFBhZ2UgLSBvdmVydmlldyAyOTcxIiwiaXRlbUFjdGlvbiI6IlZpZXcgSXRlbSIsInNvdXJjZSI6eyJwYWdlVHlwZSI6InByb2R1Y3RfaW5mb3JtYXRpb24iLCJsb2NhbGUiOiJpdF9JVCIsImNvbnRlbnRab25lcyI6WyJnbG9iYWxfUElfTkwiLCJwaV9iYW5uZXJfTkwiLCJlcXMtc3BlY2lhbF9OTCJdLCJ1cmwiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56Lml0L3Bhc3NlbmdlcmNhcnMvbW9kZWxzL3NhbG9vbi9lcXMvb3ZlcnZpZXcuaHRtbCIsInVybFJlZmVycmVyIjoiIiwiY2hhbm5lbCI6IldlYiIsImJlYWNvblZlcnNpb24iOjE2LCJjb25maWdWZXJzaW9uIjoiNjMifSwiZmxhZ3MiOnsicGFnZVZpZXciOnRydWV9LCJ1c2VyIjp7ImF0dHJpYnV0ZXMiOnsiZ2FDbGllbnRJRCI6Ijc1ODkwNzY2MC4xNzQ1NDM5NDAwIn0sImFub25JZCI6IjgyYzY3NjhhODk3ZjcxNGEifSwicGVyZm9ybWFuY2UiOnt9LCJkZWJ1ZyI6eyJleHBsYW5hdGlvbnMiOnRydWV9LCJjYXRhbG9nIjp7IlByb2R1Y3QiOnsiX2lkIjoiMjk3MSIsImRpbWVuc2lvbnMiOnsiQmF1bXVzdGVyU2hvcnQiOlsiMjk3MSJdfX19LCJjb25zZW50cyI6W10sImFjY291bnQiOnt9LCJfdG9vbHNFdmVudExpbmtJZCI6Ijk1MTIwNDMzMzc4NzQ3MjIifQ%3D%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x55614b4f6cea <unknown>
#1 0x55614afa75f0 <unknown>
#2 0x55614af8de86 <unknown>
#3 0x55614af8c79a <unknown>
#4 0x55614af8ceff <unknown>
#5 0x55614af8ce54 <unknown>
#6 0x55614afab7ff <unknown>
#7 0x55614b0509aa <unknown>
#8 0x55614b01e662 <unknown>
#9 0x55614b044660 <unknown>
#10 0x55614b01e433 <unknown>
#11 0x55614afeaea3 <unknown>
#12 0x55614afebb01 <unknown>
#13 0x55614b4bbb3b <unknown>
#14 0x55614b4bfa21 <unknown>
#15 0x55614b4a2c32 <unknown>
#16 0x55614b4c0594 <unknown>
#17 0x55614b486eef <unknown>
#18 0x55614b4e4d98 <unknown>
#19 0x55614b4e4f76 <unknown>
#20 0x55614b4f5b36 <unknown>
#21 0x7fea3b29caa4 <unknown>
#22 0x7fea3b329c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJhY3Rpb24iOiJWaXNpdGVkIC0gb3ZlcnZpZXciLCJ1c2VyIjp7ImF0dHJpYnV0ZXMiOnsiZ2FDbGllbnRJRCI6Ijc1ODkwNzY2MC4xNzQ1NDM5NDAwIn0sImFub25JZCI6IjgyYzY3NjhhODk3ZjcxNGEifSwic291cmNlIjp7InVybCI6Imh0dHBzOi8vd3d3Lm1lcmNlZGVzLWJlbnouaXQvcGFzc2VuZ2VyY2Fycy9tb2RlbHMvc2Fsb29uL2Vxcy9vdmVydmlldy5odG1sIiwidXJsUmVmZXJyZXIiOiIiLCJjaGFubmVsIjoiV2ViIiwiYmVhY29uVmVyc2lvbiI6MTYsImNvbmZpZ1ZlcnNpb24iOiI2MyIsImNvbnRlbnRab25lcyI6W119LCJjb25zZW50cyI6W10sImFjY291bnQiOnt9LCJfdG9vbHNFdmVudExpbmtJZCI6IjMxMzQ1NDAzNDQ0MTMwNDE1IiwiZGVidWciOnsiZXhwbGFuYXRpb25zIjp0cnVlfX0%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x55614b4f6cea <unknown>
#1 0x55614afa75f0 <unknown>
#2 0x55614af8de86 <unknown>
#3 0x55614af8c79a <unknown>
#4 0x55614af8ceff <unknown>
#5 0x55614af8ce54 <unknown>
#6 0x55614afab7ff <unknown>
#7 0x55614b0509aa <unknown>
#8 0x55614b01e662 <unknown>
#9 0x55614b044660 <unknown>
#10 0x55614b01e433 <unknown>
#11 0x55614afeaea3 <unknown>
#12 0x55614afebb01 <unknown>
#13 0x55614b4bbb3b <unknown>
#14 0x55614b4bfa21 <unknown>
#15 0x55614b4a2c32 <unknown>
#16 0x55614b4c0594 <unknown>
#17 0x55614b486eef <unknown>
#18 0x55614b4e4d98 <unknown>
#19 0x55614b4e4f76 <unknown>
#20 0x55614b4f5b36 <unknown>
#21 0x7fea3b29caa4 <unknown>
#22 0x7fea3b329c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJhY3Rpb24iOiJzZXRfdXNlcl9hdHRyaWJ1dGUiLCJhY2NvdW50Ijp7ImF0dHJpYnV0ZXMiOnsibGFzdFBpUGFnZSI6eyJ2ZWhpY2xlUEkiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56Lml0L3Bhc3NlbmdlcmNhcnMvbW9kZWxzL3NhbG9vbi9lcXMvb3ZlcnZpZXcuaHRtbCIsInZlaGljbGVDb2RlIjoidjI5NyIsInZlaGljbGVCTSI6IjI5NzEiLCJ2ZWhpY2xlUElIaXN0b3J5IjoiMjk3MSIsInRpbWVzdGFtcCI6MTc0NTQzOTQwNDQyNiwiZXhwaXJhdGlvbiI6MTIwfX19LCJ1c2VyIjp7ImF0dHJpYnV0ZXMiOnsiZ2FDbGllbnRJRCI6Ijc1ODkwNzY2MC4xNzQ1NDM5NDAwIn0sImFub25JZCI6IjgyYzY3NjhhODk3ZjcxNGEifSwic291cmNlIjp7InVybCI6Imh0dHBzOi8vd3d3Lm1lcmNlZGVzLWJlbnouaXQvcGFzc2VuZ2VyY2Fycy9tb2RlbHMvc2Fsb29uL2Vxcy9vdmVydmlldy5odG1sIiwidXJsUmVmZXJyZXIiOiIiLCJjaGFubmVsIjoiV2ViIiwiYmVhY29uVmVyc2lvbiI6MTYsImNvbmZpZ1ZlcnNpb24iOiI2MyIsImNvbnRlbnRab25lcyI6W119LCJjb25zZW50cyI6W10sIl90b29sc0V2ZW50TGlua0lkIjoiNjkyNDExMzg5MzE3MjA1OSIsImRlYnVnIjp7ImV4cGxhbmF0aW9ucyI6dHJ1ZX19: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x55614b4f6cea <unknown>
#1 0x55614afa75f0 <unknown>
#2 0x55614af8de86 <unknown>
#3 0x55614af8c79a <unknown>
#4 0x55614af8ceff <unknown>
#5 0x55614af8ce54 <unknown>
#6 0x55614afab7ff <unknown>
#7 0x55614b0509aa <unknown>
#8 0x55614b01e662 <unknown>
#9 0x55614b044660 <unknown>
#10 0x55614b01e433 <unknown>
#11 0x55614afeaea3 <unknown>
#12 0x55614afebb01 <unknown>
#13 0x55614b4bbb3b <unknown>
#14 0x55614b4bfa21 <unknown>
#15 0x55614b4a2c32 <unknown>
#16 0x55614b4c0594 <unknown>
#17 0x55614b486eef <unknown>
#18 0x55614b4e4d98 <unknown>
#19 0x55614b4e4f76 <unknown>
#20 0x55614b4f5b36 <unknown>
#21 0x7fea3b29caa4 <unknown>
#22 0x7fea3b329c3c <unknown>

ERROR    root:VerifyPersonalizationAndCapture.py:111 ❌ Image not found in the specified selector. Error: Message: 

ERROR    root:VerifyPersonalizationAndCapture.py:18 ❌ Error attaching screenshot to Allure: [Errno 2] No such file or directory: '/home/runner/work/QA-App-Allure/QA-App-Allure/Tests/BFV1_attempt_1.png'
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f73b7229750>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/3569ccbdf984ab4b69c2d25a7e952727
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f73b722a110>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/3569ccbdf984ab4b69c2d25a7e952727
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f73b722af50>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/3569ccbdf984ab4b69c2d25a7e952727
ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJhY3Rpb24iOiJQcm9kdWN0IEluZm9ybWF0aW9uIFBhZ2UgLSBvdmVydmlldyAyOTcxIiwiaXRlbUFjdGlvbiI6IlZpZXcgSXRlbSIsInNvdXJjZSI6eyJwYWdlVHlwZSI6InByb2R1Y3RfaW5mb3JtYXRpb24iLCJsb2NhbGUiOiJpdF9JVCIsImNvbnRlbnRab25lcyI6WyJnbG9iYWxfUElfTkwiLCJwaV9iYW5uZXJfTkwiLCJlcXMtc3BlY2lhbF9OTCJdLCJ1cmwiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56Lml0L3Bhc3NlbmdlcmNhcnMvbW9kZWxzL3NhbG9vbi9lcXMvb3ZlcnZpZXcuaHRtbCIsInVybFJlZmVycmVyIjoiIiwiY2hhbm5lbCI6IldlYiIsImJlYWNvblZlcnNpb24iOjE2LCJjb25maWdWZXJzaW9uIjoiNjMifSwiZmxhZ3MiOnsicGFnZVZpZXciOnRydWV9LCJ1c2VyIjp7ImF0dHJpYnV0ZXMiOnsiZ2FDbGllbnRJRCI6IjIxMDUwNzQwNzQuMTc0NTQzOTQzMyJ9LCJhbm9uSWQiOiI0MDNjMTI4OGVlNmQ2OTY2In0sInBlcmZvcm1hbmNlIjp7InNka1BhcnNlVGltZSI6MX0sImRlYnVnIjp7ImV4cGxhbmF0aW9ucyI6dHJ1ZX0sImNhdGFsb2ciOnsiUHJvZHVjdCI6eyJfaWQiOiIyOTcxIiwiZGltZW5zaW9ucyI6eyJCYXVtdXN0ZXJTaG9ydCI6WyIyOTcxIl19fX0sImNvbnNlbnRzIjpbXSwiYWNjb3VudCI6e30sIl90b29sc0V2ZW50TGlua0lkIjoiMzg1MzA5NTQwOTI4OTQ0MyJ9: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x556cc55ddcea <unknown>
#1 0x556cc508e5f0 <unknown>
#2 0x556cc5074e86 <unknown>
#3 0x556cc507379a <unknown>
#4 0x556cc5073eff <unknown>
#5 0x556cc5073e54 <unknown>
#6 0x556cc50927ff <unknown>
#7 0x556cc51379aa <unknown>
#8 0x556cc5105662 <unknown>
#9 0x556cc512b660 <unknown>
#10 0x556cc5105433 <unknown>
#11 0x556cc50d1ea3 <unknown>
#12 0x556cc50d2b01 <unknown>
#13 0x556cc55a2b3b <unknown>
#14 0x556cc55a6a21 <unknown>
#15 0x556cc5589c32 <unknown>
#16 0x556cc55a7594 <unknown>
#17 0x556cc556deef <unknown>
#18 0x556cc55cbd98 <unknown>
#19 0x556cc55cbf76 <unknown>
#20 0x556cc55dcb36 <unknown>
#21 0x7f6d5249caa4 <unknown>
#22 0x7f6d52529c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJpdGVtQWN0aW9uIjoiVmlldyBJdGVtIiwiY2F0YWxvZyI6eyJJdGVtQ2xhc3MiOnsiX2lkIjoib3ZlcnZpZXcifX0sInVzZXIiOnsiYXR0cmlidXRlcyI6eyJnYUNsaWVudElEIjoiMjEwNTA3NDA3NC4xNzQ1NDM5NDMzIn0sImFub25JZCI6IjQwM2MxMjg4ZWU2ZDY5NjYifSwic291cmNlIjp7InVybCI6Imh0dHBzOi8vd3d3Lm1lcmNlZGVzLWJlbnouaXQvcGFzc2VuZ2VyY2Fycy9tb2RlbHMvc2Fsb29uL2Vxcy9vdmVydmlldy5odG1sIiwidXJsUmVmZXJyZXIiOiIiLCJjaGFubmVsIjoiV2ViIiwiYmVhY29uVmVyc2lvbiI6MTYsImNvbmZpZ1ZlcnNpb24iOiI2MyIsImNvbnRlbnRab25lcyI6W119LCJjb25zZW50cyI6W10sImFjY291bnQiOnt9LCJfdG9vbHNFdmVudExpbmtJZCI6Ijg5ODE5MjEzMzk3MTU0MzQiLCJkZWJ1ZyI6eyJleHBsYW5hdGlvbnMiOnRydWV9fQ%3D%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x556cc55ddcea <unknown>
#1 0x556cc508e5f0 <unknown>
#2 0x556cc5074e86 <unknown>
#3 0x556cc507379a <unknown>
#4 0x556cc5073eff <unknown>
#5 0x556cc5073e54 <unknown>
#6 0x556cc50927ff <unknown>
#7 0x556cc51379aa <unknown>
#8 0x556cc5105662 <unknown>
#9 0x556cc512b660 <unknown>
#10 0x556cc5105433 <unknown>
#11 0x556cc50d1ea3 <unknown>
#12 0x556cc50d2b01 <unknown>
#13 0x556cc55a2b3b <unknown>
#14 0x556cc55a6a21 <unknown>
#15 0x556cc5589c32 <unknown>
#16 0x556cc55a7594 <unknown>
#17 0x556cc556deef <unknown>
#18 0x556cc55cbd98 <unknown>
#19 0x556cc55cbf76 <unknown>
#20 0x556cc55dcb36 <unknown>
#21 0x7f6d5249caa4 <unknown>
#22 0x7f6d52529c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJhY3Rpb24iOiJWaXNpdGVkIC0gb3ZlcnZpZXciLCJ1c2VyIjp7ImF0dHJpYnV0ZXMiOnsiZ2FDbGllbnRJRCI6IjIxMDUwNzQwNzQuMTc0NTQzOTQzMyJ9LCJhbm9uSWQiOiI0MDNjMTI4OGVlNmQ2OTY2In0sInNvdXJjZSI6eyJ1cmwiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56Lml0L3Bhc3NlbmdlcmNhcnMvbW9kZWxzL3NhbG9vbi9lcXMvb3ZlcnZpZXcuaHRtbCIsInVybFJlZmVycmVyIjoiIiwiY2hhbm5lbCI6IldlYiIsImJlYWNvblZlcnNpb24iOjE2LCJjb25maWdWZXJzaW9uIjoiNjMiLCJjb250ZW50Wm9uZXMiOltdfSwiY29uc2VudHMiOltdLCJhY2NvdW50Ijp7fSwicGVyZm9ybWFuY2UiOnsic2RrUGFyc2VUaW1lIjoxfSwiX3Rvb2xzRXZlbnRMaW5rSWQiOiI3Njg4MzI0NzY2MzE3NjYxIiwiZGVidWciOnsiZXhwbGFuYXRpb25zIjp0cnVlfX0%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x556cc55ddcea <unknown>
#1 0x556cc508e5f0 <unknown>
#2 0x556cc5074e86 <unknown>
#3 0x556cc507379a <unknown>
#4 0x556cc5073eff <unknown>
#5 0x556cc5073e54 <unknown>
#6 0x556cc50927ff <unknown>
#7 0x556cc51379aa <unknown>
#8 0x556cc5105662 <unknown>
#9 0x556cc512b660 <unknown>
#10 0x556cc5105433 <unknown>
#11 0x556cc50d1ea3 <unknown>
#12 0x556cc50d2b01 <unknown>
#13 0x556cc55a2b3b <unknown>
#14 0x556cc55a6a21 <unknown>
#15 0x556cc5589c32 <unknown>
#16 0x556cc55a7594 <unknown>
#17 0x556cc556deef <unknown>
#18 0x556cc55cbd98 <unknown>
#19 0x556cc55cbf76 <unknown>
#20 0x556cc55dcb36 <unknown>
#21 0x7f6d5249caa4 <unknown>
#22 0x7f6d52529c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJhY3Rpb24iOiJzZXRfdXNlcl9hdHRyaWJ1dGUiLCJhY2NvdW50Ijp7ImF0dHJpYnV0ZXMiOnsibGFzdFBpUGFnZSI6eyJ2ZWhpY2xlUEkiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56Lml0L3Bhc3NlbmdlcmNhcnMvbW9kZWxzL3NhbG9vbi9lcXMvb3ZlcnZpZXcuaHRtbCIsInZlaGljbGVDb2RlIjoidjI5NyIsInZlaGljbGVCTSI6IjI5NzEiLCJ2ZWhpY2xlUElIaXN0b3J5IjoiMjk3MSIsInRpbWVzdGFtcCI6MTc0NTQzOTQzNzEwMCwiZXhwaXJhdGlvbiI6MTIwfX19LCJ1c2VyIjp7ImF0dHJpYnV0ZXMiOnsiZ2FDbGllbnRJRCI6IjIxMDUwNzQwNzQuMTc0NTQzOTQzMyJ9LCJhbm9uSWQiOiI0MDNjMTI4OGVlNmQ2OTY2In0sInNvdXJjZSI6eyJ1cmwiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56Lml0L3Bhc3NlbmdlcmNhcnMvbW9kZWxzL3NhbG9vbi9lcXMvb3ZlcnZpZXcuaHRtbCIsInVybFJlZmVycmVyIjoiIiwiY2hhbm5lbCI6IldlYiIsImJlYWNvblZlcnNpb24iOjE2LCJjb25maWdWZXJzaW9uIjoiNjMiLCJjb250ZW50Wm9uZXMiOltdfSwiY29uc2VudHMiOltdLCJfdG9vbHNFdmVudExpbmtJZCI6IjYzNjI2MDUyMzg3MTczNTIiLCJkZWJ1ZyI6eyJleHBsYW5hdGlvbnMiOnRydWV9fQ%3D%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x556cc55ddcea <unknown>
#1 0x556cc508e5f0 <unknown>
#2 0x556cc5074e86 <unknown>
#3 0x556cc507379a <unknown>
#4 0x556cc5073eff <unknown>
#5 0x556cc5073e54 <unknown>
#6 0x556cc50927ff <unknown>
#7 0x556cc51379aa <unknown>
#8 0x556cc5105662 <unknown>
#9 0x556cc512b660 <unknown>
#10 0x556cc5105433 <unknown>
#11 0x556cc50d1ea3 <unknown>
#12 0x556cc50d2b01 <unknown>
#13 0x556cc55a2b3b <unknown>
#14 0x556cc55a6a21 <unknown>
#15 0x556cc5589c32 <unknown>
#16 0x556cc55a7594 <unknown>
#17 0x556cc556deef <unknown>
#18 0x556cc55cbd98 <unknown>
#19 0x556cc55cbf76 <unknown>
#20 0x556cc55dcb36 <unknown>
#21 0x7f6d5249caa4 <unknown>
#22 0x7f6d52529c3c <unknown>

ERROR    root:VerifyPersonalizationAndCapture.py:18 ❌ Error attaching screenshot to Allure: [Errno 2] No such file or directory: '/home/runner/work/QA-App-Allure/QA-App-Allure/Tests/BFV1_attempt_2.png'
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f73b7217910>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/3569ccbdf984ab4b69c2d25a7e952727
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f73b7215210>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/3569ccbdf984ab4b69c2d25a7e952727
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f73b7216d90>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/3569ccbdf984ab4b69c2d25a7e952727