ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJhY3Rpb24iOiJWaXNpdGVkIC0gb3ZlcnZpZXciLCJzb3VyY2UiOnsidXJsIjoiaHR0cHM6Ly93d3cubWVyY2VkZXMtYmVuei5pdC9wYXNzZW5nZXJjYXJzL21vZGVscy9jb3VwZS9jbGEvb3ZlcnZpZXcuaHRtbCIsInVybFJlZmVycmVyIjoiIiwiY2hhbm5lbCI6IldlYiIsImJlYWNvblZlcnNpb24iOjE2LCJjb25maWdWZXJzaW9uIjoiNjMiLCJjb250ZW50Wm9uZXMiOltdfSwidXNlciI6eyJhbm9uSWQiOiI1YjIxZGYzYmViZjRhY2FhIn0sImNvbnNlbnRzIjpbXSwiYWNjb3VudCI6e30sIl90b29sc0V2ZW50TGlua0lkIjoiNzUwODA3OTc4NzI2OTM3NyIsImRlYnVnIjp7ImV4cGxhbmF0aW9ucyI6dHJ1ZX19: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x5595c0cf8cea <unknown>
#1 0x5595c07a95f0 <unknown>
#2 0x5595c078fe86 <unknown>
#3 0x5595c078e79a <unknown>
#4 0x5595c078eeff <unknown>
#5 0x5595c078ee54 <unknown>
#6 0x5595c07ad7ff <unknown>
#7 0x5595c08529aa <unknown>
#8 0x5595c0820662 <unknown>
#9 0x5595c0846660 <unknown>
#10 0x5595c0820433 <unknown>
#11 0x5595c07ecea3 <unknown>
#12 0x5595c07edb01 <unknown>
#13 0x5595c0cbdb3b <unknown>
#14 0x5595c0cc1a21 <unknown>
#15 0x5595c0ca4c32 <unknown>
#16 0x5595c0cc2594 <unknown>
#17 0x5595c0c88eef <unknown>
#18 0x5595c0ce6d98 <unknown>
#19 0x5595c0ce6f76 <unknown>
#20 0x5595c0cf7b36 <unknown>
#21 0x7f4b1c09caa4 <unknown>
#22 0x7f4b1c129c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJpdGVtQWN0aW9uIjoiVmlldyBJdGVtIiwiY2F0YWxvZyI6eyJJdGVtQ2xhc3MiOnsiX2lkIjoib3ZlcnZpZXcifX0sInNvdXJjZSI6eyJ1cmwiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56Lml0L3Bhc3NlbmdlcmNhcnMvbW9kZWxzL2NvdXBlL2NsYS9vdmVydmlldy5odG1sIiwidXJsUmVmZXJyZXIiOiIiLCJjaGFubmVsIjoiV2ViIiwiYmVhY29uVmVyc2lvbiI6MTYsImNvbmZpZ1ZlcnNpb24iOiI2MyIsImNvbnRlbnRab25lcyI6W119LCJ1c2VyIjp7ImFub25JZCI6IjViMjFkZjNiZWJmNGFjYWEifSwiY29uc2VudHMiOltdLCJhY2NvdW50Ijp7fSwicGVyZm9ybWFuY2UiOnsic2RrUGFyc2VUaW1lIjoxfSwiX3Rvb2xzRXZlbnRMaW5rSWQiOiIyOTk4NTUxMDMxODQ0ODY3IiwiZGVidWciOnsiZXhwbGFuYXRpb25zIjp0cnVlfX0%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x5595c0cf8cea <unknown>
#1 0x5595c07a95f0 <unknown>
#2 0x5595c078fe86 <unknown>
#3 0x5595c078e79a <unknown>
#4 0x5595c078eeff <unknown>
#5 0x5595c078ee54 <unknown>
#6 0x5595c07ad7ff <unknown>
#7 0x5595c08529aa <unknown>
#8 0x5595c0820662 <unknown>
#9 0x5595c0846660 <unknown>
#10 0x5595c0820433 <unknown>
#11 0x5595c07ecea3 <unknown>
#12 0x5595c07edb01 <unknown>
#13 0x5595c0cbdb3b <unknown>
#14 0x5595c0cc1a21 <unknown>
#15 0x5595c0ca4c32 <unknown>
#16 0x5595c0cc2594 <unknown>
#17 0x5595c0c88eef <unknown>
#18 0x5595c0ce6d98 <unknown>
#19 0x5595c0ce6f76 <unknown>
#20 0x5595c0cf7b36 <unknown>
#21 0x7f4b1c09caa4 <unknown>
#22 0x7f4b1c129c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJhY3Rpb24iOiJQcm9kdWN0IEluZm9ybWF0aW9uIFBhZ2UgLSBvdmVydmlldyAxMTgzIiwiaXRlbUFjdGlvbiI6IlZpZXcgSXRlbSIsInNvdXJjZSI6eyJwYWdlVHlwZSI6InByb2R1Y3RfaW5mb3JtYXRpb24iLCJsb2NhbGUiOiJpdF9JVCIsImNvbnRlbnRab25lcyI6WyJnbG9iYWxfUElfTkwiLCJwaV9iYW5uZXJfTkwiLCJlcXMtc3BlY2lhbF9OTCJdLCJ1cmwiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56Lml0L3Bhc3NlbmdlcmNhcnMvbW9kZWxzL2NvdXBlL2NsYS9vdmVydmlldy5odG1sIiwidXJsUmVmZXJyZXIiOiIiLCJjaGFubmVsIjoiV2ViIiwiYmVhY29uVmVyc2lvbiI6MTYsImNvbmZpZ1ZlcnNpb24iOiI2MyJ9LCJmbGFncyI6eyJwYWdlVmlldyI6dHJ1ZX0sInVzZXIiOnsiYW5vbklkIjoiNWIyMWRmM2JlYmY0YWNhYSJ9LCJwZXJmb3JtYW5jZSI6eyJzZGtQYXJzZVRpbWUiOjF9LCJkZWJ1ZyI6eyJleHBsYW5hdGlvbnMiOnRydWV9LCJjYXRhbG9nIjp7IlByb2R1Y3QiOnsiX2lkIjoiMTE4MyIsImRpbWVuc2lvbnMiOnsiQmF1bXVzdGVyU2hvcnQiOlsiMTE4MyJdfX19LCJjb25zZW50cyI6W10sImFjY291bnQiOnt9LCJfdG9vbHNFdmVudExpbmtJZCI6IjM5ODYzNzc2MTgxODI5MTI1In0%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x5595c0cf8cea <unknown>
#1 0x5595c07a95f0 <unknown>
#2 0x5595c078fe86 <unknown>
#3 0x5595c078e79a <unknown>
#4 0x5595c078eeff <unknown>
#5 0x5595c078ee54 <unknown>
#6 0x5595c07ad7ff <unknown>
#7 0x5595c08529aa <unknown>
#8 0x5595c0820662 <unknown>
#9 0x5595c0846660 <unknown>
#10 0x5595c0820433 <unknown>
#11 0x5595c07ecea3 <unknown>
#12 0x5595c07edb01 <unknown>
#13 0x5595c0cbdb3b <unknown>
#14 0x5595c0cc1a21 <unknown>
#15 0x5595c0ca4c32 <unknown>
#16 0x5595c0cc2594 <unknown>
#17 0x5595c0c88eef <unknown>
#18 0x5595c0ce6d98 <unknown>
#19 0x5595c0ce6f76 <unknown>
#20 0x5595c0cf7b36 <unknown>
#21 0x7f4b1c09caa4 <unknown>
#22 0x7f4b1c129c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJhY3Rpb24iOiJzZXRfdXNlcl9hdHRyaWJ1dGUiLCJhY2NvdW50Ijp7ImF0dHJpYnV0ZXMiOnsibGFzdFBpUGFnZSI6eyJ2ZWhpY2xlUEkiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56Lml0L3Bhc3NlbmdlcmNhcnMvbW9kZWxzL2NvdXBlL2NsYS9vdmVydmlldy5odG1sIiwidmVoaWNsZUNvZGUiOiJjMTE4LWZsIiwidmVoaWNsZUJNIjoiMTE4MyIsInZlaGljbGVQSUhpc3RvcnkiOiIxMTgzIiwidGltZXN0YW1wIjoxNzQ1NDQxMjI5MTA1LCJleHBpcmF0aW9uIjoxMjB9fX0sInVzZXIiOnsiYXR0cmlidXRlcyI6eyJnYUNsaWVudElEIjoiMTk5OTM3MzAzNC4xNzQ1NDQxMjI3In0sImFub25JZCI6IjViMjFkZjNiZWJmNGFjYWEifSwic291cmNlIjp7InVybCI6Imh0dHBzOi8vd3d3Lm1lcmNlZGVzLWJlbnouaXQvcGFzc2VuZ2VyY2Fycy9tb2RlbHMvY291cGUvY2xhL292ZXJ2aWV3Lmh0bWwiLCJ1cmxSZWZlcnJlciI6IiIsImNoYW5uZWwiOiJXZWIiLCJiZWFjb25WZXJzaW9uIjoxNiwiY29uZmlnVmVyc2lvbiI6IjYzIiwiY29udGVudFpvbmVzIjpbXX0sImNvbnNlbnRzIjpbXSwiX3Rvb2xzRXZlbnRMaW5rSWQiOiI0OTM2OTUyOTI3NzkzOTE3IiwiZGVidWciOnsiZXhwbGFuYXRpb25zIjp0cnVlfX0%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x5595c0cf8cea <unknown>
#1 0x5595c07a95f0 <unknown>
#2 0x5595c078fe86 <unknown>
#3 0x5595c078e79a <unknown>
#4 0x5595c078eeff <unknown>
#5 0x5595c078ee54 <unknown>
#6 0x5595c07ad7ff <unknown>
#7 0x5595c08529aa <unknown>
#8 0x5595c0820662 <unknown>
#9 0x5595c0846660 <unknown>
#10 0x5595c0820433 <unknown>
#11 0x5595c07ecea3 <unknown>
#12 0x5595c07edb01 <unknown>
#13 0x5595c0cbdb3b <unknown>
#14 0x5595c0cc1a21 <unknown>
#15 0x5595c0ca4c32 <unknown>
#16 0x5595c0cc2594 <unknown>
#17 0x5595c0c88eef <unknown>
#18 0x5595c0ce6d98 <unknown>
#19 0x5595c0ce6f76 <unknown>
#20 0x5595c0cf7b36 <unknown>
#21 0x7f4b1c09caa4 <unknown>
#22 0x7f4b1c129c3c <unknown>

ERROR    root:VerifyPersonalizationAndCapture.py:111 ❌ Image not found in the specified selector. Error: Message: 

ERROR    root:VerifyPersonalizationAndCapture.py:18 ❌ Error attaching screenshot to Allure: [Errno 2] No such file or directory: '/home/runner/work/QA-App-Allure/QA-App-Allure/Tests/BFV1_attempt_1.png'
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6251dfced0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/6f0fa90123feca0443ec42fd1c1cdc7a
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6251dff990>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/6f0fa90123feca0443ec42fd1c1cdc7a
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6251dff490>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/6f0fa90123feca0443ec42fd1c1cdc7a
ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJhY3Rpb24iOiJWaXNpdGVkIC0gb3ZlcnZpZXciLCJ1c2VyIjp7ImF0dHJpYnV0ZXMiOnsiZ2FDbGllbnRJRCI6IjM2Mjg4MDc5NC4xNzQ1NDQxMjU5In0sImFub25JZCI6IjcxODdlYTMyNzU2NGE3ZDcifSwic291cmNlIjp7InVybCI6Imh0dHBzOi8vd3d3Lm1lcmNlZGVzLWJlbnouaXQvcGFzc2VuZ2VyY2Fycy9tb2RlbHMvY291cGUvY2xhL292ZXJ2aWV3Lmh0bWwiLCJ1cmxSZWZlcnJlciI6IiIsImNoYW5uZWwiOiJXZWIiLCJiZWFjb25WZXJzaW9uIjoxNiwiY29uZmlnVmVyc2lvbiI6IjYzIiwiY29udGVudFpvbmVzIjpbXX0sImNvbnNlbnRzIjpbXSwiYWNjb3VudCI6e30sIl90b29sc0V2ZW50TGlua0lkIjoiMTk4NDgyMDI4OTA0NDE1OCIsImRlYnVnIjp7ImV4cGxhbmF0aW9ucyI6dHJ1ZX19: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x55b9ff754cea <unknown>
#1 0x55b9ff2055f0 <unknown>
#2 0x55b9ff1ebe86 <unknown>
#3 0x55b9ff1ea79a <unknown>
#4 0x55b9ff1eaeff <unknown>
#5 0x55b9ff1eae54 <unknown>
#6 0x55b9ff2097ff <unknown>
#7 0x55b9ff2ae9aa <unknown>
#8 0x55b9ff27c662 <unknown>
#9 0x55b9ff2a2660 <unknown>
#10 0x55b9ff27c433 <unknown>
#11 0x55b9ff248ea3 <unknown>
#12 0x55b9ff249b01 <unknown>
#13 0x55b9ff719b3b <unknown>
#14 0x55b9ff71da21 <unknown>
#15 0x55b9ff700c32 <unknown>
#16 0x55b9ff71e594 <unknown>
#17 0x55b9ff6e4eef <unknown>
#18 0x55b9ff742d98 <unknown>
#19 0x55b9ff742f76 <unknown>
#20 0x55b9ff753b36 <unknown>
#21 0x7fa66b49caa4 <unknown>
#22 0x7fa66b529c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJpdGVtQWN0aW9uIjoiVmlldyBJdGVtIiwiY2F0YWxvZyI6eyJJdGVtQ2xhc3MiOnsiX2lkIjoib3ZlcnZpZXcifX0sInVzZXIiOnsiYXR0cmlidXRlcyI6eyJnYUNsaWVudElEIjoiMzYyODgwNzk0LjE3NDU0NDEyNTkifSwiYW5vbklkIjoiNzE4N2VhMzI3NTY0YTdkNyJ9LCJzb3VyY2UiOnsidXJsIjoiaHR0cHM6Ly93d3cubWVyY2VkZXMtYmVuei5pdC9wYXNzZW5nZXJjYXJzL21vZGVscy9jb3VwZS9jbGEvb3ZlcnZpZXcuaHRtbCIsInVybFJlZmVycmVyIjoiIiwiY2hhbm5lbCI6IldlYiIsImJlYWNvblZlcnNpb24iOjE2LCJjb25maWdWZXJzaW9uIjoiNjMiLCJjb250ZW50Wm9uZXMiOltdfSwiY29uc2VudHMiOltdLCJhY2NvdW50Ijp7fSwicGVyZm9ybWFuY2UiOnsic2RrUGFyc2VUaW1lIjoxfSwiX3Rvb2xzRXZlbnRMaW5rSWQiOiI5MjM3ODY0ODMzNjkyNTE4IiwiZGVidWciOnsiZXhwbGFuYXRpb25zIjp0cnVlfX0%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x55b9ff754cea <unknown>
#1 0x55b9ff2055f0 <unknown>
#2 0x55b9ff1ebe86 <unknown>
#3 0x55b9ff1ea79a <unknown>
#4 0x55b9ff1eaeff <unknown>
#5 0x55b9ff1eae54 <unknown>
#6 0x55b9ff2097ff <unknown>
#7 0x55b9ff2ae9aa <unknown>
#8 0x55b9ff27c662 <unknown>
#9 0x55b9ff2a2660 <unknown>
#10 0x55b9ff27c433 <unknown>
#11 0x55b9ff248ea3 <unknown>
#12 0x55b9ff249b01 <unknown>
#13 0x55b9ff719b3b <unknown>
#14 0x55b9ff71da21 <unknown>
#15 0x55b9ff700c32 <unknown>
#16 0x55b9ff71e594 <unknown>
#17 0x55b9ff6e4eef <unknown>
#18 0x55b9ff742d98 <unknown>
#19 0x55b9ff742f76 <unknown>
#20 0x55b9ff753b36 <unknown>
#21 0x7fa66b49caa4 <unknown>
#22 0x7fa66b529c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJhY3Rpb24iOiJQcm9kdWN0IEluZm9ybWF0aW9uIFBhZ2UgLSBvdmVydmlldyAxMTgzIiwiaXRlbUFjdGlvbiI6IlZpZXcgSXRlbSIsInNvdXJjZSI6eyJwYWdlVHlwZSI6InByb2R1Y3RfaW5mb3JtYXRpb24iLCJsb2NhbGUiOiJpdF9JVCIsImNvbnRlbnRab25lcyI6WyJnbG9iYWxfUElfTkwiLCJwaV9iYW5uZXJfTkwiLCJlcXMtc3BlY2lhbF9OTCJdLCJ1cmwiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56Lml0L3Bhc3NlbmdlcmNhcnMvbW9kZWxzL2NvdXBlL2NsYS9vdmVydmlldy5odG1sIiwidXJsUmVmZXJyZXIiOiIiLCJjaGFubmVsIjoiV2ViIiwiYmVhY29uVmVyc2lvbiI6MTYsImNvbmZpZ1ZlcnNpb24iOiI2MyJ9LCJmbGFncyI6eyJwYWdlVmlldyI6dHJ1ZX0sInVzZXIiOnsiYXR0cmlidXRlcyI6eyJnYUNsaWVudElEIjoiMzYyODgwNzk0LjE3NDU0NDEyNTkifSwiYW5vbklkIjoiNzE4N2VhMzI3NTY0YTdkNyJ9LCJwZXJmb3JtYW5jZSI6eyJzZGtQYXJzZVRpbWUiOjF9LCJkZWJ1ZyI6eyJleHBsYW5hdGlvbnMiOnRydWV9LCJjYXRhbG9nIjp7IlByb2R1Y3QiOnsiX2lkIjoiMTE4MyIsImRpbWVuc2lvbnMiOnsiQmF1bXVzdGVyU2hvcnQiOlsiMTE4MyJdfX19LCJjb25zZW50cyI6W10sImFjY291bnQiOnt9LCJfdG9vbHNFdmVudExpbmtJZCI6IjA0ODE2NTY1Nzk3NTk3MzM4NiJ9: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x55b9ff754cea <unknown>
#1 0x55b9ff2055f0 <unknown>
#2 0x55b9ff1ebe86 <unknown>
#3 0x55b9ff1ea79a <unknown>
#4 0x55b9ff1eaeff <unknown>
#5 0x55b9ff1eae54 <unknown>
#6 0x55b9ff2097ff <unknown>
#7 0x55b9ff2ae9aa <unknown>
#8 0x55b9ff27c662 <unknown>
#9 0x55b9ff2a2660 <unknown>
#10 0x55b9ff27c433 <unknown>
#11 0x55b9ff248ea3 <unknown>
#12 0x55b9ff249b01 <unknown>
#13 0x55b9ff719b3b <unknown>
#14 0x55b9ff71da21 <unknown>
#15 0x55b9ff700c32 <unknown>
#16 0x55b9ff71e594 <unknown>
#17 0x55b9ff6e4eef <unknown>
#18 0x55b9ff742d98 <unknown>
#19 0x55b9ff742f76 <unknown>
#20 0x55b9ff753b36 <unknown>
#21 0x7fa66b49caa4 <unknown>
#22 0x7fa66b529c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJhY3Rpb24iOiJzZXRfdXNlcl9hdHRyaWJ1dGUiLCJhY2NvdW50Ijp7ImF0dHJpYnV0ZXMiOnsibGFzdFBpUGFnZSI6eyJ2ZWhpY2xlUEkiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56Lml0L3Bhc3NlbmdlcmNhcnMvbW9kZWxzL2NvdXBlL2NsYS9vdmVydmlldy5odG1sIiwidmVoaWNsZUNvZGUiOiJjMTE4LWZsIiwidmVoaWNsZUJNIjoiMTE4MyIsInZlaGljbGVQSUhpc3RvcnkiOiIxMTgzIiwidGltZXN0YW1wIjoxNzQ1NDQxMjYyNDY4LCJleHBpcmF0aW9uIjoxMjB9fX0sInVzZXIiOnsiYXR0cmlidXRlcyI6eyJnYUNsaWVudElEIjoiMzYyODgwNzk0LjE3NDU0NDEyNTkifSwiYW5vbklkIjoiNzE4N2VhMzI3NTY0YTdkNyJ9LCJzb3VyY2UiOnsidXJsIjoiaHR0cHM6Ly93d3cubWVyY2VkZXMtYmVuei5pdC9wYXNzZW5nZXJjYXJzL21vZGVscy9jb3VwZS9jbGEvb3ZlcnZpZXcuaHRtbCIsInVybFJlZmVycmVyIjoiIiwiY2hhbm5lbCI6IldlYiIsImJlYWNvblZlcnNpb24iOjE2LCJjb25maWdWZXJzaW9uIjoiNjMiLCJjb250ZW50Wm9uZXMiOltdfSwiY29uc2VudHMiOltdLCJfdG9vbHNFdmVudExpbmtJZCI6Ijg1MjI4OTU3MzYzMDMzMDgiLCJkZWJ1ZyI6eyJleHBsYW5hdGlvbnMiOnRydWV9fQ%3D%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x55b9ff754cea <unknown>
#1 0x55b9ff2055f0 <unknown>
#2 0x55b9ff1ebe86 <unknown>
#3 0x55b9ff1ea79a <unknown>
#4 0x55b9ff1eaeff <unknown>
#5 0x55b9ff1eae54 <unknown>
#6 0x55b9ff2097ff <unknown>
#7 0x55b9ff2ae9aa <unknown>
#8 0x55b9ff27c662 <unknown>
#9 0x55b9ff2a2660 <unknown>
#10 0x55b9ff27c433 <unknown>
#11 0x55b9ff248ea3 <unknown>
#12 0x55b9ff249b01 <unknown>
#13 0x55b9ff719b3b <unknown>
#14 0x55b9ff71da21 <unknown>
#15 0x55b9ff700c32 <unknown>
#16 0x55b9ff71e594 <unknown>
#17 0x55b9ff6e4eef <unknown>
#18 0x55b9ff742d98 <unknown>
#19 0x55b9ff742f76 <unknown>
#20 0x55b9ff753b36 <unknown>
#21 0x7fa66b49caa4 <unknown>
#22 0x7fa66b529c3c <unknown>

ERROR    root:VerifyPersonalizationAndCapture.py:18 ❌ Error attaching screenshot to Allure: [Errno 2] No such file or directory: '/home/runner/work/QA-App-Allure/QA-App-Allure/Tests/BFV1_attempt_2.png'
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f62521d2450>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/6f0fa90123feca0443ec42fd1c1cdc7a
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f62521d0050>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/6f0fa90123feca0443ec42fd1c1cdc7a
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f62521d05d0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/6f0fa90123feca0443ec42fd1c1cdc7a