ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJpdGVtQWN0aW9uIjoiVmlldyBJdGVtIiwiY2F0YWxvZyI6eyJJdGVtQ2xhc3MiOnsiX2lkIjoib3ZlcnZpZXcifX0sInVzZXIiOnsiYXR0cmlidXRlcyI6eyJnYUNsaWVudElEIjoiMTIwNzM0ODAwNC4xNzQ1NDQ5OTMxIn0sImFub25JZCI6IjI2ZmYzNGI3YTFiZTBkMTAifSwic291cmNlIjp7InVybCI6Imh0dHBzOi8vd3d3Lm1lcmNlZGVzLWJlbnouaXQvcGFzc2VuZ2VyY2Fycy9tb2RlbHMvc2Fsb29uL2VxZS9vdmVydmlldy5odG1sIiwidXJsUmVmZXJyZXIiOiIiLCJjaGFubmVsIjoiV2ViIiwiYmVhY29uVmVyc2lvbiI6MTYsImNvbmZpZ1ZlcnNpb24iOiI2MyIsImNvbnRlbnRab25lcyI6W119LCJjb25zZW50cyI6W10sImFjY291bnQiOnt9LCJfdG9vbHNFdmVudExpbmtJZCI6IjUyNTU2ODQ0MTE5NDg2NTEiLCJkZWJ1ZyI6eyJleHBsYW5hdGlvbnMiOnRydWV9fQ%3D%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x55d3582e2cea <unknown>
#1 0x55d357d935f0 <unknown>
#2 0x55d357d79e86 <unknown>
#3 0x55d357d7879a <unknown>
#4 0x55d357d78eff <unknown>
#5 0x55d357d78e54 <unknown>
#6 0x55d357d977ff <unknown>
#7 0x55d357e3c9aa <unknown>
#8 0x55d357e0a662 <unknown>
#9 0x55d357e30660 <unknown>
#10 0x55d357e0a433 <unknown>
#11 0x55d357dd6ea3 <unknown>
#12 0x55d357dd7b01 <unknown>
#13 0x55d3582a7b3b <unknown>
#14 0x55d3582aba21 <unknown>
#15 0x55d35828ec32 <unknown>
#16 0x55d3582ac594 <unknown>
#17 0x55d358272eef <unknown>
#18 0x55d3582d0d98 <unknown>
#19 0x55d3582d0f76 <unknown>
#20 0x55d3582e1b36 <unknown>
#21 0x7efc0089caa4 <unknown>
#22 0x7efc00929c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJhY3Rpb24iOiJQcm9kdWN0IEluZm9ybWF0aW9uIFBhZ2UgLSBvdmVydmlldyAyOTUxIiwiaXRlbUFjdGlvbiI6IlZpZXcgSXRlbSIsInNvdXJjZSI6eyJwYWdlVHlwZSI6InByb2R1Y3RfaW5mb3JtYXRpb24iLCJsb2NhbGUiOiJpdF9JVCIsImNvbnRlbnRab25lcyI6WyJnbG9iYWxfUElfTkwiLCJwaV9iYW5uZXJfTkwiLCJlcXMtc3BlY2lhbF9OTCJdLCJ1cmwiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56Lml0L3Bhc3NlbmdlcmNhcnMvbW9kZWxzL3NhbG9vbi9lcWUvb3ZlcnZpZXcuaHRtbCIsInVybFJlZmVycmVyIjoiIiwiY2hhbm5lbCI6IldlYiIsImJlYWNvblZlcnNpb24iOjE2LCJjb25maWdWZXJzaW9uIjoiNjMifSwiZmxhZ3MiOnsicGFnZVZpZXciOnRydWV9LCJ1c2VyIjp7ImF0dHJpYnV0ZXMiOnsiZ2FDbGllbnRJRCI6IjEyMDczNDgwMDQuMTc0NTQ0OTkzMSJ9LCJhbm9uSWQiOiIyNmZmMzRiN2ExYmUwZDEwIn0sInBlcmZvcm1hbmNlIjp7InNka1BhcnNlVGltZSI6MX0sImRlYnVnIjp7ImV4cGxhbmF0aW9ucyI6dHJ1ZX0sImNhdGFsb2ciOnsiUHJvZHVjdCI6eyJfaWQiOiIyOTUxIiwiZGltZW5zaW9ucyI6eyJCYXVtdXN0ZXJTaG9ydCI6WyIyOTUxIl19fX0sImNvbnNlbnRzIjpbXSwiYWNjb3VudCI6e30sIl90b29sc0V2ZW50TGlua0lkIjoiOTkwODEzNjEwNjI4MjQwMSJ9: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x55d3582e2cea <unknown>
#1 0x55d357d935f0 <unknown>
#2 0x55d357d79e86 <unknown>
#3 0x55d357d7879a <unknown>
#4 0x55d357d78eff <unknown>
#5 0x55d357d78e54 <unknown>
#6 0x55d357d977ff <unknown>
#7 0x55d357e3c9aa <unknown>
#8 0x55d357e0a662 <unknown>
#9 0x55d357e30660 <unknown>
#10 0x55d357e0a433 <unknown>
#11 0x55d357dd6ea3 <unknown>
#12 0x55d357dd7b01 <unknown>
#13 0x55d3582a7b3b <unknown>
#14 0x55d3582aba21 <unknown>
#15 0x55d35828ec32 <unknown>
#16 0x55d3582ac594 <unknown>
#17 0x55d358272eef <unknown>
#18 0x55d3582d0d98 <unknown>
#19 0x55d3582d0f76 <unknown>
#20 0x55d3582e1b36 <unknown>
#21 0x7efc0089caa4 <unknown>
#22 0x7efc00929c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJhY3Rpb24iOiJWaXNpdGVkIC0gb3ZlcnZpZXciLCJ1c2VyIjp7ImF0dHJpYnV0ZXMiOnsiZ2FDbGllbnRJRCI6IjEyMDczNDgwMDQuMTc0NTQ0OTkzMSJ9LCJhbm9uSWQiOiIyNmZmMzRiN2ExYmUwZDEwIn0sInNvdXJjZSI6eyJ1cmwiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56Lml0L3Bhc3NlbmdlcmNhcnMvbW9kZWxzL3NhbG9vbi9lcWUvb3ZlcnZpZXcuaHRtbCIsInVybFJlZmVycmVyIjoiIiwiY2hhbm5lbCI6IldlYiIsImJlYWNvblZlcnNpb24iOjE2LCJjb25maWdWZXJzaW9uIjoiNjMiLCJjb250ZW50Wm9uZXMiOltdfSwiY29uc2VudHMiOltdLCJhY2NvdW50Ijp7fSwicGVyZm9ybWFuY2UiOnsic2RrUGFyc2VUaW1lIjoxfSwiX3Rvb2xzRXZlbnRMaW5rSWQiOiI5NDE1OTMyOTUzMTI1MDUxIiwiZGVidWciOnsiZXhwbGFuYXRpb25zIjp0cnVlfX0%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x55d3582e2cea <unknown>
#1 0x55d357d935f0 <unknown>
#2 0x55d357d79e86 <unknown>
#3 0x55d357d7879a <unknown>
#4 0x55d357d78eff <unknown>
#5 0x55d357d78e54 <unknown>
#6 0x55d357d977ff <unknown>
#7 0x55d357e3c9aa <unknown>
#8 0x55d357e0a662 <unknown>
#9 0x55d357e30660 <unknown>
#10 0x55d357e0a433 <unknown>
#11 0x55d357dd6ea3 <unknown>
#12 0x55d357dd7b01 <unknown>
#13 0x55d3582a7b3b <unknown>
#14 0x55d3582aba21 <unknown>
#15 0x55d35828ec32 <unknown>
#16 0x55d3582ac594 <unknown>
#17 0x55d358272eef <unknown>
#18 0x55d3582d0d98 <unknown>
#19 0x55d3582d0f76 <unknown>
#20 0x55d3582e1b36 <unknown>
#21 0x7efc0089caa4 <unknown>
#22 0x7efc00929c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJhY3Rpb24iOiJzZXRfdXNlcl9hdHRyaWJ1dGUiLCJhY2NvdW50Ijp7ImF0dHJpYnV0ZXMiOnsibGFzdFBpUGFnZSI6eyJ2ZWhpY2xlUEkiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56Lml0L3Bhc3NlbmdlcmNhcnMvbW9kZWxzL3NhbG9vbi9lcWUvb3ZlcnZpZXcuaHRtbCIsInZlaGljbGVDb2RlIjoidjI5NSIsInZlaGljbGVCTSI6IjI5NTEiLCJ2ZWhpY2xlUElIaXN0b3J5IjoiMjk1MSIsInRpbWVzdGFtcCI6MTc0NTQ0OTkzNzA0NywiZXhwaXJhdGlvbiI6MTIwfX19LCJ1c2VyIjp7ImF0dHJpYnV0ZXMiOnsiZ2FDbGllbnRJRCI6IjEyMDczNDgwMDQuMTc0NTQ0OTkzMSJ9LCJhbm9uSWQiOiIyNmZmMzRiN2ExYmUwZDEwIn0sInNvdXJjZSI6eyJ1cmwiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56Lml0L3Bhc3NlbmdlcmNhcnMvbW9kZWxzL3NhbG9vbi9lcWUvb3ZlcnZpZXcuaHRtbCIsInVybFJlZmVycmVyIjoiIiwiY2hhbm5lbCI6IldlYiIsImJlYWNvblZlcnNpb24iOjE2LCJjb25maWdWZXJzaW9uIjoiNjMiLCJjb250ZW50Wm9uZXMiOltdfSwiY29uc2VudHMiOltdLCJfdG9vbHNFdmVudExpbmtJZCI6Ijg3Mzc1NzAyOTY1NTM4MzMiLCJkZWJ1ZyI6eyJleHBsYW5hdGlvbnMiOnRydWV9fQ%3D%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x55d3582e2cea <unknown>
#1 0x55d357d935f0 <unknown>
#2 0x55d357d79e86 <unknown>
#3 0x55d357d7879a <unknown>
#4 0x55d357d78eff <unknown>
#5 0x55d357d78e54 <unknown>
#6 0x55d357d977ff <unknown>
#7 0x55d357e3c9aa <unknown>
#8 0x55d357e0a662 <unknown>
#9 0x55d357e30660 <unknown>
#10 0x55d357e0a433 <unknown>
#11 0x55d357dd6ea3 <unknown>
#12 0x55d357dd7b01 <unknown>
#13 0x55d3582a7b3b <unknown>
#14 0x55d3582aba21 <unknown>
#15 0x55d35828ec32 <unknown>
#16 0x55d3582ac594 <unknown>
#17 0x55d358272eef <unknown>
#18 0x55d3582d0d98 <unknown>
#19 0x55d3582d0f76 <unknown>
#20 0x55d3582e1b36 <unknown>
#21 0x7efc0089caa4 <unknown>
#22 0x7efc00929c3c <unknown>

ERROR    root:VerifyPersonalizationAndCapture.py:18 ‚ùå Error attaching screenshot to Allure: [Errno 2] No such file or directory: '/home/runner/work/QA-App-Allure/QA-App-Allure/Tests/BFV1_attempt_1.png'