ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJpdGVtQWN0aW9uIjoiVmlldyBJdGVtIiwiY2F0YWxvZyI6eyJJdGVtQ2xhc3MiOnsiX2lkIjoib3ZlcnZpZXcifX0sInNvdXJjZSI6eyJ1cmwiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56Lml0L3Bhc3NlbmdlcmNhcnMvbW9kZWxzL3N1di9nbGMtY291cGUvb3ZlcnZpZXcuaHRtbCIsInVybFJlZmVycmVyIjoiIiwiY2hhbm5lbCI6IldlYiIsImJlYWNvblZlcnNpb24iOjE2LCJjb25maWdWZXJzaW9uIjoiNjMiLCJjb250ZW50Wm9uZXMiOltdfSwidXNlciI6eyJhbm9uSWQiOiIwMzRiZDQ3YjI0ODRkYmNjIn0sImNvbnNlbnRzIjpbXSwiYWNjb3VudCI6e30sIl90b29sc0V2ZW50TGlua0lkIjoiMDE3MDA0NTEwNDQ4MTY3MzEiLCJkZWJ1ZyI6eyJleHBsYW5hdGlvbnMiOnRydWV9fQ%3D%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x55e501250cea <unknown>
#1 0x55e500d015f0 <unknown>
#2 0x55e500ce7e86 <unknown>
#3 0x55e500ce679a <unknown>
#4 0x55e500ce6eff <unknown>
#5 0x55e500ce6e54 <unknown>
#6 0x55e500d057ff <unknown>
#7 0x55e500daa9aa <unknown>
#8 0x55e500d78662 <unknown>
#9 0x55e500d9e660 <unknown>
#10 0x55e500d78433 <unknown>
#11 0x55e500d44ea3 <unknown>
#12 0x55e500d45b01 <unknown>
#13 0x55e501215b3b <unknown>
#14 0x55e501219a21 <unknown>
#15 0x55e5011fcc32 <unknown>
#16 0x55e50121a594 <unknown>
#17 0x55e5011e0eef <unknown>
#18 0x55e50123ed98 <unknown>
#19 0x55e50123ef76 <unknown>
#20 0x55e50124fb36 <unknown>
#21 0x7f648469caa4 <unknown>
#22 0x7f6484729c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJhY3Rpb24iOiJQcm9kdWN0IEluZm9ybWF0aW9uIFBhZ2UgLSBvdmVydmlldyAyNTQzIiwiaXRlbUFjdGlvbiI6IlZpZXcgSXRlbSIsInNvdXJjZSI6eyJwYWdlVHlwZSI6InByb2R1Y3RfaW5mb3JtYXRpb24iLCJsb2NhbGUiOiJpdF9JVCIsImNvbnRlbnRab25lcyI6WyJnbG9iYWxfUElfTkwiLCJwaV9iYW5uZXJfTkwiLCJlcXMtc3BlY2lhbF9OTCJdLCJ1cmwiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56Lml0L3Bhc3NlbmdlcmNhcnMvbW9kZWxzL3N1di9nbGMtY291cGUvb3ZlcnZpZXcuaHRtbCIsInVybFJlZmVycmVyIjoiIiwiY2hhbm5lbCI6IldlYiIsImJlYWNvblZlcnNpb24iOjE2LCJjb25maWdWZXJzaW9uIjoiNjMifSwiZmxhZ3MiOnsicGFnZVZpZXciOnRydWV9LCJ1c2VyIjp7ImFub25JZCI6IjAzNGJkNDdiMjQ4NGRiY2MifSwicGVyZm9ybWFuY2UiOnsic2RrUGFyc2VUaW1lIjoxfSwiZGVidWciOnsiZXhwbGFuYXRpb25zIjp0cnVlfSwiY2F0YWxvZyI6eyJQcm9kdWN0Ijp7Il9pZCI6IjI1NDMiLCJkaW1lbnNpb25zIjp7IkJhdW11c3RlclNob3J0IjpbIjI1NDMiXX19fSwiY29uc2VudHMiOltdLCJhY2NvdW50Ijp7fSwiX3Rvb2xzRXZlbnRMaW5rSWQiOiI5MDU5ODM5MTQyMDkxNTQ5In0%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x55e501250cea <unknown>
#1 0x55e500d015f0 <unknown>
#2 0x55e500ce7e86 <unknown>
#3 0x55e500ce679a <unknown>
#4 0x55e500ce6eff <unknown>
#5 0x55e500ce6e54 <unknown>
#6 0x55e500d057ff <unknown>
#7 0x55e500daa9aa <unknown>
#8 0x55e500d78662 <unknown>
#9 0x55e500d9e660 <unknown>
#10 0x55e500d78433 <unknown>
#11 0x55e500d44ea3 <unknown>
#12 0x55e500d45b01 <unknown>
#13 0x55e501215b3b <unknown>
#14 0x55e501219a21 <unknown>
#15 0x55e5011fcc32 <unknown>
#16 0x55e50121a594 <unknown>
#17 0x55e5011e0eef <unknown>
#18 0x55e50123ed98 <unknown>
#19 0x55e50123ef76 <unknown>
#20 0x55e50124fb36 <unknown>
#21 0x7f648469caa4 <unknown>
#22 0x7f6484729c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJhY3Rpb24iOiJWaXNpdGVkIC0gb3ZlcnZpZXciLCJzb3VyY2UiOnsidXJsIjoiaHR0cHM6Ly93d3cubWVyY2VkZXMtYmVuei5pdC9wYXNzZW5nZXJjYXJzL21vZGVscy9zdXYvZ2xjLWNvdXBlL292ZXJ2aWV3Lmh0bWwiLCJ1cmxSZWZlcnJlciI6IiIsImNoYW5uZWwiOiJXZWIiLCJiZWFjb25WZXJzaW9uIjoxNiwiY29uZmlnVmVyc2lvbiI6IjYzIiwiY29udGVudFpvbmVzIjpbXX0sInVzZXIiOnsiYW5vbklkIjoiMDM0YmQ0N2IyNDg0ZGJjYyJ9LCJjb25zZW50cyI6W10sImFjY291bnQiOnt9LCJwZXJmb3JtYW5jZSI6eyJzZGtQYXJzZVRpbWUiOjF9LCJfdG9vbHNFdmVudExpbmtJZCI6IjE0MTg5NjQ2MDE2MTI0NzkiLCJkZWJ1ZyI6eyJleHBsYW5hdGlvbnMiOnRydWV9fQ%3D%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x55e501250cea <unknown>
#1 0x55e500d015f0 <unknown>
#2 0x55e500ce7e86 <unknown>
#3 0x55e500ce679a <unknown>
#4 0x55e500ce6eff <unknown>
#5 0x55e500ce6e54 <unknown>
#6 0x55e500d057ff <unknown>
#7 0x55e500daa9aa <unknown>
#8 0x55e500d78662 <unknown>
#9 0x55e500d9e660 <unknown>
#10 0x55e500d78433 <unknown>
#11 0x55e500d44ea3 <unknown>
#12 0x55e500d45b01 <unknown>
#13 0x55e501215b3b <unknown>
#14 0x55e501219a21 <unknown>
#15 0x55e5011fcc32 <unknown>
#16 0x55e50121a594 <unknown>
#17 0x55e5011e0eef <unknown>
#18 0x55e50123ed98 <unknown>
#19 0x55e50123ef76 <unknown>
#20 0x55e50124fb36 <unknown>
#21 0x7f648469caa4 <unknown>
#22 0x7f6484729c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJhY3Rpb24iOiJzZXRfdXNlcl9hdHRyaWJ1dGUiLCJhY2NvdW50Ijp7ImF0dHJpYnV0ZXMiOnsibGFzdFBpUGFnZSI6eyJ2ZWhpY2xlUEkiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56Lml0L3Bhc3NlbmdlcmNhcnMvbW9kZWxzL3N1di9nbGMtY291cGUvb3ZlcnZpZXcuaHRtbCIsInZlaGljbGVDb2RlIjoiYzI1NCIsInZlaGljbGVCTSI6IjI1NDMiLCJ2ZWhpY2xlUElIaXN0b3J5IjoiMjU0MyIsInRpbWVzdGFtcCI6MTc0NTQ1MDEzODQwNiwiZXhwaXJhdGlvbiI6MTIwfX19LCJ1c2VyIjp7ImF0dHJpYnV0ZXMiOnsiZ2FDbGllbnRJRCI6IjUxMDIyNjY1OC4xNzQ1NDUwMTM2In0sImFub25JZCI6IjAzNGJkNDdiMjQ4NGRiY2MifSwic291cmNlIjp7InVybCI6Imh0dHBzOi8vd3d3Lm1lcmNlZGVzLWJlbnouaXQvcGFzc2VuZ2VyY2Fycy9tb2RlbHMvc3V2L2dsYy1jb3VwZS9vdmVydmlldy5odG1sIiwidXJsUmVmZXJyZXIiOiIiLCJjaGFubmVsIjoiV2ViIiwiYmVhY29uVmVyc2lvbiI6MTYsImNvbmZpZ1ZlcnNpb24iOiI2MyIsImNvbnRlbnRab25lcyI6W119LCJjb25zZW50cyI6W10sIl90b29sc0V2ZW50TGlua0lkIjoiOTI0MDU0NDY2NTA5NjkyNSIsImRlYnVnIjp7ImV4cGxhbmF0aW9ucyI6dHJ1ZX19: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x55e501250cea <unknown>
#1 0x55e500d015f0 <unknown>
#2 0x55e500ce7e86 <unknown>
#3 0x55e500ce679a <unknown>
#4 0x55e500ce6eff <unknown>
#5 0x55e500ce6e54 <unknown>
#6 0x55e500d057ff <unknown>
#7 0x55e500daa9aa <unknown>
#8 0x55e500d78662 <unknown>
#9 0x55e500d9e660 <unknown>
#10 0x55e500d78433 <unknown>
#11 0x55e500d44ea3 <unknown>
#12 0x55e500d45b01 <unknown>
#13 0x55e501215b3b <unknown>
#14 0x55e501219a21 <unknown>
#15 0x55e5011fcc32 <unknown>
#16 0x55e50121a594 <unknown>
#17 0x55e5011e0eef <unknown>
#18 0x55e50123ed98 <unknown>
#19 0x55e50123ef76 <unknown>
#20 0x55e50124fb36 <unknown>
#21 0x7f648469caa4 <unknown>
#22 0x7f6484729c3c <unknown>

ERROR    root:VerifyPersonalizationAndCapture.py:111 ❌ Image not found in the specified selector. Error: Message: 

ERROR    root:VerifyPersonalizationAndCapture.py:18 ❌ Error attaching screenshot to Allure: [Errno 2] No such file or directory: '/home/runner/work/QA-App-Allure/QA-App-Allure/Tests/BFV1_attempt_1.png'
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d3491e150>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/c23890302be07a83dd9c685795de7133
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d3491cf10>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/c23890302be07a83dd9c685795de7133
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d3491d590>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/c23890302be07a83dd9c685795de7133
ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJhY3Rpb24iOiJWaXNpdGVkIC0gb3ZlcnZpZXciLCJ1c2VyIjp7ImF0dHJpYnV0ZXMiOnsiZ2FDbGllbnRJRCI6IjIwNTE0OTI5OTIuMTc0NTQ1MDE4MCJ9LCJhbm9uSWQiOiIxNWU4Y2Y0NTJkOTdjYTc2In0sInNvdXJjZSI6eyJ1cmwiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56Lml0L3Bhc3NlbmdlcmNhcnMvbW9kZWxzL3N1di9nbGMtY291cGUvb3ZlcnZpZXcuaHRtbCIsInVybFJlZmVycmVyIjoiIiwiY2hhbm5lbCI6IldlYiIsImJlYWNvblZlcnNpb24iOjE2LCJjb25maWdWZXJzaW9uIjoiNjMiLCJjb250ZW50Wm9uZXMiOltdfSwiY29uc2VudHMiOltdLCJhY2NvdW50Ijp7fSwiX3Rvb2xzRXZlbnRMaW5rSWQiOiI3MjUzNzkzNzA0NjM3NzM5IiwiZGVidWciOnsiZXhwbGFuYXRpb25zIjp0cnVlfX0%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x55c31e387cea <unknown>
#1 0x55c31de385f0 <unknown>
#2 0x55c31de1ee86 <unknown>
#3 0x55c31de1d79a <unknown>
#4 0x55c31de1deff <unknown>
#5 0x55c31de1de54 <unknown>
#6 0x55c31de3c7ff <unknown>
#7 0x55c31dee19aa <unknown>
#8 0x55c31deaf662 <unknown>
#9 0x55c31ded5660 <unknown>
#10 0x55c31deaf433 <unknown>
#11 0x55c31de7bea3 <unknown>
#12 0x55c31de7cb01 <unknown>
#13 0x55c31e34cb3b <unknown>
#14 0x55c31e350a21 <unknown>
#15 0x55c31e333c32 <unknown>
#16 0x55c31e351594 <unknown>
#17 0x55c31e317eef <unknown>
#18 0x55c31e375d98 <unknown>
#19 0x55c31e375f76 <unknown>
#20 0x55c31e386b36 <unknown>
#21 0x7f0799e9caa4 <unknown>
#22 0x7f0799f29c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJpdGVtQWN0aW9uIjoiVmlldyBJdGVtIiwiY2F0YWxvZyI6eyJJdGVtQ2xhc3MiOnsiX2lkIjoib3ZlcnZpZXcifX0sInVzZXIiOnsiYXR0cmlidXRlcyI6eyJnYUNsaWVudElEIjoiMjA1MTQ5Mjk5Mi4xNzQ1NDUwMTgwIn0sImFub25JZCI6IjE1ZThjZjQ1MmQ5N2NhNzYifSwic291cmNlIjp7InVybCI6Imh0dHBzOi8vd3d3Lm1lcmNlZGVzLWJlbnouaXQvcGFzc2VuZ2VyY2Fycy9tb2RlbHMvc3V2L2dsYy1jb3VwZS9vdmVydmlldy5odG1sIiwidXJsUmVmZXJyZXIiOiIiLCJjaGFubmVsIjoiV2ViIiwiYmVhY29uVmVyc2lvbiI6MTYsImNvbmZpZ1ZlcnNpb24iOiI2MyIsImNvbnRlbnRab25lcyI6W119LCJjb25zZW50cyI6W10sImFjY291bnQiOnt9LCJwZXJmb3JtYW5jZSI6eyJzZGtQYXJzZVRpbWUiOjF9LCJfdG9vbHNFdmVudExpbmtJZCI6IjQ5Mjg5MzU2ODA3MTA4NzY0IiwiZGVidWciOnsiZXhwbGFuYXRpb25zIjp0cnVlfX0%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x55c31e387cea <unknown>
#1 0x55c31de385f0 <unknown>
#2 0x55c31de1ee86 <unknown>
#3 0x55c31de1d79a <unknown>
#4 0x55c31de1deff <unknown>
#5 0x55c31de1de54 <unknown>
#6 0x55c31de3c7ff <unknown>
#7 0x55c31dee19aa <unknown>
#8 0x55c31deaf662 <unknown>
#9 0x55c31ded5660 <unknown>
#10 0x55c31deaf433 <unknown>
#11 0x55c31de7bea3 <unknown>
#12 0x55c31de7cb01 <unknown>
#13 0x55c31e34cb3b <unknown>
#14 0x55c31e350a21 <unknown>
#15 0x55c31e333c32 <unknown>
#16 0x55c31e351594 <unknown>
#17 0x55c31e317eef <unknown>
#18 0x55c31e375d98 <unknown>
#19 0x55c31e375f76 <unknown>
#20 0x55c31e386b36 <unknown>
#21 0x7f0799e9caa4 <unknown>
#22 0x7f0799f29c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJhY3Rpb24iOiJQcm9kdWN0IEluZm9ybWF0aW9uIFBhZ2UgLSBvdmVydmlldyAyNTQzIiwiaXRlbUFjdGlvbiI6IlZpZXcgSXRlbSIsInNvdXJjZSI6eyJwYWdlVHlwZSI6InByb2R1Y3RfaW5mb3JtYXRpb24iLCJsb2NhbGUiOiJpdF9JVCIsImNvbnRlbnRab25lcyI6WyJnbG9iYWxfUElfTkwiLCJwaV9iYW5uZXJfTkwiLCJlcXMtc3BlY2lhbF9OTCJdLCJ1cmwiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56Lml0L3Bhc3NlbmdlcmNhcnMvbW9kZWxzL3N1di9nbGMtY291cGUvb3ZlcnZpZXcuaHRtbCIsInVybFJlZmVycmVyIjoiIiwiY2hhbm5lbCI6IldlYiIsImJlYWNvblZlcnNpb24iOjE2LCJjb25maWdWZXJzaW9uIjoiNjMifSwiZmxhZ3MiOnsicGFnZVZpZXciOnRydWV9LCJ1c2VyIjp7ImF0dHJpYnV0ZXMiOnsiZ2FDbGllbnRJRCI6IjIwNTE0OTI5OTIuMTc0NTQ1MDE4MCJ9LCJhbm9uSWQiOiIxNWU4Y2Y0NTJkOTdjYTc2In0sInBlcmZvcm1hbmNlIjp7InNka1BhcnNlVGltZSI6MX0sImRlYnVnIjp7ImV4cGxhbmF0aW9ucyI6dHJ1ZX0sImNhdGFsb2ciOnsiUHJvZHVjdCI6eyJfaWQiOiIyNTQzIiwiZGltZW5zaW9ucyI6eyJCYXVtdXN0ZXJTaG9ydCI6WyIyNTQzIl19fX0sImNvbnNlbnRzIjpbXSwiYWNjb3VudCI6e30sIl90b29sc0V2ZW50TGlua0lkIjoiMTcxMDEwMzM1Nzg4NDczMjQifQ%3D%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x55c31e387cea <unknown>
#1 0x55c31de385f0 <unknown>
#2 0x55c31de1ee86 <unknown>
#3 0x55c31de1d79a <unknown>
#4 0x55c31de1deff <unknown>
#5 0x55c31de1de54 <unknown>
#6 0x55c31de3c7ff <unknown>
#7 0x55c31dee19aa <unknown>
#8 0x55c31deaf662 <unknown>
#9 0x55c31ded5660 <unknown>
#10 0x55c31deaf433 <unknown>
#11 0x55c31de7bea3 <unknown>
#12 0x55c31de7cb01 <unknown>
#13 0x55c31e34cb3b <unknown>
#14 0x55c31e350a21 <unknown>
#15 0x55c31e333c32 <unknown>
#16 0x55c31e351594 <unknown>
#17 0x55c31e317eef <unknown>
#18 0x55c31e375d98 <unknown>
#19 0x55c31e375f76 <unknown>
#20 0x55c31e386b36 <unknown>
#21 0x7f0799e9caa4 <unknown>
#22 0x7f0799f29c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJhY3Rpb24iOiJzZXRfdXNlcl9hdHRyaWJ1dGUiLCJhY2NvdW50Ijp7ImF0dHJpYnV0ZXMiOnsibGFzdFBpUGFnZSI6eyJ2ZWhpY2xlUEkiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56Lml0L3Bhc3NlbmdlcmNhcnMvbW9kZWxzL3N1di9nbGMtY291cGUvb3ZlcnZpZXcuaHRtbCIsInZlaGljbGVDb2RlIjoiYzI1NCIsInZlaGljbGVCTSI6IjI1NDMiLCJ2ZWhpY2xlUElIaXN0b3J5IjoiMjU0MyIsInRpbWVzdGFtcCI6MTc0NTQ1MDE4NzU5NywiZXhwaXJhdGlvbiI6MTIwfX19LCJ1c2VyIjp7ImF0dHJpYnV0ZXMiOnsiZ2FDbGllbnRJRCI6IjIwNTE0OTI5OTIuMTc0NTQ1MDE4MCJ9LCJhbm9uSWQiOiIxNWU4Y2Y0NTJkOTdjYTc2In0sInNvdXJjZSI6eyJ1cmwiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56Lml0L3Bhc3NlbmdlcmNhcnMvbW9kZWxzL3N1di9nbGMtY291cGUvb3ZlcnZpZXcuaHRtbCIsInVybFJlZmVycmVyIjoiIiwiY2hhbm5lbCI6IldlYiIsImJlYWNvblZlcnNpb24iOjE2LCJjb25maWdWZXJzaW9uIjoiNjMiLCJjb250ZW50Wm9uZXMiOltdfSwiY29uc2VudHMiOltdLCJfdG9vbHNFdmVudExpbmtJZCI6IjYzMTAwOTgzNDI1MzIyMjEiLCJkZWJ1ZyI6eyJleHBsYW5hdGlvbnMiOnRydWV9fQ%3D%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x55c31e387cea <unknown>
#1 0x55c31de385f0 <unknown>
#2 0x55c31de1ee86 <unknown>
#3 0x55c31de1d79a <unknown>
#4 0x55c31de1deff <unknown>
#5 0x55c31de1de54 <unknown>
#6 0x55c31de3c7ff <unknown>
#7 0x55c31dee19aa <unknown>
#8 0x55c31deaf662 <unknown>
#9 0x55c31ded5660 <unknown>
#10 0x55c31deaf433 <unknown>
#11 0x55c31de7bea3 <unknown>
#12 0x55c31de7cb01 <unknown>
#13 0x55c31e34cb3b <unknown>
#14 0x55c31e350a21 <unknown>
#15 0x55c31e333c32 <unknown>
#16 0x55c31e351594 <unknown>
#17 0x55c31e317eef <unknown>
#18 0x55c31e375d98 <unknown>
#19 0x55c31e375f76 <unknown>
#20 0x55c31e386b36 <unknown>
#21 0x7f0799e9caa4 <unknown>
#22 0x7f0799f29c3c <unknown>

ERROR    root:VerifyPersonalizationAndCapture.py:18 ❌ Error attaching screenshot to Allure: [Errno 2] No such file or directory: '/home/runner/work/QA-App-Allure/QA-App-Allure/Tests/BFV1_attempt_2.png'
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d34903890>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/c23890302be07a83dd9c685795de7133
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d34900510>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/c23890302be07a83dd9c685795de7133
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d34900950>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/c23890302be07a83dd9c685795de7133