ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJhY3Rpb24iOiJWaXNpdGVkIC0gb3ZlcnZpZXciLCJzb3VyY2UiOnsidXJsIjoiaHR0cHM6Ly93d3cubWVyY2VkZXMtYmVuei5pdC9wYXNzZW5nZXJjYXJzL21vZGVscy9zdXYvZ2xlLWNvdXBlL292ZXJ2aWV3Lmh0bWwiLCJ1cmxSZWZlcnJlciI6IiIsImNoYW5uZWwiOiJXZWIiLCJiZWFjb25WZXJzaW9uIjoxNiwiY29uZmlnVmVyc2lvbiI6IjYzIiwiY29udGVudFpvbmVzIjpbXX0sInVzZXIiOnsiYW5vbklkIjoiNjM2M2U2OWZjOTMzMTkzMiJ9LCJjb25zZW50cyI6W10sImFjY291bnQiOnt9LCJfdG9vbHNFdmVudExpbmtJZCI6IjQxNDI1OTU1NDE3MTQ0NSIsImRlYnVnIjp7ImV4cGxhbmF0aW9ucyI6dHJ1ZX19: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x556183484cea <unknown>
#1 0x556182f355f0 <unknown>
#2 0x556182f1be86 <unknown>
#3 0x556182f1a79a <unknown>
#4 0x556182f1aeff <unknown>
#5 0x556182f1ae54 <unknown>
#6 0x556182f397ff <unknown>
#7 0x556182fde9aa <unknown>
#8 0x556182fac662 <unknown>
#9 0x556182fd2660 <unknown>
#10 0x556182fac433 <unknown>
#11 0x556182f78ea3 <unknown>
#12 0x556182f79b01 <unknown>
#13 0x556183449b3b <unknown>
#14 0x55618344da21 <unknown>
#15 0x556183430c32 <unknown>
#16 0x55618344e594 <unknown>
#17 0x556183414eef <unknown>
#18 0x556183472d98 <unknown>
#19 0x556183472f76 <unknown>
#20 0x556183483b36 <unknown>
#21 0x7fbea829caa4 <unknown>
#22 0x7fbea8329c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJpdGVtQWN0aW9uIjoiVmlldyBJdGVtIiwiY2F0YWxvZyI6eyJJdGVtQ2xhc3MiOnsiX2lkIjoib3ZlcnZpZXcifX0sInNvdXJjZSI6eyJ1cmwiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56Lml0L3Bhc3NlbmdlcmNhcnMvbW9kZWxzL3N1di9nbGUtY291cGUvb3ZlcnZpZXcuaHRtbCIsInVybFJlZmVycmVyIjoiIiwiY2hhbm5lbCI6IldlYiIsImJlYWNvblZlcnNpb24iOjE2LCJjb25maWdWZXJzaW9uIjoiNjMiLCJjb250ZW50Wm9uZXMiOltdfSwidXNlciI6eyJhbm9uSWQiOiI2MzYzZTY5ZmM5MzMxOTMyIn0sImNvbnNlbnRzIjpbXSwiYWNjb3VudCI6e30sIl90b29sc0V2ZW50TGlua0lkIjoiNjAwNDU3MjYxMjQyMzYwNyIsImRlYnVnIjp7ImV4cGxhbmF0aW9ucyI6dHJ1ZX19: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x556183484cea <unknown>
#1 0x556182f355f0 <unknown>
#2 0x556182f1be86 <unknown>
#3 0x556182f1a79a <unknown>
#4 0x556182f1aeff <unknown>
#5 0x556182f1ae54 <unknown>
#6 0x556182f397ff <unknown>
#7 0x556182fde9aa <unknown>
#8 0x556182fac662 <unknown>
#9 0x556182fd2660 <unknown>
#10 0x556182fac433 <unknown>
#11 0x556182f78ea3 <unknown>
#12 0x556182f79b01 <unknown>
#13 0x556183449b3b <unknown>
#14 0x55618344da21 <unknown>
#15 0x556183430c32 <unknown>
#16 0x55618344e594 <unknown>
#17 0x556183414eef <unknown>
#18 0x556183472d98 <unknown>
#19 0x556183472f76 <unknown>
#20 0x556183483b36 <unknown>
#21 0x7fbea829caa4 <unknown>
#22 0x7fbea8329c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJhY3Rpb24iOiJQcm9kdWN0IEluZm9ybWF0aW9uIFBhZ2UgLSBvdmVydmlldyAxNjczIiwiaXRlbUFjdGlvbiI6IlZpZXcgSXRlbSIsInNvdXJjZSI6eyJwYWdlVHlwZSI6InByb2R1Y3RfaW5mb3JtYXRpb24iLCJsb2NhbGUiOiJpdF9JVCIsImNvbnRlbnRab25lcyI6WyJnbG9iYWxfUElfTkwiLCJwaV9iYW5uZXJfTkwiLCJlcXMtc3BlY2lhbF9OTCJdLCJ1cmwiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56Lml0L3Bhc3NlbmdlcmNhcnMvbW9kZWxzL3N1di9nbGUtY291cGUvb3ZlcnZpZXcuaHRtbCIsInVybFJlZmVycmVyIjoiIiwiY2hhbm5lbCI6IldlYiIsImJlYWNvblZlcnNpb24iOjE2LCJjb25maWdWZXJzaW9uIjoiNjMifSwiZmxhZ3MiOnsicGFnZVZpZXciOnRydWV9LCJ1c2VyIjp7ImFub25JZCI6IjYzNjNlNjlmYzkzMzE5MzIifSwicGVyZm9ybWFuY2UiOnt9LCJkZWJ1ZyI6eyJleHBsYW5hdGlvbnMiOnRydWV9LCJjYXRhbG9nIjp7IlByb2R1Y3QiOnsiX2lkIjoiMTY3MyIsImRpbWVuc2lvbnMiOnsiQmF1bXVzdGVyU2hvcnQiOlsiMTY3MyJdfX19LCJjb25zZW50cyI6W10sImFjY291bnQiOnt9LCJfdG9vbHNFdmVudExpbmtJZCI6Ijg1ODYyNTU1MDAzNzQ2MjgifQ%3D%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x556183484cea <unknown>
#1 0x556182f355f0 <unknown>
#2 0x556182f1be86 <unknown>
#3 0x556182f1a79a <unknown>
#4 0x556182f1aeff <unknown>
#5 0x556182f1ae54 <unknown>
#6 0x556182f397ff <unknown>
#7 0x556182fde9aa <unknown>
#8 0x556182fac662 <unknown>
#9 0x556182fd2660 <unknown>
#10 0x556182fac433 <unknown>
#11 0x556182f78ea3 <unknown>
#12 0x556182f79b01 <unknown>
#13 0x556183449b3b <unknown>
#14 0x55618344da21 <unknown>
#15 0x556183430c32 <unknown>
#16 0x55618344e594 <unknown>
#17 0x556183414eef <unknown>
#18 0x556183472d98 <unknown>
#19 0x556183472f76 <unknown>
#20 0x556183483b36 <unknown>
#21 0x7fbea829caa4 <unknown>
#22 0x7fbea8329c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJhY3Rpb24iOiJzZXRfdXNlcl9hdHRyaWJ1dGUiLCJhY2NvdW50Ijp7ImF0dHJpYnV0ZXMiOnsibGFzdFBpUGFnZSI6eyJ2ZWhpY2xlUEkiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56Lml0L3Bhc3NlbmdlcmNhcnMvbW9kZWxzL3N1di9nbGUtY291cGUvb3ZlcnZpZXcuaHRtbCIsInZlaGljbGVDb2RlIjoiYzE2Ny1mbCIsInZlaGljbGVCTSI6IjE2NzMiLCJ2ZWhpY2xlUElIaXN0b3J5IjoiMTY3MyIsInRpbWVzdGFtcCI6MTc0NTQzOTM4MDY0MSwiZXhwaXJhdGlvbiI6MTIwfX19LCJ1c2VyIjp7ImF0dHJpYnV0ZXMiOnsiZ2FDbGllbnRJRCI6IjU4NzY0OTgxNS4xNzQ1NDM5Mzc4In0sImFub25JZCI6IjYzNjNlNjlmYzkzMzE5MzIifSwic291cmNlIjp7InVybCI6Imh0dHBzOi8vd3d3Lm1lcmNlZGVzLWJlbnouaXQvcGFzc2VuZ2VyY2Fycy9tb2RlbHMvc3V2L2dsZS1jb3VwZS9vdmVydmlldy5odG1sIiwidXJsUmVmZXJyZXIiOiIiLCJjaGFubmVsIjoiV2ViIiwiYmVhY29uVmVyc2lvbiI6MTYsImNvbmZpZ1ZlcnNpb24iOiI2MyIsImNvbnRlbnRab25lcyI6W119LCJjb25zZW50cyI6W10sIl90b29sc0V2ZW50TGlua0lkIjoiMTM0NzI3MTI2Njk5MTQ1MjIiLCJkZWJ1ZyI6eyJleHBsYW5hdGlvbnMiOnRydWV9fQ%3D%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x556183484cea <unknown>
#1 0x556182f355f0 <unknown>
#2 0x556182f1be86 <unknown>
#3 0x556182f1a79a <unknown>
#4 0x556182f1aeff <unknown>
#5 0x556182f1ae54 <unknown>
#6 0x556182f397ff <unknown>
#7 0x556182fde9aa <unknown>
#8 0x556182fac662 <unknown>
#9 0x556182fd2660 <unknown>
#10 0x556182fac433 <unknown>
#11 0x556182f78ea3 <unknown>
#12 0x556182f79b01 <unknown>
#13 0x556183449b3b <unknown>
#14 0x55618344da21 <unknown>
#15 0x556183430c32 <unknown>
#16 0x55618344e594 <unknown>
#17 0x556183414eef <unknown>
#18 0x556183472d98 <unknown>
#19 0x556183472f76 <unknown>
#20 0x556183483b36 <unknown>
#21 0x7fbea829caa4 <unknown>
#22 0x7fbea8329c3c <unknown>

ERROR    root:VerifyPersonalizationAndCapture.py:18 ‚ùå Error attaching screenshot to Allure: [Errno 2] No such file or directory: '/home/runner/work/QA-App-Allure/QA-App-Allure/Tests/BFV1_attempt_1.png'