ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJpdGVtQWN0aW9uIjoiVmlldyBJdGVtIiwiY2F0YWxvZyI6eyJJdGVtQ2xhc3MiOnsiX2lkIjoib3ZlcnZpZXcifX0sInVzZXIiOnsiYXR0cmlidXRlcyI6eyJnYUNsaWVudElEIjoiMTE1Mjc1MTY3NS4xNzQ1NDUwMDk1In0sImFub25JZCI6IjM0ZjhiOGNmMGYzYjVmN2MifSwic291cmNlIjp7InVybCI6Imh0dHBzOi8vd3d3Lm1lcmNlZGVzLWJlbnouaXQvcGFzc2VuZ2VyY2Fycy9tb2RlbHMvc3V2L2dsYy9vdmVydmlldy5odG1sIiwidXJsUmVmZXJyZXIiOiIiLCJjaGFubmVsIjoiV2ViIiwiYmVhY29uVmVyc2lvbiI6MTYsImNvbmZpZ1ZlcnNpb24iOiI2MyIsImNvbnRlbnRab25lcyI6W119LCJjb25zZW50cyI6W10sImFjY291bnQiOnt9LCJfdG9vbHNFdmVudExpbmtJZCI6Ijg2MDU2NzgzNzQwMzkwMDEiLCJkZWJ1ZyI6eyJleHBsYW5hdGlvbnMiOnRydWV9fQ%3D%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x55f78cc89cea <unknown>
#1 0x55f78c73a5f0 <unknown>
#2 0x55f78c720e86 <unknown>
#3 0x55f78c71f79a <unknown>
#4 0x55f78c71feff <unknown>
#5 0x55f78c71fe54 <unknown>
#6 0x55f78c73e7ff <unknown>
#7 0x55f78c7e39aa <unknown>
#8 0x55f78c7b1662 <unknown>
#9 0x55f78c7d7660 <unknown>
#10 0x55f78c7b1433 <unknown>
#11 0x55f78c77dea3 <unknown>
#12 0x55f78c77eb01 <unknown>
#13 0x55f78cc4eb3b <unknown>
#14 0x55f78cc52a21 <unknown>
#15 0x55f78cc35c32 <unknown>
#16 0x55f78cc53594 <unknown>
#17 0x55f78cc19eef <unknown>
#18 0x55f78cc77d98 <unknown>
#19 0x55f78cc77f76 <unknown>
#20 0x55f78cc88b36 <unknown>
#21 0x7f488d09caa4 <unknown>
#22 0x7f488d129c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJhY3Rpb24iOiJWaXNpdGVkIC0gb3ZlcnZpZXciLCJ1c2VyIjp7ImF0dHJpYnV0ZXMiOnsiZ2FDbGllbnRJRCI6IjExNTI3NTE2NzUuMTc0NTQ1MDA5NSJ9LCJhbm9uSWQiOiIzNGY4YjhjZjBmM2I1ZjdjIn0sInNvdXJjZSI6eyJ1cmwiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56Lml0L3Bhc3NlbmdlcmNhcnMvbW9kZWxzL3N1di9nbGMvb3ZlcnZpZXcuaHRtbCIsInVybFJlZmVycmVyIjoiIiwiY2hhbm5lbCI6IldlYiIsImJlYWNvblZlcnNpb24iOjE2LCJjb25maWdWZXJzaW9uIjoiNjMiLCJjb250ZW50Wm9uZXMiOltdfSwiY29uc2VudHMiOltdLCJhY2NvdW50Ijp7fSwicGVyZm9ybWFuY2UiOnsic2RrUGFyc2VUaW1lIjoyfSwiX3Rvb2xzRXZlbnRMaW5rSWQiOiI2OTkwMTEyMjg1NDk4MDUiLCJkZWJ1ZyI6eyJleHBsYW5hdGlvbnMiOnRydWV9fQ%3D%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x55f78cc89cea <unknown>
#1 0x55f78c73a5f0 <unknown>
#2 0x55f78c720e86 <unknown>
#3 0x55f78c71f79a <unknown>
#4 0x55f78c71feff <unknown>
#5 0x55f78c71fe54 <unknown>
#6 0x55f78c73e7ff <unknown>
#7 0x55f78c7e39aa <unknown>
#8 0x55f78c7b1662 <unknown>
#9 0x55f78c7d7660 <unknown>
#10 0x55f78c7b1433 <unknown>
#11 0x55f78c77dea3 <unknown>
#12 0x55f78c77eb01 <unknown>
#13 0x55f78cc4eb3b <unknown>
#14 0x55f78cc52a21 <unknown>
#15 0x55f78cc35c32 <unknown>
#16 0x55f78cc53594 <unknown>
#17 0x55f78cc19eef <unknown>
#18 0x55f78cc77d98 <unknown>
#19 0x55f78cc77f76 <unknown>
#20 0x55f78cc88b36 <unknown>
#21 0x7f488d09caa4 <unknown>
#22 0x7f488d129c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJhY3Rpb24iOiJQcm9kdWN0IEluZm9ybWF0aW9uIFBhZ2UgLSBvdmVydmlldyAyNTQ2IiwiaXRlbUFjdGlvbiI6IlZpZXcgSXRlbSIsInNvdXJjZSI6eyJwYWdlVHlwZSI6InByb2R1Y3RfaW5mb3JtYXRpb24iLCJsb2NhbGUiOiJpdF9JVCIsImNvbnRlbnRab25lcyI6WyJnbG9iYWxfUElfTkwiLCJwaV9iYW5uZXJfTkwiLCJlcXMtc3BlY2lhbF9OTCJdLCJ1cmwiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56Lml0L3Bhc3NlbmdlcmNhcnMvbW9kZWxzL3N1di9nbGMvb3ZlcnZpZXcuaHRtbCIsInVybFJlZmVycmVyIjoiIiwiY2hhbm5lbCI6IldlYiIsImJlYWNvblZlcnNpb24iOjE2LCJjb25maWdWZXJzaW9uIjoiNjMifSwiZmxhZ3MiOnsicGFnZVZpZXciOnRydWV9LCJ1c2VyIjp7ImF0dHJpYnV0ZXMiOnsiZ2FDbGllbnRJRCI6IjExNTI3NTE2NzUuMTc0NTQ1MDA5NSJ9LCJhbm9uSWQiOiIzNGY4YjhjZjBmM2I1ZjdjIn0sInBlcmZvcm1hbmNlIjp7InNka1BhcnNlVGltZSI6Mn0sImRlYnVnIjp7ImV4cGxhbmF0aW9ucyI6dHJ1ZX0sImNhdGFsb2ciOnsiUHJvZHVjdCI6eyJfaWQiOiIyNTQ2IiwiZGltZW5zaW9ucyI6eyJCYXVtdXN0ZXJTaG9ydCI6WyIyNTQ2Il19fX0sImNvbnNlbnRzIjpbXSwiYWNjb3VudCI6e30sIl90b29sc0V2ZW50TGlua0lkIjoiODY5NjAxOTk1NTI0OTY1NiJ9: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x55f78cc89cea <unknown>
#1 0x55f78c73a5f0 <unknown>
#2 0x55f78c720e86 <unknown>
#3 0x55f78c71f79a <unknown>
#4 0x55f78c71feff <unknown>
#5 0x55f78c71fe54 <unknown>
#6 0x55f78c73e7ff <unknown>
#7 0x55f78c7e39aa <unknown>
#8 0x55f78c7b1662 <unknown>
#9 0x55f78c7d7660 <unknown>
#10 0x55f78c7b1433 <unknown>
#11 0x55f78c77dea3 <unknown>
#12 0x55f78c77eb01 <unknown>
#13 0x55f78cc4eb3b <unknown>
#14 0x55f78cc52a21 <unknown>
#15 0x55f78cc35c32 <unknown>
#16 0x55f78cc53594 <unknown>
#17 0x55f78cc19eef <unknown>
#18 0x55f78cc77d98 <unknown>
#19 0x55f78cc77f76 <unknown>
#20 0x55f78cc88b36 <unknown>
#21 0x7f488d09caa4 <unknown>
#22 0x7f488d129c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJhY3Rpb24iOiJzZXRfdXNlcl9hdHRyaWJ1dGUiLCJhY2NvdW50Ijp7ImF0dHJpYnV0ZXMiOnsibGFzdFBpUGFnZSI6eyJ2ZWhpY2xlUEkiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56Lml0L3Bhc3NlbmdlcmNhcnMvbW9kZWxzL3N1di9nbGMvb3ZlcnZpZXcuaHRtbCIsInZlaGljbGVDb2RlIjoieDI1NCIsInZlaGljbGVCTSI6IjI1NDYiLCJ2ZWhpY2xlUElIaXN0b3J5IjoiMjU0NiIsInRpbWVzdGFtcCI6MTc0NTQ1MDEwMjgyNiwiZXhwaXJhdGlvbiI6MTIwfX19LCJ1c2VyIjp7ImF0dHJpYnV0ZXMiOnsiZ2FDbGllbnRJRCI6IjExNTI3NTE2NzUuMTc0NTQ1MDA5NSJ9LCJhbm9uSWQiOiIzNGY4YjhjZjBmM2I1ZjdjIn0sInNvdXJjZSI6eyJ1cmwiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56Lml0L3Bhc3NlbmdlcmNhcnMvbW9kZWxzL3N1di9nbGMvb3ZlcnZpZXcuaHRtbCIsInVybFJlZmVycmVyIjoiIiwiY2hhbm5lbCI6IldlYiIsImJlYWNvblZlcnNpb24iOjE2LCJjb25maWdWZXJzaW9uIjoiNjMiLCJjb250ZW50Wm9uZXMiOltdfSwiY29uc2VudHMiOltdLCJfdG9vbHNFdmVudExpbmtJZCI6IjI5NDYwMzAxMjI5MTUxMTEiLCJkZWJ1ZyI6eyJleHBsYW5hdGlvbnMiOnRydWV9fQ%3D%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x55f78cc89cea <unknown>
#1 0x55f78c73a5f0 <unknown>
#2 0x55f78c720e86 <unknown>
#3 0x55f78c71f79a <unknown>
#4 0x55f78c71feff <unknown>
#5 0x55f78c71fe54 <unknown>
#6 0x55f78c73e7ff <unknown>
#7 0x55f78c7e39aa <unknown>
#8 0x55f78c7b1662 <unknown>
#9 0x55f78c7d7660 <unknown>
#10 0x55f78c7b1433 <unknown>
#11 0x55f78c77dea3 <unknown>
#12 0x55f78c77eb01 <unknown>
#13 0x55f78cc4eb3b <unknown>
#14 0x55f78cc52a21 <unknown>
#15 0x55f78cc35c32 <unknown>
#16 0x55f78cc53594 <unknown>
#17 0x55f78cc19eef <unknown>
#18 0x55f78cc77d98 <unknown>
#19 0x55f78cc77f76 <unknown>
#20 0x55f78cc88b36 <unknown>
#21 0x7f488d09caa4 <unknown>
#22 0x7f488d129c3c <unknown>

ERROR    root:VerifyPersonalizationAndCapture.py:18 ‚ùå Error attaching screenshot to Allure: [Errno 2] No such file or directory: '/home/runner/work/QA-App-Allure/QA-App-Allure/Tests/BFV1_attempt_1.png'