ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJpdGVtQWN0aW9uIjoiVmlldyBJdGVtIiwiY2F0YWxvZyI6eyJJdGVtQ2xhc3MiOnsiX2lkIjoib3ZlcnZpZXcifX0sInVzZXIiOnsiYXR0cmlidXRlcyI6eyJnYUNsaWVudElEIjoiMTc0ODkyMTgwNy4xNzQ1NDQwOTQ0In0sImFub25JZCI6IjlmY2FiNDUxZmY5YjY5N2YifSwic291cmNlIjp7InVybCI6Imh0dHBzOi8vd3d3Lm1lcmNlZGVzLWJlbnouaXQvcGFzc2VuZ2VyY2Fycy9tb2RlbHMvc3V2L2dsYy9vdmVydmlldy5odG1sIiwidXJsUmVmZXJyZXIiOiIiLCJjaGFubmVsIjoiV2ViIiwiYmVhY29uVmVyc2lvbiI6MTYsImNvbmZpZ1ZlcnNpb24iOiI2MyIsImNvbnRlbnRab25lcyI6W119LCJjb25zZW50cyI6W10sImFjY291bnQiOnt9LCJfdG9vbHNFdmVudExpbmtJZCI6IjcyODE0MDE0Njk2NTAwMjciLCJkZWJ1ZyI6eyJleHBsYW5hdGlvbnMiOnRydWV9fQ%3D%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x5584a9d0dcea <unknown>
#1 0x5584a97be5f0 <unknown>
#2 0x5584a97a4e86 <unknown>
#3 0x5584a97a379a <unknown>
#4 0x5584a97a3eff <unknown>
#5 0x5584a97a3e54 <unknown>
#6 0x5584a97c27ff <unknown>
#7 0x5584a98679aa <unknown>
#8 0x5584a9835662 <unknown>
#9 0x5584a985b660 <unknown>
#10 0x5584a9835433 <unknown>
#11 0x5584a9801ea3 <unknown>
#12 0x5584a9802b01 <unknown>
#13 0x5584a9cd2b3b <unknown>
#14 0x5584a9cd6a21 <unknown>
#15 0x5584a9cb9c32 <unknown>
#16 0x5584a9cd7594 <unknown>
#17 0x5584a9c9deef <unknown>
#18 0x5584a9cfbd98 <unknown>
#19 0x5584a9cfbf76 <unknown>
#20 0x5584a9d0cb36 <unknown>
#21 0x7f078749caa4 <unknown>
#22 0x7f0787529c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJhY3Rpb24iOiJQcm9kdWN0IEluZm9ybWF0aW9uIFBhZ2UgLSBvdmVydmlldyAyNTQ2IiwiaXRlbUFjdGlvbiI6IlZpZXcgSXRlbSIsInNvdXJjZSI6eyJwYWdlVHlwZSI6InByb2R1Y3RfaW5mb3JtYXRpb24iLCJsb2NhbGUiOiJpdF9JVCIsImNvbnRlbnRab25lcyI6WyJnbG9iYWxfUElfTkwiLCJwaV9iYW5uZXJfTkwiLCJlcXMtc3BlY2lhbF9OTCJdLCJ1cmwiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56Lml0L3Bhc3NlbmdlcmNhcnMvbW9kZWxzL3N1di9nbGMvb3ZlcnZpZXcuaHRtbCIsInVybFJlZmVycmVyIjoiIiwiY2hhbm5lbCI6IldlYiIsImJlYWNvblZlcnNpb24iOjE2LCJjb25maWdWZXJzaW9uIjoiNjMifSwiZmxhZ3MiOnsicGFnZVZpZXciOnRydWV9LCJ1c2VyIjp7ImF0dHJpYnV0ZXMiOnsiZ2FDbGllbnRJRCI6IjE3NDg5MjE4MDcuMTc0NTQ0MDk0NCJ9LCJhbm9uSWQiOiI5ZmNhYjQ1MWZmOWI2OTdmIn0sInBlcmZvcm1hbmNlIjp7InNka1BhcnNlVGltZSI6MX0sImRlYnVnIjp7ImV4cGxhbmF0aW9ucyI6dHJ1ZX0sImNhdGFsb2ciOnsiUHJvZHVjdCI6eyJfaWQiOiIyNTQ2IiwiZGltZW5zaW9ucyI6eyJCYXVtdXN0ZXJTaG9ydCI6WyIyNTQ2Il19fX0sImNvbnNlbnRzIjpbXSwiYWNjb3VudCI6e30sIl90b29sc0V2ZW50TGlua0lkIjoiOTUxNDczNzYxOTA3OTg4In0%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x5584a9d0dcea <unknown>
#1 0x5584a97be5f0 <unknown>
#2 0x5584a97a4e86 <unknown>
#3 0x5584a97a379a <unknown>
#4 0x5584a97a3eff <unknown>
#5 0x5584a97a3e54 <unknown>
#6 0x5584a97c27ff <unknown>
#7 0x5584a98679aa <unknown>
#8 0x5584a9835662 <unknown>
#9 0x5584a985b660 <unknown>
#10 0x5584a9835433 <unknown>
#11 0x5584a9801ea3 <unknown>
#12 0x5584a9802b01 <unknown>
#13 0x5584a9cd2b3b <unknown>
#14 0x5584a9cd6a21 <unknown>
#15 0x5584a9cb9c32 <unknown>
#16 0x5584a9cd7594 <unknown>
#17 0x5584a9c9deef <unknown>
#18 0x5584a9cfbd98 <unknown>
#19 0x5584a9cfbf76 <unknown>
#20 0x5584a9d0cb36 <unknown>
#21 0x7f078749caa4 <unknown>
#22 0x7f0787529c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJhY3Rpb24iOiJWaXNpdGVkIC0gb3ZlcnZpZXciLCJ1c2VyIjp7ImF0dHJpYnV0ZXMiOnsiZ2FDbGllbnRJRCI6IjE3NDg5MjE4MDcuMTc0NTQ0MDk0NCJ9LCJhbm9uSWQiOiI5ZmNhYjQ1MWZmOWI2OTdmIn0sInNvdXJjZSI6eyJ1cmwiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56Lml0L3Bhc3NlbmdlcmNhcnMvbW9kZWxzL3N1di9nbGMvb3ZlcnZpZXcuaHRtbCIsInVybFJlZmVycmVyIjoiIiwiY2hhbm5lbCI6IldlYiIsImJlYWNvblZlcnNpb24iOjE2LCJjb25maWdWZXJzaW9uIjoiNjMiLCJjb250ZW50Wm9uZXMiOltdfSwiY29uc2VudHMiOltdLCJhY2NvdW50Ijp7fSwicGVyZm9ybWFuY2UiOnsic2RrUGFyc2VUaW1lIjoxfSwiX3Rvb2xzRXZlbnRMaW5rSWQiOiI1NjkwODg5MTk0NDE3MjQyIiwiZGVidWciOnsiZXhwbGFuYXRpb25zIjp0cnVlfX0%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x5584a9d0dcea <unknown>
#1 0x5584a97be5f0 <unknown>
#2 0x5584a97a4e86 <unknown>
#3 0x5584a97a379a <unknown>
#4 0x5584a97a3eff <unknown>
#5 0x5584a97a3e54 <unknown>
#6 0x5584a97c27ff <unknown>
#7 0x5584a98679aa <unknown>
#8 0x5584a9835662 <unknown>
#9 0x5584a985b660 <unknown>
#10 0x5584a9835433 <unknown>
#11 0x5584a9801ea3 <unknown>
#12 0x5584a9802b01 <unknown>
#13 0x5584a9cd2b3b <unknown>
#14 0x5584a9cd6a21 <unknown>
#15 0x5584a9cb9c32 <unknown>
#16 0x5584a9cd7594 <unknown>
#17 0x5584a9c9deef <unknown>
#18 0x5584a9cfbd98 <unknown>
#19 0x5584a9cfbf76 <unknown>
#20 0x5584a9d0cb36 <unknown>
#21 0x7f078749caa4 <unknown>
#22 0x7f0787529c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJhY3Rpb24iOiJzZXRfdXNlcl9hdHRyaWJ1dGUiLCJhY2NvdW50Ijp7ImF0dHJpYnV0ZXMiOnsibGFzdFBpUGFnZSI6eyJ2ZWhpY2xlUEkiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56Lml0L3Bhc3NlbmdlcmNhcnMvbW9kZWxzL3N1di9nbGMvb3ZlcnZpZXcuaHRtbCIsInZlaGljbGVDb2RlIjoieDI1NCIsInZlaGljbGVCTSI6IjI1NDYiLCJ2ZWhpY2xlUElIaXN0b3J5IjoiMjU0NiIsInRpbWVzdGFtcCI6MTc0NTQ0MDk0ODI0OSwiZXhwaXJhdGlvbiI6MTIwfX19LCJ1c2VyIjp7ImF0dHJpYnV0ZXMiOnsiZ2FDbGllbnRJRCI6IjE3NDg5MjE4MDcuMTc0NTQ0MDk0NCJ9LCJhbm9uSWQiOiI5ZmNhYjQ1MWZmOWI2OTdmIn0sInNvdXJjZSI6eyJ1cmwiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56Lml0L3Bhc3NlbmdlcmNhcnMvbW9kZWxzL3N1di9nbGMvb3ZlcnZpZXcuaHRtbCIsInVybFJlZmVycmVyIjoiIiwiY2hhbm5lbCI6IldlYiIsImJlYWNvblZlcnNpb24iOjE2LCJjb25maWdWZXJzaW9uIjoiNjMiLCJjb250ZW50Wm9uZXMiOltdfSwiY29uc2VudHMiOltdLCJfdG9vbHNFdmVudExpbmtJZCI6IjU5OTk2ODc0MDM3NzI2MzYiLCJkZWJ1ZyI6eyJleHBsYW5hdGlvbnMiOnRydWV9fQ%3D%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x5584a9d0dcea <unknown>
#1 0x5584a97be5f0 <unknown>
#2 0x5584a97a4e86 <unknown>
#3 0x5584a97a379a <unknown>
#4 0x5584a97a3eff <unknown>
#5 0x5584a97a3e54 <unknown>
#6 0x5584a97c27ff <unknown>
#7 0x5584a98679aa <unknown>
#8 0x5584a9835662 <unknown>
#9 0x5584a985b660 <unknown>
#10 0x5584a9835433 <unknown>
#11 0x5584a9801ea3 <unknown>
#12 0x5584a9802b01 <unknown>
#13 0x5584a9cd2b3b <unknown>
#14 0x5584a9cd6a21 <unknown>
#15 0x5584a9cb9c32 <unknown>
#16 0x5584a9cd7594 <unknown>
#17 0x5584a9c9deef <unknown>
#18 0x5584a9cfbd98 <unknown>
#19 0x5584a9cfbf76 <unknown>
#20 0x5584a9d0cb36 <unknown>
#21 0x7f078749caa4 <unknown>
#22 0x7f0787529c3c <unknown>

ERROR    root:VerifyPersonalizationAndCapture.py:18 ‚ùå Error attaching screenshot to Allure: [Errno 2] No such file or directory: '/home/runner/work/QA-App-Allure/QA-App-Allure/Tests/BFV1_attempt_1.png'