ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJpdGVtQWN0aW9uIjoiVmlldyBJdGVtIiwiY2F0YWxvZyI6eyJJdGVtQ2xhc3MiOnsiX2lkIjoib3ZlcnZpZXcifX0sInVzZXIiOnsiYXR0cmlidXRlcyI6eyJnYUNsaWVudElEIjoiNzYxMzg4Nzc1LjE3NDU0Mzg5NzkifSwiYW5vbklkIjoiNTU4MTZiNGQ0ODFjNDkyNiJ9LCJzb3VyY2UiOnsidXJsIjoiaHR0cHM6Ly93d3cubWVyY2VkZXMtYmVuei5pdC9wYXNzZW5nZXJjYXJzL21vZGVscy9zdXYvZy1jbGFzcy9vdmVydmlldy5odG1sIiwidXJsUmVmZXJyZXIiOiIiLCJjaGFubmVsIjoiV2ViIiwiYmVhY29uVmVyc2lvbiI6MTYsImNvbmZpZ1ZlcnNpb24iOiI2MyIsImNvbnRlbnRab25lcyI6W119LCJjb25zZW50cyI6W10sImFjY291bnQiOnt9LCJfdG9vbHNFdmVudExpbmtJZCI6Ijg1MDA1NzM2ODgxMzA0NiIsImRlYnVnIjp7ImV4cGxhbmF0aW9ucyI6dHJ1ZX19: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x55d414a6bcea <unknown>
#1 0x55d41451c5f0 <unknown>
#2 0x55d414502e86 <unknown>
#3 0x55d41450179a <unknown>
#4 0x55d414501eff <unknown>
#5 0x55d414501e54 <unknown>
#6 0x55d4145207ff <unknown>
#7 0x55d4145c59aa <unknown>
#8 0x55d414593662 <unknown>
#9 0x55d4145b9660 <unknown>
#10 0x55d414593433 <unknown>
#11 0x55d41455fea3 <unknown>
#12 0x55d414560b01 <unknown>
#13 0x55d414a30b3b <unknown>
#14 0x55d414a34a21 <unknown>
#15 0x55d414a17c32 <unknown>
#16 0x55d414a35594 <unknown>
#17 0x55d4149fbeef <unknown>
#18 0x55d414a59d98 <unknown>
#19 0x55d414a59f76 <unknown>
#20 0x55d414a6ab36 <unknown>
#21 0x7f5d2969caa4 <unknown>
#22 0x7f5d29729c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJhY3Rpb24iOiJQcm9kdWN0IEluZm9ybWF0aW9uIFBhZ2UgLSBvdmVydmlldyA0NjUyIiwiaXRlbUFjdGlvbiI6IlZpZXcgSXRlbSIsInNvdXJjZSI6eyJwYWdlVHlwZSI6InByb2R1Y3RfaW5mb3JtYXRpb24iLCJsb2NhbGUiOiJpdF9JVCIsImNvbnRlbnRab25lcyI6WyJnbG9iYWxfUElfTkwiLCJwaV9iYW5uZXJfTkwiLCJlcXMtc3BlY2lhbF9OTCJdLCJ1cmwiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56Lml0L3Bhc3NlbmdlcmNhcnMvbW9kZWxzL3N1di9nLWNsYXNzL292ZXJ2aWV3Lmh0bWwiLCJ1cmxSZWZlcnJlciI6IiIsImNoYW5uZWwiOiJXZWIiLCJiZWFjb25WZXJzaW9uIjoxNiwiY29uZmlnVmVyc2lvbiI6IjYzIn0sImZsYWdzIjp7InBhZ2VWaWV3Ijp0cnVlfSwidXNlciI6eyJhdHRyaWJ1dGVzIjp7ImdhQ2xpZW50SUQiOiI3NjEzODg3NzUuMTc0NTQzODk3OSJ9LCJhbm9uSWQiOiI1NTgxNmI0ZDQ4MWM0OTI2In0sInBlcmZvcm1hbmNlIjp7InNka1BhcnNlVGltZSI6MX0sImRlYnVnIjp7ImV4cGxhbmF0aW9ucyI6dHJ1ZX0sImNhdGFsb2ciOnsiUHJvZHVjdCI6eyJfaWQiOiI0NjUyIiwiZGltZW5zaW9ucyI6eyJCYXVtdXN0ZXJTaG9ydCI6WyI0NjUyIl19fX0sImNvbnNlbnRzIjpbXSwiYWNjb3VudCI6e30sIl90b29sc0V2ZW50TGlua0lkIjoiNDE4OTE0MzkzNDA2ODg2ODUifQ%3D%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x55d414a6bcea <unknown>
#1 0x55d41451c5f0 <unknown>
#2 0x55d414502e86 <unknown>
#3 0x55d41450179a <unknown>
#4 0x55d414501eff <unknown>
#5 0x55d414501e54 <unknown>
#6 0x55d4145207ff <unknown>
#7 0x55d4145c59aa <unknown>
#8 0x55d414593662 <unknown>
#9 0x55d4145b9660 <unknown>
#10 0x55d414593433 <unknown>
#11 0x55d41455fea3 <unknown>
#12 0x55d414560b01 <unknown>
#13 0x55d414a30b3b <unknown>
#14 0x55d414a34a21 <unknown>
#15 0x55d414a17c32 <unknown>
#16 0x55d414a35594 <unknown>
#17 0x55d4149fbeef <unknown>
#18 0x55d414a59d98 <unknown>
#19 0x55d414a59f76 <unknown>
#20 0x55d414a6ab36 <unknown>
#21 0x7f5d2969caa4 <unknown>
#22 0x7f5d29729c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJhY3Rpb24iOiJWaXNpdGVkIC0gb3ZlcnZpZXciLCJ1c2VyIjp7ImF0dHJpYnV0ZXMiOnsiZ2FDbGllbnRJRCI6Ijc2MTM4ODc3NS4xNzQ1NDM4OTc5In0sImFub25JZCI6IjU1ODE2YjRkNDgxYzQ5MjYifSwic291cmNlIjp7InVybCI6Imh0dHBzOi8vd3d3Lm1lcmNlZGVzLWJlbnouaXQvcGFzc2VuZ2VyY2Fycy9tb2RlbHMvc3V2L2ctY2xhc3Mvb3ZlcnZpZXcuaHRtbCIsInVybFJlZmVycmVyIjoiIiwiY2hhbm5lbCI6IldlYiIsImJlYWNvblZlcnNpb24iOjE2LCJjb25maWdWZXJzaW9uIjoiNjMiLCJjb250ZW50Wm9uZXMiOltdfSwiY29uc2VudHMiOltdLCJhY2NvdW50Ijp7fSwicGVyZm9ybWFuY2UiOnsic2RrUGFyc2VUaW1lIjoxfSwiX3Rvb2xzRXZlbnRMaW5rSWQiOiI1NTY0NTg1MTI4MzMwMjk4IiwiZGVidWciOnsiZXhwbGFuYXRpb25zIjp0cnVlfX0%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x55d414a6bcea <unknown>
#1 0x55d41451c5f0 <unknown>
#2 0x55d414502e86 <unknown>
#3 0x55d41450179a <unknown>
#4 0x55d414501eff <unknown>
#5 0x55d414501e54 <unknown>
#6 0x55d4145207ff <unknown>
#7 0x55d4145c59aa <unknown>
#8 0x55d414593662 <unknown>
#9 0x55d4145b9660 <unknown>
#10 0x55d414593433 <unknown>
#11 0x55d41455fea3 <unknown>
#12 0x55d414560b01 <unknown>
#13 0x55d414a30b3b <unknown>
#14 0x55d414a34a21 <unknown>
#15 0x55d414a17c32 <unknown>
#16 0x55d414a35594 <unknown>
#17 0x55d4149fbeef <unknown>
#18 0x55d414a59d98 <unknown>
#19 0x55d414a59f76 <unknown>
#20 0x55d414a6ab36 <unknown>
#21 0x7f5d2969caa4 <unknown>
#22 0x7f5d29729c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJhY3Rpb24iOiJzZXRfdXNlcl9hdHRyaWJ1dGUiLCJhY2NvdW50Ijp7ImF0dHJpYnV0ZXMiOnsibGFzdFBpUGFnZSI6eyJ2ZWhpY2xlUEkiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56Lml0L3Bhc3NlbmdlcmNhcnMvbW9kZWxzL3N1di9nLWNsYXNzL292ZXJ2aWV3Lmh0bWwiLCJ2ZWhpY2xlQ29kZSI6Inc0NjUiLCJ2ZWhpY2xlQk0iOiI0NjUyIiwidmVoaWNsZVBJSGlzdG9yeSI6IjQ2NTIiLCJ0aW1lc3RhbXAiOjE3NDU0Mzg5ODMwMjAsImV4cGlyYXRpb24iOjEyMH19fSwidXNlciI6eyJhdHRyaWJ1dGVzIjp7ImdhQ2xpZW50SUQiOiI3NjEzODg3NzUuMTc0NTQzODk3OSJ9LCJhbm9uSWQiOiI1NTgxNmI0ZDQ4MWM0OTI2In0sInNvdXJjZSI6eyJ1cmwiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56Lml0L3Bhc3NlbmdlcmNhcnMvbW9kZWxzL3N1di9nLWNsYXNzL292ZXJ2aWV3Lmh0bWwiLCJ1cmxSZWZlcnJlciI6IiIsImNoYW5uZWwiOiJXZWIiLCJiZWFjb25WZXJzaW9uIjoxNiwiY29uZmlnVmVyc2lvbiI6IjYzIiwiY29udGVudFpvbmVzIjpbXX0sImNvbnNlbnRzIjpbXSwiX3Rvb2xzRXZlbnRMaW5rSWQiOiIyNDA4Mzc5OTg1NTgwNTk2NSIsImRlYnVnIjp7ImV4cGxhbmF0aW9ucyI6dHJ1ZX19: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x55d414a6bcea <unknown>
#1 0x55d41451c5f0 <unknown>
#2 0x55d414502e86 <unknown>
#3 0x55d41450179a <unknown>
#4 0x55d414501eff <unknown>
#5 0x55d414501e54 <unknown>
#6 0x55d4145207ff <unknown>
#7 0x55d4145c59aa <unknown>
#8 0x55d414593662 <unknown>
#9 0x55d4145b9660 <unknown>
#10 0x55d414593433 <unknown>
#11 0x55d41455fea3 <unknown>
#12 0x55d414560b01 <unknown>
#13 0x55d414a30b3b <unknown>
#14 0x55d414a34a21 <unknown>
#15 0x55d414a17c32 <unknown>
#16 0x55d414a35594 <unknown>
#17 0x55d4149fbeef <unknown>
#18 0x55d414a59d98 <unknown>
#19 0x55d414a59f76 <unknown>
#20 0x55d414a6ab36 <unknown>
#21 0x7f5d2969caa4 <unknown>
#22 0x7f5d29729c3c <unknown>

ERROR    root:VerifyPersonalizationAndCapture.py:111 ❌ Image not found in the specified selector. Error: Message: 

ERROR    root:VerifyPersonalizationAndCapture.py:18 ❌ Error attaching screenshot to Allure: [Errno 2] No such file or directory: '/home/runner/work/QA-App-Allure/QA-App-Allure/Tests/BFV1_attempt_1.png'
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f73b65ce2d0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/6a64ec939a4ea7a1b6668d4465435e49
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f73b65cdcd0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/6a64ec939a4ea7a1b6668d4465435e49
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f73b65cd590>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/6a64ec939a4ea7a1b6668d4465435e49
ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJpdGVtQWN0aW9uIjoiVmlldyBJdGVtIiwiY2F0YWxvZyI6eyJJdGVtQ2xhc3MiOnsiX2lkIjoib3ZlcnZpZXcifX0sInNvdXJjZSI6eyJ1cmwiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56Lml0L3Bhc3NlbmdlcmNhcnMvbW9kZWxzL3N1di9nLWNsYXNzL292ZXJ2aWV3Lmh0bWwiLCJ1cmxSZWZlcnJlciI6IiIsImNoYW5uZWwiOiJXZWIiLCJiZWFjb25WZXJzaW9uIjoxNiwiY29uZmlnVmVyc2lvbiI6IjYzIiwiY29udGVudFpvbmVzIjpbXX0sInVzZXIiOnsiYW5vbklkIjoiMDczMDA1OWMwOGRiY2UzNiJ9LCJjb25zZW50cyI6W10sImFjY291bnQiOnt9LCJfdG9vbHNFdmVudExpbmtJZCI6IjcyMDM5MDE5NjU3NDM1MjkiLCJkZWJ1ZyI6eyJleHBsYW5hdGlvbnMiOnRydWV9fQ%3D%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x558a33423cea <unknown>
#1 0x558a32ed45f0 <unknown>
#2 0x558a32ebae86 <unknown>
#3 0x558a32eb979a <unknown>
#4 0x558a32eb9eff <unknown>
#5 0x558a32eb9e54 <unknown>
#6 0x558a32ed87ff <unknown>
#7 0x558a32f7d9aa <unknown>
#8 0x558a32f4b662 <unknown>
#9 0x558a32f71660 <unknown>
#10 0x558a32f4b433 <unknown>
#11 0x558a32f17ea3 <unknown>
#12 0x558a32f18b01 <unknown>
#13 0x558a333e8b3b <unknown>
#14 0x558a333eca21 <unknown>
#15 0x558a333cfc32 <unknown>
#16 0x558a333ed594 <unknown>
#17 0x558a333b3eef <unknown>
#18 0x558a33411d98 <unknown>
#19 0x558a33411f76 <unknown>
#20 0x558a33422b36 <unknown>
#21 0x7fe30d09caa4 <unknown>
#22 0x7fe30d129c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJhY3Rpb24iOiJQcm9kdWN0IEluZm9ybWF0aW9uIFBhZ2UgLSBvdmVydmlldyA0NjUyIiwiaXRlbUFjdGlvbiI6IlZpZXcgSXRlbSIsInNvdXJjZSI6eyJwYWdlVHlwZSI6InByb2R1Y3RfaW5mb3JtYXRpb24iLCJsb2NhbGUiOiJpdF9JVCIsImNvbnRlbnRab25lcyI6WyJnbG9iYWxfUElfTkwiLCJwaV9iYW5uZXJfTkwiLCJlcXMtc3BlY2lhbF9OTCJdLCJ1cmwiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56Lml0L3Bhc3NlbmdlcmNhcnMvbW9kZWxzL3N1di9nLWNsYXNzL292ZXJ2aWV3Lmh0bWwiLCJ1cmxSZWZlcnJlciI6IiIsImNoYW5uZWwiOiJXZWIiLCJiZWFjb25WZXJzaW9uIjoxNiwiY29uZmlnVmVyc2lvbiI6IjYzIn0sImZsYWdzIjp7InBhZ2VWaWV3Ijp0cnVlfSwidXNlciI6eyJhbm9uSWQiOiIwNzMwMDU5YzA4ZGJjZTM2In0sInBlcmZvcm1hbmNlIjp7fSwiZGVidWciOnsiZXhwbGFuYXRpb25zIjp0cnVlfSwiY2F0YWxvZyI6eyJQcm9kdWN0Ijp7Il9pZCI6IjQ2NTIiLCJkaW1lbnNpb25zIjp7IkJhdW11c3RlclNob3J0IjpbIjQ2NTIiXX19fSwiY29uc2VudHMiOltdLCJhY2NvdW50Ijp7fSwiX3Rvb2xzRXZlbnRMaW5rSWQiOiI2MTgxMzA2MTQ5NDY1MzA5In0%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x558a33423cea <unknown>
#1 0x558a32ed45f0 <unknown>
#2 0x558a32ebae86 <unknown>
#3 0x558a32eb979a <unknown>
#4 0x558a32eb9eff <unknown>
#5 0x558a32eb9e54 <unknown>
#6 0x558a32ed87ff <unknown>
#7 0x558a32f7d9aa <unknown>
#8 0x558a32f4b662 <unknown>
#9 0x558a32f71660 <unknown>
#10 0x558a32f4b433 <unknown>
#11 0x558a32f17ea3 <unknown>
#12 0x558a32f18b01 <unknown>
#13 0x558a333e8b3b <unknown>
#14 0x558a333eca21 <unknown>
#15 0x558a333cfc32 <unknown>
#16 0x558a333ed594 <unknown>
#17 0x558a333b3eef <unknown>
#18 0x558a33411d98 <unknown>
#19 0x558a33411f76 <unknown>
#20 0x558a33422b36 <unknown>
#21 0x7fe30d09caa4 <unknown>
#22 0x7fe30d129c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJhY3Rpb24iOiJWaXNpdGVkIC0gb3ZlcnZpZXciLCJzb3VyY2UiOnsidXJsIjoiaHR0cHM6Ly93d3cubWVyY2VkZXMtYmVuei5pdC9wYXNzZW5nZXJjYXJzL21vZGVscy9zdXYvZy1jbGFzcy9vdmVydmlldy5odG1sIiwidXJsUmVmZXJyZXIiOiIiLCJjaGFubmVsIjoiV2ViIiwiYmVhY29uVmVyc2lvbiI6MTYsImNvbmZpZ1ZlcnNpb24iOiI2MyIsImNvbnRlbnRab25lcyI6W119LCJ1c2VyIjp7ImFub25JZCI6IjA3MzAwNTljMDhkYmNlMzYifSwiY29uc2VudHMiOltdLCJhY2NvdW50Ijp7fSwiX3Rvb2xzRXZlbnRMaW5rSWQiOiIyOTcxNzIyMzgyNDYwMTIiLCJkZWJ1ZyI6eyJleHBsYW5hdGlvbnMiOnRydWV9fQ%3D%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x558a33423cea <unknown>
#1 0x558a32ed45f0 <unknown>
#2 0x558a32ebae86 <unknown>
#3 0x558a32eb979a <unknown>
#4 0x558a32eb9eff <unknown>
#5 0x558a32eb9e54 <unknown>
#6 0x558a32ed87ff <unknown>
#7 0x558a32f7d9aa <unknown>
#8 0x558a32f4b662 <unknown>
#9 0x558a32f71660 <unknown>
#10 0x558a32f4b433 <unknown>
#11 0x558a32f17ea3 <unknown>
#12 0x558a32f18b01 <unknown>
#13 0x558a333e8b3b <unknown>
#14 0x558a333eca21 <unknown>
#15 0x558a333cfc32 <unknown>
#16 0x558a333ed594 <unknown>
#17 0x558a333b3eef <unknown>
#18 0x558a33411d98 <unknown>
#19 0x558a33411f76 <unknown>
#20 0x558a33422b36 <unknown>
#21 0x7fe30d09caa4 <unknown>
#22 0x7fe30d129c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJhY3Rpb24iOiJzZXRfdXNlcl9hdHRyaWJ1dGUiLCJhY2NvdW50Ijp7ImF0dHJpYnV0ZXMiOnsibGFzdFBpUGFnZSI6eyJ2ZWhpY2xlUEkiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56Lml0L3Bhc3NlbmdlcmNhcnMvbW9kZWxzL3N1di9nLWNsYXNzL292ZXJ2aWV3Lmh0bWwiLCJ2ZWhpY2xlQ29kZSI6Inc0NjUiLCJ2ZWhpY2xlQk0iOiI0NjUyIiwidmVoaWNsZVBJSGlzdG9yeSI6IjQ2NTIiLCJ0aW1lc3RhbXAiOjE3NDU0MzkwMTYyNDcsImV4cGlyYXRpb24iOjEyMH19fSwidXNlciI6eyJhdHRyaWJ1dGVzIjp7ImdhQ2xpZW50SUQiOiI1ODQ4MTExMTcuMTc0NTQzOTAxNCJ9LCJhbm9uSWQiOiIwNzMwMDU5YzA4ZGJjZTM2In0sInNvdXJjZSI6eyJ1cmwiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56Lml0L3Bhc3NlbmdlcmNhcnMvbW9kZWxzL3N1di9nLWNsYXNzL292ZXJ2aWV3Lmh0bWwiLCJ1cmxSZWZlcnJlciI6IiIsImNoYW5uZWwiOiJXZWIiLCJiZWFjb25WZXJzaW9uIjoxNiwiY29uZmlnVmVyc2lvbiI6IjYzIiwiY29udGVudFpvbmVzIjpbXX0sImNvbnNlbnRzIjpbXSwiX3Rvb2xzRXZlbnRMaW5rSWQiOiI1MjIzMzQxNzQ5NDA5MjUiLCJkZWJ1ZyI6eyJleHBsYW5hdGlvbnMiOnRydWV9fQ%3D%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x558a33423cea <unknown>
#1 0x558a32ed45f0 <unknown>
#2 0x558a32ebae86 <unknown>
#3 0x558a32eb979a <unknown>
#4 0x558a32eb9eff <unknown>
#5 0x558a32eb9e54 <unknown>
#6 0x558a32ed87ff <unknown>
#7 0x558a32f7d9aa <unknown>
#8 0x558a32f4b662 <unknown>
#9 0x558a32f71660 <unknown>
#10 0x558a32f4b433 <unknown>
#11 0x558a32f17ea3 <unknown>
#12 0x558a32f18b01 <unknown>
#13 0x558a333e8b3b <unknown>
#14 0x558a333eca21 <unknown>
#15 0x558a333cfc32 <unknown>
#16 0x558a333ed594 <unknown>
#17 0x558a333b3eef <unknown>
#18 0x558a33411d98 <unknown>
#19 0x558a33411f76 <unknown>
#20 0x558a33422b36 <unknown>
#21 0x7fe30d09caa4 <unknown>
#22 0x7fe30d129c3c <unknown>

ERROR    root:VerifyPersonalizationAndCapture.py:18 ❌ Error attaching screenshot to Allure: [Errno 2] No such file or directory: '/home/runner/work/QA-App-Allure/QA-App-Allure/Tests/BFV1_attempt_2.png'
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f73b8d30290>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/6a64ec939a4ea7a1b6668d4465435e49
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f73b6541610>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/6a64ec939a4ea7a1b6668d4465435e49
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f73b6540c10>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/6a64ec939a4ea7a1b6668d4465435e49