ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJpdGVtQWN0aW9uIjoiVmlldyBJdGVtIiwiY2F0YWxvZyI6eyJJdGVtQ2xhc3MiOnsiX2lkIjoib3ZlcnZpZXcifX0sInVzZXIiOnsiYXR0cmlidXRlcyI6eyJnYUNsaWVudElEIjoiMTUwODcyNjAwMC4xNzQ1NDUwMTE0In0sImFub25JZCI6IjA5ZjY1ZmZjMzRmYzA0MjAifSwic291cmNlIjp7InVybCI6Imh0dHBzOi8vd3d3Lm1lcmNlZGVzLWJlbnouaXQvcGFzc2VuZ2VyY2Fycy9tb2RlbHMvc3V2L2ctY2xhc3Mvb3ZlcnZpZXcuaHRtbCIsInVybFJlZmVycmVyIjoiIiwiY2hhbm5lbCI6IldlYiIsImJlYWNvblZlcnNpb24iOjE2LCJjb25maWdWZXJzaW9uIjoiNjMiLCJjb250ZW50Wm9uZXMiOltdfSwiY29uc2VudHMiOltdLCJhY2NvdW50Ijp7fSwiX3Rvb2xzRXZlbnRMaW5rSWQiOiIxMTg2MjgwOTg5MjUzODk1IiwiZGVidWciOnsiZXhwbGFuYXRpb25zIjp0cnVlfX0%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x55f854f1ccea <unknown>
#1 0x55f8549cd5f0 <unknown>
#2 0x55f8549b3e86 <unknown>
#3 0x55f8549b279a <unknown>
#4 0x55f8549b2eff <unknown>
#5 0x55f8549b2e54 <unknown>
#6 0x55f8549d17ff <unknown>
#7 0x55f854a769aa <unknown>
#8 0x55f854a44662 <unknown>
#9 0x55f854a6a660 <unknown>
#10 0x55f854a44433 <unknown>
#11 0x55f854a10ea3 <unknown>
#12 0x55f854a11b01 <unknown>
#13 0x55f854ee1b3b <unknown>
#14 0x55f854ee5a21 <unknown>
#15 0x55f854ec8c32 <unknown>
#16 0x55f854ee6594 <unknown>
#17 0x55f854eaceef <unknown>
#18 0x55f854f0ad98 <unknown>
#19 0x55f854f0af76 <unknown>
#20 0x55f854f1bb36 <unknown>
#21 0x7fee4bc9caa4 <unknown>
#22 0x7fee4bd29c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJhY3Rpb24iOiJWaXNpdGVkIC0gb3ZlcnZpZXciLCJ1c2VyIjp7ImF0dHJpYnV0ZXMiOnsiZ2FDbGllbnRJRCI6IjE1MDg3MjYwMDAuMTc0NTQ1MDExNCJ9LCJhbm9uSWQiOiIwOWY2NWZmYzM0ZmMwNDIwIn0sInNvdXJjZSI6eyJ1cmwiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56Lml0L3Bhc3NlbmdlcmNhcnMvbW9kZWxzL3N1di9nLWNsYXNzL292ZXJ2aWV3Lmh0bWwiLCJ1cmxSZWZlcnJlciI6IiIsImNoYW5uZWwiOiJXZWIiLCJiZWFjb25WZXJzaW9uIjoxNiwiY29uZmlnVmVyc2lvbiI6IjYzIiwiY29udGVudFpvbmVzIjpbXX0sImNvbnNlbnRzIjpbXSwiYWNjb3VudCI6e30sInBlcmZvcm1hbmNlIjp7InNka1BhcnNlVGltZSI6MX0sIl90b29sc0V2ZW50TGlua0lkIjoiNDgyNjgyNTg3ODI2ODQ0MjYiLCJkZWJ1ZyI6eyJleHBsYW5hdGlvbnMiOnRydWV9fQ%3D%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x55f854f1ccea <unknown>
#1 0x55f8549cd5f0 <unknown>
#2 0x55f8549b3e86 <unknown>
#3 0x55f8549b279a <unknown>
#4 0x55f8549b2eff <unknown>
#5 0x55f8549b2e54 <unknown>
#6 0x55f8549d17ff <unknown>
#7 0x55f854a769aa <unknown>
#8 0x55f854a44662 <unknown>
#9 0x55f854a6a660 <unknown>
#10 0x55f854a44433 <unknown>
#11 0x55f854a10ea3 <unknown>
#12 0x55f854a11b01 <unknown>
#13 0x55f854ee1b3b <unknown>
#14 0x55f854ee5a21 <unknown>
#15 0x55f854ec8c32 <unknown>
#16 0x55f854ee6594 <unknown>
#17 0x55f854eaceef <unknown>
#18 0x55f854f0ad98 <unknown>
#19 0x55f854f0af76 <unknown>
#20 0x55f854f1bb36 <unknown>
#21 0x7fee4bc9caa4 <unknown>
#22 0x7fee4bd29c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJhY3Rpb24iOiJQcm9kdWN0IEluZm9ybWF0aW9uIFBhZ2UgLSBvdmVydmlldyA0NjUyIiwiaXRlbUFjdGlvbiI6IlZpZXcgSXRlbSIsInNvdXJjZSI6eyJwYWdlVHlwZSI6InByb2R1Y3RfaW5mb3JtYXRpb24iLCJsb2NhbGUiOiJpdF9JVCIsImNvbnRlbnRab25lcyI6WyJnbG9iYWxfUElfTkwiLCJwaV9iYW5uZXJfTkwiLCJlcXMtc3BlY2lhbF9OTCJdLCJ1cmwiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56Lml0L3Bhc3NlbmdlcmNhcnMvbW9kZWxzL3N1di9nLWNsYXNzL292ZXJ2aWV3Lmh0bWwiLCJ1cmxSZWZlcnJlciI6IiIsImNoYW5uZWwiOiJXZWIiLCJiZWFjb25WZXJzaW9uIjoxNiwiY29uZmlnVmVyc2lvbiI6IjYzIn0sImZsYWdzIjp7InBhZ2VWaWV3Ijp0cnVlfSwidXNlciI6eyJhdHRyaWJ1dGVzIjp7ImdhQ2xpZW50SUQiOiIxNTA4NzI2MDAwLjE3NDU0NTAxMTQifSwiYW5vbklkIjoiMDlmNjVmZmMzNGZjMDQyMCJ9LCJwZXJmb3JtYW5jZSI6eyJzZGtQYXJzZVRpbWUiOjF9LCJkZWJ1ZyI6eyJleHBsYW5hdGlvbnMiOnRydWV9LCJjYXRhbG9nIjp7IlByb2R1Y3QiOnsiX2lkIjoiNDY1MiIsImRpbWVuc2lvbnMiOnsiQmF1bXVzdGVyU2hvcnQiOlsiNDY1MiJdfX19LCJjb25zZW50cyI6W10sImFjY291bnQiOnt9LCJfdG9vbHNFdmVudExpbmtJZCI6IjM3OTk5MDYyMDA1NTIyMTY2In0%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x55f854f1ccea <unknown>
#1 0x55f8549cd5f0 <unknown>
#2 0x55f8549b3e86 <unknown>
#3 0x55f8549b279a <unknown>
#4 0x55f8549b2eff <unknown>
#5 0x55f8549b2e54 <unknown>
#6 0x55f8549d17ff <unknown>
#7 0x55f854a769aa <unknown>
#8 0x55f854a44662 <unknown>
#9 0x55f854a6a660 <unknown>
#10 0x55f854a44433 <unknown>
#11 0x55f854a10ea3 <unknown>
#12 0x55f854a11b01 <unknown>
#13 0x55f854ee1b3b <unknown>
#14 0x55f854ee5a21 <unknown>
#15 0x55f854ec8c32 <unknown>
#16 0x55f854ee6594 <unknown>
#17 0x55f854eaceef <unknown>
#18 0x55f854f0ad98 <unknown>
#19 0x55f854f0af76 <unknown>
#20 0x55f854f1bb36 <unknown>
#21 0x7fee4bc9caa4 <unknown>
#22 0x7fee4bd29c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJhY3Rpb24iOiJzZXRfdXNlcl9hdHRyaWJ1dGUiLCJhY2NvdW50Ijp7ImF0dHJpYnV0ZXMiOnsibGFzdFBpUGFnZSI6eyJ2ZWhpY2xlUEkiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56Lml0L3Bhc3NlbmdlcmNhcnMvbW9kZWxzL3N1di9nLWNsYXNzL292ZXJ2aWV3Lmh0bWwiLCJ2ZWhpY2xlQ29kZSI6Inc0NjUiLCJ2ZWhpY2xlQk0iOiI0NjUyIiwidmVoaWNsZVBJSGlzdG9yeSI6IjQ2NTIiLCJ0aW1lc3RhbXAiOjE3NDU0NTAxMTk1MDcsImV4cGlyYXRpb24iOjEyMH19fSwidXNlciI6eyJhdHRyaWJ1dGVzIjp7ImdhQ2xpZW50SUQiOiIxNTA4NzI2MDAwLjE3NDU0NTAxMTQifSwiYW5vbklkIjoiMDlmNjVmZmMzNGZjMDQyMCJ9LCJzb3VyY2UiOnsidXJsIjoiaHR0cHM6Ly93d3cubWVyY2VkZXMtYmVuei5pdC9wYXNzZW5nZXJjYXJzL21vZGVscy9zdXYvZy1jbGFzcy9vdmVydmlldy5odG1sIiwidXJsUmVmZXJyZXIiOiIiLCJjaGFubmVsIjoiV2ViIiwiYmVhY29uVmVyc2lvbiI6MTYsImNvbmZpZ1ZlcnNpb24iOiI2MyIsImNvbnRlbnRab25lcyI6W119LCJjb25zZW50cyI6W10sIl90b29sc0V2ZW50TGlua0lkIjoiNjg3MDI0MDczMTA1OTU4NCIsImRlYnVnIjp7ImV4cGxhbmF0aW9ucyI6dHJ1ZX19: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x55f854f1ccea <unknown>
#1 0x55f8549cd5f0 <unknown>
#2 0x55f8549b3e86 <unknown>
#3 0x55f8549b279a <unknown>
#4 0x55f8549b2eff <unknown>
#5 0x55f8549b2e54 <unknown>
#6 0x55f8549d17ff <unknown>
#7 0x55f854a769aa <unknown>
#8 0x55f854a44662 <unknown>
#9 0x55f854a6a660 <unknown>
#10 0x55f854a44433 <unknown>
#11 0x55f854a10ea3 <unknown>
#12 0x55f854a11b01 <unknown>
#13 0x55f854ee1b3b <unknown>
#14 0x55f854ee5a21 <unknown>
#15 0x55f854ec8c32 <unknown>
#16 0x55f854ee6594 <unknown>
#17 0x55f854eaceef <unknown>
#18 0x55f854f0ad98 <unknown>
#19 0x55f854f0af76 <unknown>
#20 0x55f854f1bb36 <unknown>
#21 0x7fee4bc9caa4 <unknown>
#22 0x7fee4bd29c3c <unknown>

ERROR    root:VerifyPersonalizationAndCapture.py:111 ❌ Image not found in the specified selector. Error: Message: 

ERROR    root:VerifyPersonalizationAndCapture.py:18 ❌ Error attaching screenshot to Allure: [Errno 2] No such file or directory: '/home/runner/work/QA-App-Allure/QA-App-Allure/Tests/BFV1_attempt_1.png'
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc8a7ee12d0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/781838d2387b7bc6d682b2c0b1a0d84d
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc8a7ee27d0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/781838d2387b7bc6d682b2c0b1a0d84d
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc8a7ee20d0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/781838d2387b7bc6d682b2c0b1a0d84d
ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJhY3Rpb24iOiJWaXNpdGVkIC0gb3ZlcnZpZXciLCJ1c2VyIjp7ImF0dHJpYnV0ZXMiOnsiZ2FDbGllbnRJRCI6IjEzMDU2Mzg1MjMuMTc0NTQ1MDE2MyJ9LCJhbm9uSWQiOiJkMTAxOGM5MTRiN2IxNTI4In0sInNvdXJjZSI6eyJ1cmwiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56Lml0L3Bhc3NlbmdlcmNhcnMvbW9kZWxzL3N1di9nLWNsYXNzL292ZXJ2aWV3Lmh0bWwiLCJ1cmxSZWZlcnJlciI6IiIsImNoYW5uZWwiOiJXZWIiLCJiZWFjb25WZXJzaW9uIjoxNiwiY29uZmlnVmVyc2lvbiI6IjYzIiwiY29udGVudFpvbmVzIjpbXX0sImNvbnNlbnRzIjpbXSwiYWNjb3VudCI6e30sIl90b29sc0V2ZW50TGlua0lkIjoiMDgzMzc1NjQzODE2MzU2OTgiLCJkZWJ1ZyI6eyJleHBsYW5hdGlvbnMiOnRydWV9fQ%3D%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x55795000ecea <unknown>
#1 0x55794fabf5f0 <unknown>
#2 0x55794faa5e86 <unknown>
#3 0x55794faa479a <unknown>
#4 0x55794faa4eff <unknown>
#5 0x55794faa4e54 <unknown>
#6 0x55794fac37ff <unknown>
#7 0x55794fb689aa <unknown>
#8 0x55794fb36662 <unknown>
#9 0x55794fb5c660 <unknown>
#10 0x55794fb36433 <unknown>
#11 0x55794fb02ea3 <unknown>
#12 0x55794fb03b01 <unknown>
#13 0x55794ffd3b3b <unknown>
#14 0x55794ffd7a21 <unknown>
#15 0x55794ffbac32 <unknown>
#16 0x55794ffd8594 <unknown>
#17 0x55794ff9eeef <unknown>
#18 0x55794fffcd98 <unknown>
#19 0x55794fffcf76 <unknown>
#20 0x55795000db36 <unknown>
#21 0x7f2a0329caa4 <unknown>
#22 0x7f2a03329c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJpdGVtQWN0aW9uIjoiVmlldyBJdGVtIiwiY2F0YWxvZyI6eyJJdGVtQ2xhc3MiOnsiX2lkIjoib3ZlcnZpZXcifX0sInVzZXIiOnsiYXR0cmlidXRlcyI6eyJnYUNsaWVudElEIjoiMTMwNTYzODUyMy4xNzQ1NDUwMTYzIn0sImFub25JZCI6ImQxMDE4YzkxNGI3YjE1MjgifSwic291cmNlIjp7InVybCI6Imh0dHBzOi8vd3d3Lm1lcmNlZGVzLWJlbnouaXQvcGFzc2VuZ2VyY2Fycy9tb2RlbHMvc3V2L2ctY2xhc3Mvb3ZlcnZpZXcuaHRtbCIsInVybFJlZmVycmVyIjoiIiwiY2hhbm5lbCI6IldlYiIsImJlYWNvblZlcnNpb24iOjE2LCJjb25maWdWZXJzaW9uIjoiNjMiLCJjb250ZW50Wm9uZXMiOltdfSwiY29uc2VudHMiOltdLCJhY2NvdW50Ijp7fSwicGVyZm9ybWFuY2UiOnsic2RrUGFyc2VUaW1lIjoxfSwiX3Rvb2xzRXZlbnRMaW5rSWQiOiIwOTk2Mjk4NDQ5MzEwMDAyNCIsImRlYnVnIjp7ImV4cGxhbmF0aW9ucyI6dHJ1ZX19: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x55795000ecea <unknown>
#1 0x55794fabf5f0 <unknown>
#2 0x55794faa5e86 <unknown>
#3 0x55794faa479a <unknown>
#4 0x55794faa4eff <unknown>
#5 0x55794faa4e54 <unknown>
#6 0x55794fac37ff <unknown>
#7 0x55794fb689aa <unknown>
#8 0x55794fb36662 <unknown>
#9 0x55794fb5c660 <unknown>
#10 0x55794fb36433 <unknown>
#11 0x55794fb02ea3 <unknown>
#12 0x55794fb03b01 <unknown>
#13 0x55794ffd3b3b <unknown>
#14 0x55794ffd7a21 <unknown>
#15 0x55794ffbac32 <unknown>
#16 0x55794ffd8594 <unknown>
#17 0x55794ff9eeef <unknown>
#18 0x55794fffcd98 <unknown>
#19 0x55794fffcf76 <unknown>
#20 0x55795000db36 <unknown>
#21 0x7f2a0329caa4 <unknown>
#22 0x7f2a03329c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJhY3Rpb24iOiJQcm9kdWN0IEluZm9ybWF0aW9uIFBhZ2UgLSBvdmVydmlldyA0NjUyIiwiaXRlbUFjdGlvbiI6IlZpZXcgSXRlbSIsInNvdXJjZSI6eyJwYWdlVHlwZSI6InByb2R1Y3RfaW5mb3JtYXRpb24iLCJsb2NhbGUiOiJpdF9JVCIsImNvbnRlbnRab25lcyI6WyJnbG9iYWxfUElfTkwiLCJwaV9iYW5uZXJfTkwiLCJlcXMtc3BlY2lhbF9OTCJdLCJ1cmwiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56Lml0L3Bhc3NlbmdlcmNhcnMvbW9kZWxzL3N1di9nLWNsYXNzL292ZXJ2aWV3Lmh0bWwiLCJ1cmxSZWZlcnJlciI6IiIsImNoYW5uZWwiOiJXZWIiLCJiZWFjb25WZXJzaW9uIjoxNiwiY29uZmlnVmVyc2lvbiI6IjYzIn0sImZsYWdzIjp7InBhZ2VWaWV3Ijp0cnVlfSwidXNlciI6eyJhdHRyaWJ1dGVzIjp7ImdhQ2xpZW50SUQiOiIxMzA1NjM4NTIzLjE3NDU0NTAxNjMifSwiYW5vbklkIjoiZDEwMThjOTE0YjdiMTUyOCJ9LCJwZXJmb3JtYW5jZSI6eyJzZGtQYXJzZVRpbWUiOjF9LCJkZWJ1ZyI6eyJleHBsYW5hdGlvbnMiOnRydWV9LCJjYXRhbG9nIjp7IlByb2R1Y3QiOnsiX2lkIjoiNDY1MiIsImRpbWVuc2lvbnMiOnsiQmF1bXVzdGVyU2hvcnQiOlsiNDY1MiJdfX19LCJjb25zZW50cyI6W10sImFjY291bnQiOnt9LCJfdG9vbHNFdmVudExpbmtJZCI6Ijc5MTI2MDQ1NDAwNTYzNTMifQ%3D%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x55795000ecea <unknown>
#1 0x55794fabf5f0 <unknown>
#2 0x55794faa5e86 <unknown>
#3 0x55794faa479a <unknown>
#4 0x55794faa4eff <unknown>
#5 0x55794faa4e54 <unknown>
#6 0x55794fac37ff <unknown>
#7 0x55794fb689aa <unknown>
#8 0x55794fb36662 <unknown>
#9 0x55794fb5c660 <unknown>
#10 0x55794fb36433 <unknown>
#11 0x55794fb02ea3 <unknown>
#12 0x55794fb03b01 <unknown>
#13 0x55794ffd3b3b <unknown>
#14 0x55794ffd7a21 <unknown>
#15 0x55794ffbac32 <unknown>
#16 0x55794ffd8594 <unknown>
#17 0x55794ff9eeef <unknown>
#18 0x55794fffcd98 <unknown>
#19 0x55794fffcf76 <unknown>
#20 0x55795000db36 <unknown>
#21 0x7f2a0329caa4 <unknown>
#22 0x7f2a03329c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJhY3Rpb24iOiJzZXRfdXNlcl9hdHRyaWJ1dGUiLCJhY2NvdW50Ijp7ImF0dHJpYnV0ZXMiOnsibGFzdFBpUGFnZSI6eyJ2ZWhpY2xlUEkiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56Lml0L3Bhc3NlbmdlcmNhcnMvbW9kZWxzL3N1di9nLWNsYXNzL292ZXJ2aWV3Lmh0bWwiLCJ2ZWhpY2xlQ29kZSI6Inc0NjUiLCJ2ZWhpY2xlQk0iOiI0NjUyIiwidmVoaWNsZVBJSGlzdG9yeSI6IjQ2NTIiLCJ0aW1lc3RhbXAiOjE3NDU0NTAxNjk3MDUsImV4cGlyYXRpb24iOjEyMH19fSwidXNlciI6eyJhdHRyaWJ1dGVzIjp7ImdhQ2xpZW50SUQiOiIxMzA1NjM4NTIzLjE3NDU0NTAxNjMifSwiYW5vbklkIjoiZDEwMThjOTE0YjdiMTUyOCJ9LCJzb3VyY2UiOnsidXJsIjoiaHR0cHM6Ly93d3cubWVyY2VkZXMtYmVuei5pdC9wYXNzZW5nZXJjYXJzL21vZGVscy9zdXYvZy1jbGFzcy9vdmVydmlldy5odG1sIiwidXJsUmVmZXJyZXIiOiIiLCJjaGFubmVsIjoiV2ViIiwiYmVhY29uVmVyc2lvbiI6MTYsImNvbmZpZ1ZlcnNpb24iOiI2MyIsImNvbnRlbnRab25lcyI6W119LCJjb25zZW50cyI6W10sIl90b29sc0V2ZW50TGlua0lkIjoiNTA5NTAzNTU5NzgxMDIzNiIsImRlYnVnIjp7ImV4cGxhbmF0aW9ucyI6dHJ1ZX19: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x55795000ecea <unknown>
#1 0x55794fabf5f0 <unknown>
#2 0x55794faa5e86 <unknown>
#3 0x55794faa479a <unknown>
#4 0x55794faa4eff <unknown>
#5 0x55794faa4e54 <unknown>
#6 0x55794fac37ff <unknown>
#7 0x55794fb689aa <unknown>
#8 0x55794fb36662 <unknown>
#9 0x55794fb5c660 <unknown>
#10 0x55794fb36433 <unknown>
#11 0x55794fb02ea3 <unknown>
#12 0x55794fb03b01 <unknown>
#13 0x55794ffd3b3b <unknown>
#14 0x55794ffd7a21 <unknown>
#15 0x55794ffbac32 <unknown>
#16 0x55794ffd8594 <unknown>
#17 0x55794ff9eeef <unknown>
#18 0x55794fffcd98 <unknown>
#19 0x55794fffcf76 <unknown>
#20 0x55795000db36 <unknown>
#21 0x7f2a0329caa4 <unknown>
#22 0x7f2a03329c3c <unknown>

ERROR    root:VerifyPersonalizationAndCapture.py:111 ❌ Image not found in the specified selector. Error: Message: 

ERROR    root:VerifyPersonalizationAndCapture.py:18 ❌ Error attaching screenshot to Allure: [Errno 2] No such file or directory: '/home/runner/work/QA-App-Allure/QA-App-Allure/Tests/BFV1_attempt_2.png'
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc8ac636e50>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/bf10af042c4292c9e026fb01995d4263
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc8ac637850>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/bf10af042c4292c9e026fb01995d4263
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc8ac634090>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/bf10af042c4292c9e026fb01995d4263
ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJhY3Rpb24iOiJWaXNpdGVkIC0gb3ZlcnZpZXciLCJ1c2VyIjp7ImF0dHJpYnV0ZXMiOnsiZ2FDbGllbnRJRCI6IjY0MjcxNzkzNy4xNzQ1NDUwMjA5In0sImFub25JZCI6ImYyYTBlYzI5Zjg4YjA0OWUifSwic291cmNlIjp7InVybCI6Imh0dHBzOi8vd3d3Lm1lcmNlZGVzLWJlbnouaXQvcGFzc2VuZ2VyY2Fycy9tb2RlbHMvc3V2L2ctY2xhc3Mvb3ZlcnZpZXcuaHRtbCIsInVybFJlZmVycmVyIjoiIiwiY2hhbm5lbCI6IldlYiIsImJlYWNvblZlcnNpb24iOjE2LCJjb25maWdWZXJzaW9uIjoiNjMiLCJjb250ZW50Wm9uZXMiOltdfSwiY29uc2VudHMiOltdLCJhY2NvdW50Ijp7fSwicGVyZm9ybWFuY2UiOnsic2RrUGFyc2VUaW1lIjoyfSwiX3Rvb2xzRXZlbnRMaW5rSWQiOiI0MjA5NTMyMzY4OTQ5MDQ2IiwiZGVidWciOnsiZXhwbGFuYXRpb25zIjp0cnVlfX0%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x559dabc9ccea <unknown>
#1 0x559dab74d5f0 <unknown>
#2 0x559dab733e86 <unknown>
#3 0x559dab73279a <unknown>
#4 0x559dab732eff <unknown>
#5 0x559dab732e54 <unknown>
#6 0x559dab7517ff <unknown>
#7 0x559dab7f69aa <unknown>
#8 0x559dab7c4662 <unknown>
#9 0x559dab7ea660 <unknown>
#10 0x559dab7c4433 <unknown>
#11 0x559dab790ea3 <unknown>
#12 0x559dab791b01 <unknown>
#13 0x559dabc61b3b <unknown>
#14 0x559dabc65a21 <unknown>
#15 0x559dabc48c32 <unknown>
#16 0x559dabc66594 <unknown>
#17 0x559dabc2ceef <unknown>
#18 0x559dabc8ad98 <unknown>
#19 0x559dabc8af76 <unknown>
#20 0x559dabc9bb36 <unknown>
#21 0x7fce2749caa4 <unknown>
#22 0x7fce27529c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJpdGVtQWN0aW9uIjoiVmlldyBJdGVtIiwiY2F0YWxvZyI6eyJJdGVtQ2xhc3MiOnsiX2lkIjoib3ZlcnZpZXcifX0sInVzZXIiOnsiYXR0cmlidXRlcyI6eyJnYUNsaWVudElEIjoiNjQyNzE3OTM3LjE3NDU0NTAyMDkifSwiYW5vbklkIjoiZjJhMGVjMjlmODhiMDQ5ZSJ9LCJzb3VyY2UiOnsidXJsIjoiaHR0cHM6Ly93d3cubWVyY2VkZXMtYmVuei5pdC9wYXNzZW5nZXJjYXJzL21vZGVscy9zdXYvZy1jbGFzcy9vdmVydmlldy5odG1sIiwidXJsUmVmZXJyZXIiOiIiLCJjaGFubmVsIjoiV2ViIiwiYmVhY29uVmVyc2lvbiI6MTYsImNvbmZpZ1ZlcnNpb24iOiI2MyIsImNvbnRlbnRab25lcyI6W119LCJjb25zZW50cyI6W10sImFjY291bnQiOnt9LCJfdG9vbHNFdmVudExpbmtJZCI6IjQ0NTU4ODg0MzQwMjEwMTI1IiwiZGVidWciOnsiZXhwbGFuYXRpb25zIjp0cnVlfX0%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x559dabc9ccea <unknown>
#1 0x559dab74d5f0 <unknown>
#2 0x559dab733e86 <unknown>
#3 0x559dab73279a <unknown>
#4 0x559dab732eff <unknown>
#5 0x559dab732e54 <unknown>
#6 0x559dab7517ff <unknown>
#7 0x559dab7f69aa <unknown>
#8 0x559dab7c4662 <unknown>
#9 0x559dab7ea660 <unknown>
#10 0x559dab7c4433 <unknown>
#11 0x559dab790ea3 <unknown>
#12 0x559dab791b01 <unknown>
#13 0x559dabc61b3b <unknown>
#14 0x559dabc65a21 <unknown>
#15 0x559dabc48c32 <unknown>
#16 0x559dabc66594 <unknown>
#17 0x559dabc2ceef <unknown>
#18 0x559dabc8ad98 <unknown>
#19 0x559dabc8af76 <unknown>
#20 0x559dabc9bb36 <unknown>
#21 0x7fce2749caa4 <unknown>
#22 0x7fce27529c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJhY3Rpb24iOiJQcm9kdWN0IEluZm9ybWF0aW9uIFBhZ2UgLSBvdmVydmlldyA0NjUyIiwiaXRlbUFjdGlvbiI6IlZpZXcgSXRlbSIsInNvdXJjZSI6eyJwYWdlVHlwZSI6InByb2R1Y3RfaW5mb3JtYXRpb24iLCJsb2NhbGUiOiJpdF9JVCIsImNvbnRlbnRab25lcyI6WyJnbG9iYWxfUElfTkwiLCJwaV9iYW5uZXJfTkwiLCJlcXMtc3BlY2lhbF9OTCJdLCJ1cmwiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56Lml0L3Bhc3NlbmdlcmNhcnMvbW9kZWxzL3N1di9nLWNsYXNzL292ZXJ2aWV3Lmh0bWwiLCJ1cmxSZWZlcnJlciI6IiIsImNoYW5uZWwiOiJXZWIiLCJiZWFjb25WZXJzaW9uIjoxNiwiY29uZmlnVmVyc2lvbiI6IjYzIn0sImZsYWdzIjp7InBhZ2VWaWV3Ijp0cnVlfSwidXNlciI6eyJhdHRyaWJ1dGVzIjp7ImdhQ2xpZW50SUQiOiI2NDI3MTc5MzcuMTc0NTQ1MDIwOSJ9LCJhbm9uSWQiOiJmMmEwZWMyOWY4OGIwNDllIn0sInBlcmZvcm1hbmNlIjp7InNka1BhcnNlVGltZSI6Mn0sImRlYnVnIjp7ImV4cGxhbmF0aW9ucyI6dHJ1ZX0sImNhdGFsb2ciOnsiUHJvZHVjdCI6eyJfaWQiOiI0NjUyIiwiZGltZW5zaW9ucyI6eyJCYXVtdXN0ZXJTaG9ydCI6WyI0NjUyIl19fX0sImNvbnNlbnRzIjpbXSwiYWNjb3VudCI6e30sIl90b29sc0V2ZW50TGlua0lkIjoiMDQ2ODI5Mzk1NzQzMzY5MTk1In0%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x559dabc9ccea <unknown>
#1 0x559dab74d5f0 <unknown>
#2 0x559dab733e86 <unknown>
#3 0x559dab73279a <unknown>
#4 0x559dab732eff <unknown>
#5 0x559dab732e54 <unknown>
#6 0x559dab7517ff <unknown>
#7 0x559dab7f69aa <unknown>
#8 0x559dab7c4662 <unknown>
#9 0x559dab7ea660 <unknown>
#10 0x559dab7c4433 <unknown>
#11 0x559dab790ea3 <unknown>
#12 0x559dab791b01 <unknown>
#13 0x559dabc61b3b <unknown>
#14 0x559dabc65a21 <unknown>
#15 0x559dabc48c32 <unknown>
#16 0x559dabc66594 <unknown>
#17 0x559dabc2ceef <unknown>
#18 0x559dabc8ad98 <unknown>
#19 0x559dabc8af76 <unknown>
#20 0x559dabc9bb36 <unknown>
#21 0x7fce2749caa4 <unknown>
#22 0x7fce27529c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJhY3Rpb24iOiJzZXRfdXNlcl9hdHRyaWJ1dGUiLCJhY2NvdW50Ijp7ImF0dHJpYnV0ZXMiOnsibGFzdFBpUGFnZSI6eyJ2ZWhpY2xlUEkiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56Lml0L3Bhc3NlbmdlcmNhcnMvbW9kZWxzL3N1di9nLWNsYXNzL292ZXJ2aWV3Lmh0bWwiLCJ2ZWhpY2xlQ29kZSI6Inc0NjUiLCJ2ZWhpY2xlQk0iOiI0NjUyIiwidmVoaWNsZVBJSGlzdG9yeSI6IjQ2NTIiLCJ0aW1lc3RhbXAiOjE3NDU0NTAyMTMzNTYsImV4cGlyYXRpb24iOjEyMH19fSwidXNlciI6eyJhdHRyaWJ1dGVzIjp7ImdhQ2xpZW50SUQiOiI2NDI3MTc5MzcuMTc0NTQ1MDIwOSJ9LCJhbm9uSWQiOiJmMmEwZWMyOWY4OGIwNDllIn0sInNvdXJjZSI6eyJ1cmwiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56Lml0L3Bhc3NlbmdlcmNhcnMvbW9kZWxzL3N1di9nLWNsYXNzL292ZXJ2aWV3Lmh0bWwiLCJ1cmxSZWZlcnJlciI6IiIsImNoYW5uZWwiOiJXZWIiLCJiZWFjb25WZXJzaW9uIjoxNiwiY29uZmlnVmVyc2lvbiI6IjYzIiwiY29udGVudFpvbmVzIjpbXX0sImNvbnNlbnRzIjpbXSwiX3Rvb2xzRXZlbnRMaW5rSWQiOiI0NTU1NDg5NDIyNjQ4OTI4NCIsImRlYnVnIjp7ImV4cGxhbmF0aW9ucyI6dHJ1ZX19: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x559dabc9ccea <unknown>
#1 0x559dab74d5f0 <unknown>
#2 0x559dab733e86 <unknown>
#3 0x559dab73279a <unknown>
#4 0x559dab732eff <unknown>
#5 0x559dab732e54 <unknown>
#6 0x559dab7517ff <unknown>
#7 0x559dab7f69aa <unknown>
#8 0x559dab7c4662 <unknown>
#9 0x559dab7ea660 <unknown>
#10 0x559dab7c4433 <unknown>
#11 0x559dab790ea3 <unknown>
#12 0x559dab791b01 <unknown>
#13 0x559dabc61b3b <unknown>
#14 0x559dabc65a21 <unknown>
#15 0x559dabc48c32 <unknown>
#16 0x559dabc66594 <unknown>
#17 0x559dabc2ceef <unknown>
#18 0x559dabc8ad98 <unknown>
#19 0x559dabc8af76 <unknown>
#20 0x559dabc9bb36 <unknown>
#21 0x7fce2749caa4 <unknown>
#22 0x7fce27529c3c <unknown>

ERROR    root:VerifyPersonalizationAndCapture.py:18 ❌ Error attaching screenshot to Allure: [Errno 2] No such file or directory: '/home/runner/work/QA-App-Allure/QA-App-Allure/Tests/BFV1_attempt_3.png'
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc8a7b38050>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/781838d2387b7bc6d682b2c0b1a0d84d
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc8a7b3b510>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/781838d2387b7bc6d682b2c0b1a0d84d
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc8a7b3bc10>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/781838d2387b7bc6d682b2c0b1a0d84d