ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJpdGVtQWN0aW9uIjoiVmlldyBJdGVtIiwiY2F0YWxvZyI6eyJJdGVtQ2xhc3MiOnsiX2lkIjoib3ZlcnZpZXcifX0sInVzZXIiOnsiYXR0cmlidXRlcyI6eyJnYUNsaWVudElEIjoiMzg2NDAwMjM0LjE3NDU0NDEyODIifSwiYW5vbklkIjoiNmZhMTQzYmU0OGI1NzhmOSJ9LCJzb3VyY2UiOnsidXJsIjoiaHR0cHM6Ly93d3cubWVyY2VkZXMtYmVuei5pdC9wYXNzZW5nZXJjYXJzL21vZGVscy9zdXYvZy1jbGFzcy9vdmVydmlldy5odG1sIiwidXJsUmVmZXJyZXIiOiIiLCJjaGFubmVsIjoiV2ViIiwiYmVhY29uVmVyc2lvbiI6MTYsImNvbmZpZ1ZlcnNpb24iOiI2MyIsImNvbnRlbnRab25lcyI6W119LCJjb25zZW50cyI6W10sImFjY291bnQiOnt9LCJfdG9vbHNFdmVudExpbmtJZCI6IjA0NTE3NTkyODcyMjQwMzM5IiwiZGVidWciOnsiZXhwbGFuYXRpb25zIjp0cnVlfX0%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x557bdf5d8cea <unknown>
#1 0x557bdf0895f0 <unknown>
#2 0x557bdf06fe86 <unknown>
#3 0x557bdf06e79a <unknown>
#4 0x557bdf06eeff <unknown>
#5 0x557bdf06ee54 <unknown>
#6 0x557bdf08d7ff <unknown>
#7 0x557bdf1329aa <unknown>
#8 0x557bdf100662 <unknown>
#9 0x557bdf126660 <unknown>
#10 0x557bdf100433 <unknown>
#11 0x557bdf0ccea3 <unknown>
#12 0x557bdf0cdb01 <unknown>
#13 0x557bdf59db3b <unknown>
#14 0x557bdf5a1a21 <unknown>
#15 0x557bdf584c32 <unknown>
#16 0x557bdf5a2594 <unknown>
#17 0x557bdf568eef <unknown>
#18 0x557bdf5c6d98 <unknown>
#19 0x557bdf5c6f76 <unknown>
#20 0x557bdf5d7b36 <unknown>
#21 0x7fbebfa9caa4 <unknown>
#22 0x7fbebfb29c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJhY3Rpb24iOiJQcm9kdWN0IEluZm9ybWF0aW9uIFBhZ2UgLSBvdmVydmlldyA0NjUyIiwiaXRlbUFjdGlvbiI6IlZpZXcgSXRlbSIsInNvdXJjZSI6eyJwYWdlVHlwZSI6InByb2R1Y3RfaW5mb3JtYXRpb24iLCJsb2NhbGUiOiJpdF9JVCIsImNvbnRlbnRab25lcyI6WyJnbG9iYWxfUElfTkwiLCJwaV9iYW5uZXJfTkwiLCJlcXMtc3BlY2lhbF9OTCJdLCJ1cmwiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56Lml0L3Bhc3NlbmdlcmNhcnMvbW9kZWxzL3N1di9nLWNsYXNzL292ZXJ2aWV3Lmh0bWwiLCJ1cmxSZWZlcnJlciI6IiIsImNoYW5uZWwiOiJXZWIiLCJiZWFjb25WZXJzaW9uIjoxNiwiY29uZmlnVmVyc2lvbiI6IjYzIn0sImZsYWdzIjp7InBhZ2VWaWV3Ijp0cnVlfSwidXNlciI6eyJhdHRyaWJ1dGVzIjp7ImdhQ2xpZW50SUQiOiIzODY0MDAyMzQuMTc0NTQ0MTI4MiJ9LCJhbm9uSWQiOiI2ZmExNDNiZTQ4YjU3OGY5In0sInBlcmZvcm1hbmNlIjp7InNka1BhcnNlVGltZSI6MX0sImRlYnVnIjp7ImV4cGxhbmF0aW9ucyI6dHJ1ZX0sImNhdGFsb2ciOnsiUHJvZHVjdCI6eyJfaWQiOiI0NjUyIiwiZGltZW5zaW9ucyI6eyJCYXVtdXN0ZXJTaG9ydCI6WyI0NjUyIl19fX0sImNvbnNlbnRzIjpbXSwiYWNjb3VudCI6e30sIl90b29sc0V2ZW50TGlua0lkIjoiMTkwODU3MzA1MzA1Mjg5MjIifQ%3D%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x557bdf5d8cea <unknown>
#1 0x557bdf0895f0 <unknown>
#2 0x557bdf06fe86 <unknown>
#3 0x557bdf06e79a <unknown>
#4 0x557bdf06eeff <unknown>
#5 0x557bdf06ee54 <unknown>
#6 0x557bdf08d7ff <unknown>
#7 0x557bdf1329aa <unknown>
#8 0x557bdf100662 <unknown>
#9 0x557bdf126660 <unknown>
#10 0x557bdf100433 <unknown>
#11 0x557bdf0ccea3 <unknown>
#12 0x557bdf0cdb01 <unknown>
#13 0x557bdf59db3b <unknown>
#14 0x557bdf5a1a21 <unknown>
#15 0x557bdf584c32 <unknown>
#16 0x557bdf5a2594 <unknown>
#17 0x557bdf568eef <unknown>
#18 0x557bdf5c6d98 <unknown>
#19 0x557bdf5c6f76 <unknown>
#20 0x557bdf5d7b36 <unknown>
#21 0x7fbebfa9caa4 <unknown>
#22 0x7fbebfb29c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJhY3Rpb24iOiJWaXNpdGVkIC0gb3ZlcnZpZXciLCJ1c2VyIjp7ImF0dHJpYnV0ZXMiOnsiZ2FDbGllbnRJRCI6IjM4NjQwMDIzNC4xNzQ1NDQxMjgyIn0sImFub25JZCI6IjZmYTE0M2JlNDhiNTc4ZjkifSwic291cmNlIjp7InVybCI6Imh0dHBzOi8vd3d3Lm1lcmNlZGVzLWJlbnouaXQvcGFzc2VuZ2VyY2Fycy9tb2RlbHMvc3V2L2ctY2xhc3Mvb3ZlcnZpZXcuaHRtbCIsInVybFJlZmVycmVyIjoiIiwiY2hhbm5lbCI6IldlYiIsImJlYWNvblZlcnNpb24iOjE2LCJjb25maWdWZXJzaW9uIjoiNjMiLCJjb250ZW50Wm9uZXMiOltdfSwiY29uc2VudHMiOltdLCJhY2NvdW50Ijp7fSwicGVyZm9ybWFuY2UiOnsic2RrUGFyc2VUaW1lIjoxfSwiX3Rvb2xzRXZlbnRMaW5rSWQiOiIxODEwMDAwNTIzMjIzMzg4NCIsImRlYnVnIjp7ImV4cGxhbmF0aW9ucyI6dHJ1ZX19: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x557bdf5d8cea <unknown>
#1 0x557bdf0895f0 <unknown>
#2 0x557bdf06fe86 <unknown>
#3 0x557bdf06e79a <unknown>
#4 0x557bdf06eeff <unknown>
#5 0x557bdf06ee54 <unknown>
#6 0x557bdf08d7ff <unknown>
#7 0x557bdf1329aa <unknown>
#8 0x557bdf100662 <unknown>
#9 0x557bdf126660 <unknown>
#10 0x557bdf100433 <unknown>
#11 0x557bdf0ccea3 <unknown>
#12 0x557bdf0cdb01 <unknown>
#13 0x557bdf59db3b <unknown>
#14 0x557bdf5a1a21 <unknown>
#15 0x557bdf584c32 <unknown>
#16 0x557bdf5a2594 <unknown>
#17 0x557bdf568eef <unknown>
#18 0x557bdf5c6d98 <unknown>
#19 0x557bdf5c6f76 <unknown>
#20 0x557bdf5d7b36 <unknown>
#21 0x7fbebfa9caa4 <unknown>
#22 0x7fbebfb29c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJhY3Rpb24iOiJzZXRfdXNlcl9hdHRyaWJ1dGUiLCJhY2NvdW50Ijp7ImF0dHJpYnV0ZXMiOnsibGFzdFBpUGFnZSI6eyJ2ZWhpY2xlUEkiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56Lml0L3Bhc3NlbmdlcmNhcnMvbW9kZWxzL3N1di9nLWNsYXNzL292ZXJ2aWV3Lmh0bWwiLCJ2ZWhpY2xlQ29kZSI6Inc0NjUiLCJ2ZWhpY2xlQk0iOiI0NjUyIiwidmVoaWNsZVBJSGlzdG9yeSI6IjQ2NTIiLCJ0aW1lc3RhbXAiOjE3NDU0NDEyODYwNzcsImV4cGlyYXRpb24iOjEyMH19fSwidXNlciI6eyJhdHRyaWJ1dGVzIjp7ImdhQ2xpZW50SUQiOiIzODY0MDAyMzQuMTc0NTQ0MTI4MiJ9LCJhbm9uSWQiOiI2ZmExNDNiZTQ4YjU3OGY5In0sInNvdXJjZSI6eyJ1cmwiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56Lml0L3Bhc3NlbmdlcmNhcnMvbW9kZWxzL3N1di9nLWNsYXNzL292ZXJ2aWV3Lmh0bWwiLCJ1cmxSZWZlcnJlciI6IiIsImNoYW5uZWwiOiJXZWIiLCJiZWFjb25WZXJzaW9uIjoxNiwiY29uZmlnVmVyc2lvbiI6IjYzIiwiY29udGVudFpvbmVzIjpbXX0sImNvbnNlbnRzIjpbXSwiX3Rvb2xzRXZlbnRMaW5rSWQiOiI2OTY3NzIyNTk1MTA3NjY2IiwiZGVidWciOnsiZXhwbGFuYXRpb25zIjp0cnVlfX0%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x557bdf5d8cea <unknown>
#1 0x557bdf0895f0 <unknown>
#2 0x557bdf06fe86 <unknown>
#3 0x557bdf06e79a <unknown>
#4 0x557bdf06eeff <unknown>
#5 0x557bdf06ee54 <unknown>
#6 0x557bdf08d7ff <unknown>
#7 0x557bdf1329aa <unknown>
#8 0x557bdf100662 <unknown>
#9 0x557bdf126660 <unknown>
#10 0x557bdf100433 <unknown>
#11 0x557bdf0ccea3 <unknown>
#12 0x557bdf0cdb01 <unknown>
#13 0x557bdf59db3b <unknown>
#14 0x557bdf5a1a21 <unknown>
#15 0x557bdf584c32 <unknown>
#16 0x557bdf5a2594 <unknown>
#17 0x557bdf568eef <unknown>
#18 0x557bdf5c6d98 <unknown>
#19 0x557bdf5c6f76 <unknown>
#20 0x557bdf5d7b36 <unknown>
#21 0x7fbebfa9caa4 <unknown>
#22 0x7fbebfb29c3c <unknown>

ERROR    root:VerifyPersonalizationAndCapture.py:18 ‚ùå Error attaching screenshot to Allure: [Errno 2] No such file or directory: '/home/runner/work/QA-App-Allure/QA-App-Allure/Tests/BFV1_attempt_1.png'