ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJpdGVtQWN0aW9uIjoiVmlldyBJdGVtIiwiY2F0YWxvZyI6eyJJdGVtQ2xhc3MiOnsiX2lkIjoib3ZlcnZpZXcifX0sInVzZXIiOnsiYXR0cmlidXRlcyI6eyJnYUNsaWVudElEIjoiMTczMzU4MDQzNS4xNzQ1NDQwOTAwIn0sImFub25JZCI6IjcyZDRmYWNmYzU0MzhjYWMifSwic291cmNlIjp7InVybCI6Imh0dHBzOi8vd3d3Lm1lcmNlZGVzLWJlbnouaXQvcGFzc2VuZ2VyY2Fycy9tb2RlbHMvc3V2L2VxZS9vdmVydmlldy5odG1sIiwidXJsUmVmZXJyZXIiOiIiLCJjaGFubmVsIjoiV2ViIiwiYmVhY29uVmVyc2lvbiI6MTYsImNvbmZpZ1ZlcnNpb24iOiI2MyIsImNvbnRlbnRab25lcyI6W119LCJjb25zZW50cyI6W10sImFjY291bnQiOnt9LCJfdG9vbHNFdmVudExpbmtJZCI6IjMzMzU2NzAzMDY2MzMwNzczIiwiZGVidWciOnsiZXhwbGFuYXRpb25zIjp0cnVlfX0%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x56378a82ecea <unknown>
#1 0x56378a2df5f0 <unknown>
#2 0x56378a2c5e86 <unknown>
#3 0x56378a2c479a <unknown>
#4 0x56378a2c4eff <unknown>
#5 0x56378a2c4e54 <unknown>
#6 0x56378a2e37ff <unknown>
#7 0x56378a3889aa <unknown>
#8 0x56378a356662 <unknown>
#9 0x56378a37c660 <unknown>
#10 0x56378a356433 <unknown>
#11 0x56378a322ea3 <unknown>
#12 0x56378a323b01 <unknown>
#13 0x56378a7f3b3b <unknown>
#14 0x56378a7f7a21 <unknown>
#15 0x56378a7dac32 <unknown>
#16 0x56378a7f8594 <unknown>
#17 0x56378a7beeef <unknown>
#18 0x56378a81cd98 <unknown>
#19 0x56378a81cf76 <unknown>
#20 0x56378a82db36 <unknown>
#21 0x7ff42a49caa4 <unknown>
#22 0x7ff42a529c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJhY3Rpb24iOiJQcm9kdWN0IEluZm9ybWF0aW9uIFBhZ2UgLSBvdmVydmlldyAyOTQ2IiwiaXRlbUFjdGlvbiI6IlZpZXcgSXRlbSIsInNvdXJjZSI6eyJwYWdlVHlwZSI6InByb2R1Y3RfaW5mb3JtYXRpb24iLCJsb2NhbGUiOiJpdF9JVCIsImNvbnRlbnRab25lcyI6WyJnbG9iYWxfUElfTkwiLCJwaV9iYW5uZXJfTkwiLCJlcXMtc3BlY2lhbF9OTCJdLCJ1cmwiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56Lml0L3Bhc3NlbmdlcmNhcnMvbW9kZWxzL3N1di9lcWUvb3ZlcnZpZXcuaHRtbCIsInVybFJlZmVycmVyIjoiIiwiY2hhbm5lbCI6IldlYiIsImJlYWNvblZlcnNpb24iOjE2LCJjb25maWdWZXJzaW9uIjoiNjMifSwiZmxhZ3MiOnsicGFnZVZpZXciOnRydWV9LCJ1c2VyIjp7ImF0dHJpYnV0ZXMiOnsiZ2FDbGllbnRJRCI6IjE3MzM1ODA0MzUuMTc0NTQ0MDkwMCJ9LCJhbm9uSWQiOiI3MmQ0ZmFjZmM1NDM4Y2FjIn0sInBlcmZvcm1hbmNlIjp7InNka1BhcnNlVGltZSI6MX0sImRlYnVnIjp7ImV4cGxhbmF0aW9ucyI6dHJ1ZX0sImNhdGFsb2ciOnsiUHJvZHVjdCI6eyJfaWQiOiIyOTQ2IiwiZGltZW5zaW9ucyI6eyJCYXVtdXN0ZXJTaG9ydCI6WyIyOTQ2Il19fX0sImNvbnNlbnRzIjpbXSwiYWNjb3VudCI6e30sIl90b29sc0V2ZW50TGlua0lkIjoiMjY1MDY2NTg2ODAyNDQ4In0%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x56378a82ecea <unknown>
#1 0x56378a2df5f0 <unknown>
#2 0x56378a2c5e86 <unknown>
#3 0x56378a2c479a <unknown>
#4 0x56378a2c4eff <unknown>
#5 0x56378a2c4e54 <unknown>
#6 0x56378a2e37ff <unknown>
#7 0x56378a3889aa <unknown>
#8 0x56378a356662 <unknown>
#9 0x56378a37c660 <unknown>
#10 0x56378a356433 <unknown>
#11 0x56378a322ea3 <unknown>
#12 0x56378a323b01 <unknown>
#13 0x56378a7f3b3b <unknown>
#14 0x56378a7f7a21 <unknown>
#15 0x56378a7dac32 <unknown>
#16 0x56378a7f8594 <unknown>
#17 0x56378a7beeef <unknown>
#18 0x56378a81cd98 <unknown>
#19 0x56378a81cf76 <unknown>
#20 0x56378a82db36 <unknown>
#21 0x7ff42a49caa4 <unknown>
#22 0x7ff42a529c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJhY3Rpb24iOiJWaXNpdGVkIC0gb3ZlcnZpZXciLCJ1c2VyIjp7ImF0dHJpYnV0ZXMiOnsiZ2FDbGllbnRJRCI6IjE3MzM1ODA0MzUuMTc0NTQ0MDkwMCJ9LCJhbm9uSWQiOiI3MmQ0ZmFjZmM1NDM4Y2FjIn0sInNvdXJjZSI6eyJ1cmwiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56Lml0L3Bhc3NlbmdlcmNhcnMvbW9kZWxzL3N1di9lcWUvb3ZlcnZpZXcuaHRtbCIsInVybFJlZmVycmVyIjoiIiwiY2hhbm5lbCI6IldlYiIsImJlYWNvblZlcnNpb24iOjE2LCJjb25maWdWZXJzaW9uIjoiNjMiLCJjb250ZW50Wm9uZXMiOltdfSwiY29uc2VudHMiOltdLCJhY2NvdW50Ijp7fSwicGVyZm9ybWFuY2UiOnsic2RrUGFyc2VUaW1lIjoxfSwiX3Rvb2xzRXZlbnRMaW5rSWQiOiIwOTQwMzg5NzAxNTIyMjc2MiIsImRlYnVnIjp7ImV4cGxhbmF0aW9ucyI6dHJ1ZX19: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x56378a82ecea <unknown>
#1 0x56378a2df5f0 <unknown>
#2 0x56378a2c5e86 <unknown>
#3 0x56378a2c479a <unknown>
#4 0x56378a2c4eff <unknown>
#5 0x56378a2c4e54 <unknown>
#6 0x56378a2e37ff <unknown>
#7 0x56378a3889aa <unknown>
#8 0x56378a356662 <unknown>
#9 0x56378a37c660 <unknown>
#10 0x56378a356433 <unknown>
#11 0x56378a322ea3 <unknown>
#12 0x56378a323b01 <unknown>
#13 0x56378a7f3b3b <unknown>
#14 0x56378a7f7a21 <unknown>
#15 0x56378a7dac32 <unknown>
#16 0x56378a7f8594 <unknown>
#17 0x56378a7beeef <unknown>
#18 0x56378a81cd98 <unknown>
#19 0x56378a81cf76 <unknown>
#20 0x56378a82db36 <unknown>
#21 0x7ff42a49caa4 <unknown>
#22 0x7ff42a529c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJhY3Rpb24iOiJzZXRfdXNlcl9hdHRyaWJ1dGUiLCJhY2NvdW50Ijp7ImF0dHJpYnV0ZXMiOnsibGFzdFBpUGFnZSI6eyJ2ZWhpY2xlUEkiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56Lml0L3Bhc3NlbmdlcmNhcnMvbW9kZWxzL3N1di9lcWUvb3ZlcnZpZXcuaHRtbCIsInZlaGljbGVDb2RlIjoieDI5NCIsInZlaGljbGVCTSI6IjI5NDYiLCJ2ZWhpY2xlUElIaXN0b3J5IjoiMjk0NiIsInRpbWVzdGFtcCI6MTc0NTQ0MDkwMzkxNCwiZXhwaXJhdGlvbiI6MTIwfX19LCJ1c2VyIjp7ImF0dHJpYnV0ZXMiOnsiZ2FDbGllbnRJRCI6IjE3MzM1ODA0MzUuMTc0NTQ0MDkwMCJ9LCJhbm9uSWQiOiI3MmQ0ZmFjZmM1NDM4Y2FjIn0sInNvdXJjZSI6eyJ1cmwiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56Lml0L3Bhc3NlbmdlcmNhcnMvbW9kZWxzL3N1di9lcWUvb3ZlcnZpZXcuaHRtbCIsInVybFJlZmVycmVyIjoiIiwiY2hhbm5lbCI6IldlYiIsImJlYWNvblZlcnNpb24iOjE2LCJjb25maWdWZXJzaW9uIjoiNjMiLCJjb250ZW50Wm9uZXMiOltdfSwiY29uc2VudHMiOltdLCJfdG9vbHNFdmVudExpbmtJZCI6IjkwNDczOTUwMTg0NTkzODgiLCJkZWJ1ZyI6eyJleHBsYW5hdGlvbnMiOnRydWV9fQ%3D%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x56378a82ecea <unknown>
#1 0x56378a2df5f0 <unknown>
#2 0x56378a2c5e86 <unknown>
#3 0x56378a2c479a <unknown>
#4 0x56378a2c4eff <unknown>
#5 0x56378a2c4e54 <unknown>
#6 0x56378a2e37ff <unknown>
#7 0x56378a3889aa <unknown>
#8 0x56378a356662 <unknown>
#9 0x56378a37c660 <unknown>
#10 0x56378a356433 <unknown>
#11 0x56378a322ea3 <unknown>
#12 0x56378a323b01 <unknown>
#13 0x56378a7f3b3b <unknown>
#14 0x56378a7f7a21 <unknown>
#15 0x56378a7dac32 <unknown>
#16 0x56378a7f8594 <unknown>
#17 0x56378a7beeef <unknown>
#18 0x56378a81cd98 <unknown>
#19 0x56378a81cf76 <unknown>
#20 0x56378a82db36 <unknown>
#21 0x7ff42a49caa4 <unknown>
#22 0x7ff42a529c3c <unknown>

ERROR    root:VerifyPersonalizationAndCapture.py:18 ‚ùå Error attaching screenshot to Allure: [Errno 2] No such file or directory: '/home/runner/work/QA-App-Allure/QA-App-Allure/Tests/BFV1_attempt_1.png'