ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJhY3Rpb24iOiJQcm9kdWN0IEluZm9ybWF0aW9uIFBhZ2UgLSBvdmVydmlldyAyOTY2IiwiaXRlbUFjdGlvbiI6IlZpZXcgSXRlbSIsInNvdXJjZSI6eyJwYWdlVHlwZSI6InByb2R1Y3RfaW5mb3JtYXRpb24iLCJsb2NhbGUiOiJpdF9JVCIsImNvbnRlbnRab25lcyI6WyJnbG9iYWxfUElfTkwiLCJwaV9iYW5uZXJfTkwiLCJlcXMtc3BlY2lhbF9OTCJdLCJ1cmwiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56Lml0L3Bhc3NlbmdlcmNhcnMvbW9kZWxzL3N1di9lcXMvb3ZlcnZpZXcuaHRtbCIsInVybFJlZmVycmVyIjoiIiwiY2hhbm5lbCI6IldlYiIsImJlYWNvblZlcnNpb24iOjE2LCJjb25maWdWZXJzaW9uIjoiNjMifSwiZmxhZ3MiOnsicGFnZVZpZXciOnRydWV9LCJ1c2VyIjp7ImF0dHJpYnV0ZXMiOnsiZ2FDbGllbnRJRCI6IjU5MjcxMDA2NS4xNzQ1NDQ5NjgxIn0sImFub25JZCI6IjVkZWM5Mzg3YmRiNWFlMjUifSwicGVyZm9ybWFuY2UiOnsic2RrUGFyc2VUaW1lIjo0fSwiZGVidWciOnsiZXhwbGFuYXRpb25zIjp0cnVlfSwiY2F0YWxvZyI6eyJQcm9kdWN0Ijp7Il9pZCI6IjI5NjYiLCJkaW1lbnNpb25zIjp7IkJhdW11c3RlclNob3J0IjpbIjI5NjYiXX19fSwiY29uc2VudHMiOltdLCJhY2NvdW50Ijp7fSwiX3Rvb2xzRXZlbnRMaW5rSWQiOiI3MDIyMzkwNDU2OTk1NTc1In0%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x55c3958edcea <unknown>
#1 0x55c39539e5f0 <unknown>
#2 0x55c395384e86 <unknown>
#3 0x55c39538379a <unknown>
#4 0x55c395383eff <unknown>
#5 0x55c395383e54 <unknown>
#6 0x55c3953a27ff <unknown>
#7 0x55c3954479aa <unknown>
#8 0x55c395415662 <unknown>
#9 0x55c39543b660 <unknown>
#10 0x55c395415433 <unknown>
#11 0x55c3953e1ea3 <unknown>
#12 0x55c3953e2b01 <unknown>
#13 0x55c3958b2b3b <unknown>
#14 0x55c3958b6a21 <unknown>
#15 0x55c395899c32 <unknown>
#16 0x55c3958b7594 <unknown>
#17 0x55c39587deef <unknown>
#18 0x55c3958dbd98 <unknown>
#19 0x55c3958dbf76 <unknown>
#20 0x55c3958ecb36 <unknown>
#21 0x7f89de09caa4 <unknown>
#22 0x7f89de129c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJhY3Rpb24iOiJWaXNpdGVkIC0gb3ZlcnZpZXciLCJ1c2VyIjp7ImF0dHJpYnV0ZXMiOnsiZ2FDbGllbnRJRCI6IjU5MjcxMDA2NS4xNzQ1NDQ5NjgxIn0sImFub25JZCI6IjVkZWM5Mzg3YmRiNWFlMjUifSwic291cmNlIjp7InVybCI6Imh0dHBzOi8vd3d3Lm1lcmNlZGVzLWJlbnouaXQvcGFzc2VuZ2VyY2Fycy9tb2RlbHMvc3V2L2Vxcy9vdmVydmlldy5odG1sIiwidXJsUmVmZXJyZXIiOiIiLCJjaGFubmVsIjoiV2ViIiwiYmVhY29uVmVyc2lvbiI6MTYsImNvbmZpZ1ZlcnNpb24iOiI2MyIsImNvbnRlbnRab25lcyI6W119LCJjb25zZW50cyI6W10sImFjY291bnQiOnt9LCJwZXJmb3JtYW5jZSI6eyJzZGtQYXJzZVRpbWUiOjR9LCJfdG9vbHNFdmVudExpbmtJZCI6Ijg4MDIzMzE2MjYzMzgwMDYiLCJkZWJ1ZyI6eyJleHBsYW5hdGlvbnMiOnRydWV9fQ%3D%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x55c3958edcea <unknown>
#1 0x55c39539e5f0 <unknown>
#2 0x55c395384e86 <unknown>
#3 0x55c39538379a <unknown>
#4 0x55c395383eff <unknown>
#5 0x55c395383e54 <unknown>
#6 0x55c3953a27ff <unknown>
#7 0x55c3954479aa <unknown>
#8 0x55c395415662 <unknown>
#9 0x55c39543b660 <unknown>
#10 0x55c395415433 <unknown>
#11 0x55c3953e1ea3 <unknown>
#12 0x55c3953e2b01 <unknown>
#13 0x55c3958b2b3b <unknown>
#14 0x55c3958b6a21 <unknown>
#15 0x55c395899c32 <unknown>
#16 0x55c3958b7594 <unknown>
#17 0x55c39587deef <unknown>
#18 0x55c3958dbd98 <unknown>
#19 0x55c3958dbf76 <unknown>
#20 0x55c3958ecb36 <unknown>
#21 0x7f89de09caa4 <unknown>
#22 0x7f89de129c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJpdGVtQWN0aW9uIjoiVmlldyBJdGVtIiwiY2F0YWxvZyI6eyJJdGVtQ2xhc3MiOnsiX2lkIjoib3ZlcnZpZXcifX0sInVzZXIiOnsiYXR0cmlidXRlcyI6eyJnYUNsaWVudElEIjoiNTkyNzEwMDY1LjE3NDU0NDk2ODEifSwiYW5vbklkIjoiNWRlYzkzODdiZGI1YWUyNSJ9LCJzb3VyY2UiOnsidXJsIjoiaHR0cHM6Ly93d3cubWVyY2VkZXMtYmVuei5pdC9wYXNzZW5nZXJjYXJzL21vZGVscy9zdXYvZXFzL292ZXJ2aWV3Lmh0bWwiLCJ1cmxSZWZlcnJlciI6IiIsImNoYW5uZWwiOiJXZWIiLCJiZWFjb25WZXJzaW9uIjoxNiwiY29uZmlnVmVyc2lvbiI6IjYzIiwiY29udGVudFpvbmVzIjpbXX0sImNvbnNlbnRzIjpbXSwiYWNjb3VudCI6e30sIl90b29sc0V2ZW50TGlua0lkIjoiNjMxODA0OTk0NjU5MDgyMSIsImRlYnVnIjp7ImV4cGxhbmF0aW9ucyI6dHJ1ZX19: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x55c3958edcea <unknown>
#1 0x55c39539e5f0 <unknown>
#2 0x55c395384e86 <unknown>
#3 0x55c39538379a <unknown>
#4 0x55c395383eff <unknown>
#5 0x55c395383e54 <unknown>
#6 0x55c3953a27ff <unknown>
#7 0x55c3954479aa <unknown>
#8 0x55c395415662 <unknown>
#9 0x55c39543b660 <unknown>
#10 0x55c395415433 <unknown>
#11 0x55c3953e1ea3 <unknown>
#12 0x55c3953e2b01 <unknown>
#13 0x55c3958b2b3b <unknown>
#14 0x55c3958b6a21 <unknown>
#15 0x55c395899c32 <unknown>
#16 0x55c3958b7594 <unknown>
#17 0x55c39587deef <unknown>
#18 0x55c3958dbd98 <unknown>
#19 0x55c3958dbf76 <unknown>
#20 0x55c3958ecb36 <unknown>
#21 0x7f89de09caa4 <unknown>
#22 0x7f89de129c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJhY3Rpb24iOiJzZXRfdXNlcl9hdHRyaWJ1dGUiLCJhY2NvdW50Ijp7ImF0dHJpYnV0ZXMiOnsibGFzdFBpUGFnZSI6eyJ2ZWhpY2xlUEkiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56Lml0L3Bhc3NlbmdlcmNhcnMvbW9kZWxzL3N1di9lcXMvb3ZlcnZpZXcuaHRtbCIsInZlaGljbGVDb2RlIjoieDI5NiIsInZlaGljbGVCTSI6IjI5NjYiLCJ2ZWhpY2xlUElIaXN0b3J5IjoiMjk2NiIsInRpbWVzdGFtcCI6MTc0NTQ0OTY4OTA3NywiZXhwaXJhdGlvbiI6MTIwfX19LCJ1c2VyIjp7ImF0dHJpYnV0ZXMiOnsiZ2FDbGllbnRJRCI6IjU5MjcxMDA2NS4xNzQ1NDQ5NjgxIn0sImFub25JZCI6IjVkZWM5Mzg3YmRiNWFlMjUifSwic291cmNlIjp7InVybCI6Imh0dHBzOi8vd3d3Lm1lcmNlZGVzLWJlbnouaXQvcGFzc2VuZ2VyY2Fycy9tb2RlbHMvc3V2L2Vxcy9vdmVydmlldy5odG1sIiwidXJsUmVmZXJyZXIiOiIiLCJjaGFubmVsIjoiV2ViIiwiYmVhY29uVmVyc2lvbiI6MTYsImNvbmZpZ1ZlcnNpb24iOiI2MyIsImNvbnRlbnRab25lcyI6W119LCJjb25zZW50cyI6W10sIl90b29sc0V2ZW50TGlua0lkIjoiMDQ0OTA2MjM0NzQzODkyMTA0IiwiZGVidWciOnsiZXhwbGFuYXRpb25zIjp0cnVlfX0%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x55c3958edcea <unknown>
#1 0x55c39539e5f0 <unknown>
#2 0x55c395384e86 <unknown>
#3 0x55c39538379a <unknown>
#4 0x55c395383eff <unknown>
#5 0x55c395383e54 <unknown>
#6 0x55c3953a27ff <unknown>
#7 0x55c3954479aa <unknown>
#8 0x55c395415662 <unknown>
#9 0x55c39543b660 <unknown>
#10 0x55c395415433 <unknown>
#11 0x55c3953e1ea3 <unknown>
#12 0x55c3953e2b01 <unknown>
#13 0x55c3958b2b3b <unknown>
#14 0x55c3958b6a21 <unknown>
#15 0x55c395899c32 <unknown>
#16 0x55c3958b7594 <unknown>
#17 0x55c39587deef <unknown>
#18 0x55c3958dbd98 <unknown>
#19 0x55c3958dbf76 <unknown>
#20 0x55c3958ecb36 <unknown>
#21 0x7f89de09caa4 <unknown>
#22 0x7f89de129c3c <unknown>

ERROR    root:VerifyPersonalizationAndCapture.py:111 ❌ Image not found in the specified selector. Error: Message: 

ERROR    root:VerifyPersonalizationAndCapture.py:18 ❌ Error attaching screenshot to Allure: [Errno 2] No such file or directory: '/home/runner/work/QA-App-Allure/QA-App-Allure/Tests/BFV1_attempt_1.png'
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f47a02d4050>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5a5bda56ba4493838da14c2c7c3afcba
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f47a02d49d0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5a5bda56ba4493838da14c2c7c3afcba
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f47a02d6a10>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5a5bda56ba4493838da14c2c7c3afcba
ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJpdGVtQWN0aW9uIjoiVmlldyBJdGVtIiwiY2F0YWxvZyI6eyJJdGVtQ2xhc3MiOnsiX2lkIjoib3ZlcnZpZXcifX0sInVzZXIiOnsiYXR0cmlidXRlcyI6eyJnYUNsaWVudElEIjoiNjI4MDg0MTg2LjE3NDU0NDk3MjMifSwiYW5vbklkIjoiY2YwODVhMmFmMTkzNDIzMyJ9LCJzb3VyY2UiOnsidXJsIjoiaHR0cHM6Ly93d3cubWVyY2VkZXMtYmVuei5pdC9wYXNzZW5nZXJjYXJzL21vZGVscy9zdXYvZXFzL292ZXJ2aWV3Lmh0bWwiLCJ1cmxSZWZlcnJlciI6IiIsImNoYW5uZWwiOiJXZWIiLCJiZWFjb25WZXJzaW9uIjoxNiwiY29uZmlnVmVyc2lvbiI6IjYzIiwiY29udGVudFpvbmVzIjpbXX0sImNvbnNlbnRzIjpbXSwiYWNjb3VudCI6e30sIl90b29sc0V2ZW50TGlua0lkIjoiMTYyODUxNjM5OTI4NTQxMTMiLCJkZWJ1ZyI6eyJleHBsYW5hdGlvbnMiOnRydWV9fQ%3D%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x55bb783d2cea <unknown>
#1 0x55bb77e835f0 <unknown>
#2 0x55bb77e69e86 <unknown>
#3 0x55bb77e6879a <unknown>
#4 0x55bb77e68eff <unknown>
#5 0x55bb77e68e54 <unknown>
#6 0x55bb77e877ff <unknown>
#7 0x55bb77f2c9aa <unknown>
#8 0x55bb77efa662 <unknown>
#9 0x55bb77f20660 <unknown>
#10 0x55bb77efa433 <unknown>
#11 0x55bb77ec6ea3 <unknown>
#12 0x55bb77ec7b01 <unknown>
#13 0x55bb78397b3b <unknown>
#14 0x55bb7839ba21 <unknown>
#15 0x55bb7837ec32 <unknown>
#16 0x55bb7839c594 <unknown>
#17 0x55bb78362eef <unknown>
#18 0x55bb783c0d98 <unknown>
#19 0x55bb783c0f76 <unknown>
#20 0x55bb783d1b36 <unknown>
#21 0x7fae2fa9caa4 <unknown>
#22 0x7fae2fb29c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJhY3Rpb24iOiJQcm9kdWN0IEluZm9ybWF0aW9uIFBhZ2UgLSBvdmVydmlldyAyOTY2IiwiaXRlbUFjdGlvbiI6IlZpZXcgSXRlbSIsInNvdXJjZSI6eyJwYWdlVHlwZSI6InByb2R1Y3RfaW5mb3JtYXRpb24iLCJsb2NhbGUiOiJpdF9JVCIsImNvbnRlbnRab25lcyI6WyJnbG9iYWxfUElfTkwiLCJwaV9iYW5uZXJfTkwiLCJlcXMtc3BlY2lhbF9OTCJdLCJ1cmwiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56Lml0L3Bhc3NlbmdlcmNhcnMvbW9kZWxzL3N1di9lcXMvb3ZlcnZpZXcuaHRtbCIsInVybFJlZmVycmVyIjoiIiwiY2hhbm5lbCI6IldlYiIsImJlYWNvblZlcnNpb24iOjE2LCJjb25maWdWZXJzaW9uIjoiNjMifSwiZmxhZ3MiOnsicGFnZVZpZXciOnRydWV9LCJ1c2VyIjp7ImF0dHJpYnV0ZXMiOnsiZ2FDbGllbnRJRCI6IjYyODA4NDE4Ni4xNzQ1NDQ5NzIzIn0sImFub25JZCI6ImNmMDg1YTJhZjE5MzQyMzMifSwicGVyZm9ybWFuY2UiOnsic2RrUGFyc2VUaW1lIjoxfSwiZGVidWciOnsiZXhwbGFuYXRpb25zIjp0cnVlfSwiY2F0YWxvZyI6eyJQcm9kdWN0Ijp7Il9pZCI6IjI5NjYiLCJkaW1lbnNpb25zIjp7IkJhdW11c3RlclNob3J0IjpbIjI5NjYiXX19fSwiY29uc2VudHMiOltdLCJhY2NvdW50Ijp7fSwiX3Rvb2xzRXZlbnRMaW5rSWQiOiIxODkwMjkyMzc0NzA0OTczOCJ9: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x55bb783d2cea <unknown>
#1 0x55bb77e835f0 <unknown>
#2 0x55bb77e69e86 <unknown>
#3 0x55bb77e6879a <unknown>
#4 0x55bb77e68eff <unknown>
#5 0x55bb77e68e54 <unknown>
#6 0x55bb77e877ff <unknown>
#7 0x55bb77f2c9aa <unknown>
#8 0x55bb77efa662 <unknown>
#9 0x55bb77f20660 <unknown>
#10 0x55bb77efa433 <unknown>
#11 0x55bb77ec6ea3 <unknown>
#12 0x55bb77ec7b01 <unknown>
#13 0x55bb78397b3b <unknown>
#14 0x55bb7839ba21 <unknown>
#15 0x55bb7837ec32 <unknown>
#16 0x55bb7839c594 <unknown>
#17 0x55bb78362eef <unknown>
#18 0x55bb783c0d98 <unknown>
#19 0x55bb783c0f76 <unknown>
#20 0x55bb783d1b36 <unknown>
#21 0x7fae2fa9caa4 <unknown>
#22 0x7fae2fb29c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJhY3Rpb24iOiJWaXNpdGVkIC0gb3ZlcnZpZXciLCJ1c2VyIjp7ImF0dHJpYnV0ZXMiOnsiZ2FDbGllbnRJRCI6IjYyODA4NDE4Ni4xNzQ1NDQ5NzIzIn0sImFub25JZCI6ImNmMDg1YTJhZjE5MzQyMzMifSwic291cmNlIjp7InVybCI6Imh0dHBzOi8vd3d3Lm1lcmNlZGVzLWJlbnouaXQvcGFzc2VuZ2VyY2Fycy9tb2RlbHMvc3V2L2Vxcy9vdmVydmlldy5odG1sIiwidXJsUmVmZXJyZXIiOiIiLCJjaGFubmVsIjoiV2ViIiwiYmVhY29uVmVyc2lvbiI6MTYsImNvbmZpZ1ZlcnNpb24iOiI2MyIsImNvbnRlbnRab25lcyI6W119LCJjb25zZW50cyI6W10sImFjY291bnQiOnt9LCJwZXJmb3JtYW5jZSI6eyJzZGtQYXJzZVRpbWUiOjF9LCJfdG9vbHNFdmVudExpbmtJZCI6IjUwMzU5MDc1MDk1MzQxNTMiLCJkZWJ1ZyI6eyJleHBsYW5hdGlvbnMiOnRydWV9fQ%3D%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x55bb783d2cea <unknown>
#1 0x55bb77e835f0 <unknown>
#2 0x55bb77e69e86 <unknown>
#3 0x55bb77e6879a <unknown>
#4 0x55bb77e68eff <unknown>
#5 0x55bb77e68e54 <unknown>
#6 0x55bb77e877ff <unknown>
#7 0x55bb77f2c9aa <unknown>
#8 0x55bb77efa662 <unknown>
#9 0x55bb77f20660 <unknown>
#10 0x55bb77efa433 <unknown>
#11 0x55bb77ec6ea3 <unknown>
#12 0x55bb77ec7b01 <unknown>
#13 0x55bb78397b3b <unknown>
#14 0x55bb7839ba21 <unknown>
#15 0x55bb7837ec32 <unknown>
#16 0x55bb7839c594 <unknown>
#17 0x55bb78362eef <unknown>
#18 0x55bb783c0d98 <unknown>
#19 0x55bb783c0f76 <unknown>
#20 0x55bb783d1b36 <unknown>
#21 0x7fae2fa9caa4 <unknown>
#22 0x7fae2fb29c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJhY3Rpb24iOiJzZXRfdXNlcl9hdHRyaWJ1dGUiLCJhY2NvdW50Ijp7ImF0dHJpYnV0ZXMiOnsibGFzdFBpUGFnZSI6eyJ2ZWhpY2xlUEkiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56Lml0L3Bhc3NlbmdlcmNhcnMvbW9kZWxzL3N1di9lcXMvb3ZlcnZpZXcuaHRtbCIsInZlaGljbGVDb2RlIjoieDI5NiIsInZlaGljbGVCTSI6IjI5NjYiLCJ2ZWhpY2xlUElIaXN0b3J5IjoiMjk2NiIsInRpbWVzdGFtcCI6MTc0NTQ0OTczNTE0MiwiZXhwaXJhdGlvbiI6MTIwfX19LCJ1c2VyIjp7ImF0dHJpYnV0ZXMiOnsiZ2FDbGllbnRJRCI6IjYyODA4NDE4Ni4xNzQ1NDQ5NzIzIn0sImFub25JZCI6ImNmMDg1YTJhZjE5MzQyMzMifSwic291cmNlIjp7InVybCI6Imh0dHBzOi8vd3d3Lm1lcmNlZGVzLWJlbnouaXQvcGFzc2VuZ2VyY2Fycy9tb2RlbHMvc3V2L2Vxcy9vdmVydmlldy5odG1sIiwidXJsUmVmZXJyZXIiOiIiLCJjaGFubmVsIjoiV2ViIiwiYmVhY29uVmVyc2lvbiI6MTYsImNvbmZpZ1ZlcnNpb24iOiI2MyIsImNvbnRlbnRab25lcyI6W119LCJjb25zZW50cyI6W10sIl90b29sc0V2ZW50TGlua0lkIjoiMjQzNTQ4ODk1MTI0MjA5ODUiLCJkZWJ1ZyI6eyJleHBsYW5hdGlvbnMiOnRydWV9fQ%3D%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x55bb783d2cea <unknown>
#1 0x55bb77e835f0 <unknown>
#2 0x55bb77e69e86 <unknown>
#3 0x55bb77e6879a <unknown>
#4 0x55bb77e68eff <unknown>
#5 0x55bb77e68e54 <unknown>
#6 0x55bb77e877ff <unknown>
#7 0x55bb77f2c9aa <unknown>
#8 0x55bb77efa662 <unknown>
#9 0x55bb77f20660 <unknown>
#10 0x55bb77efa433 <unknown>
#11 0x55bb77ec6ea3 <unknown>
#12 0x55bb77ec7b01 <unknown>
#13 0x55bb78397b3b <unknown>
#14 0x55bb7839ba21 <unknown>
#15 0x55bb7837ec32 <unknown>
#16 0x55bb7839c594 <unknown>
#17 0x55bb78362eef <unknown>
#18 0x55bb783c0d98 <unknown>
#19 0x55bb783c0f76 <unknown>
#20 0x55bb783d1b36 <unknown>
#21 0x7fae2fa9caa4 <unknown>
#22 0x7fae2fb29c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJhY3Rpb24iOiIxNSBTZWNvbmRzIG9uIFBJIFBhZ2UgLSAyOTY2IiwidXNlciI6eyJhdHRyaWJ1dGVzIjp7ImdhQ2xpZW50SUQiOiI2MjgwODQxODYuMTc0NTQ0OTcyMyJ9LCJhbm9uSWQiOiJjZjA4NWEyYWYxOTM0MjMzIn0sInNvdXJjZSI6eyJ1cmwiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56Lml0L3Bhc3NlbmdlcmNhcnMvbW9kZWxzL3N1di9lcXMvb3ZlcnZpZXcuaHRtbCIsInVybFJlZmVycmVyIjoiIiwiY2hhbm5lbCI6IldlYiIsImJlYWNvblZlcnNpb24iOjE2LCJjb25maWdWZXJzaW9uIjoiNjMiLCJjb250ZW50Wm9uZXMiOltdfSwiY29uc2VudHMiOltdLCJhY2NvdW50Ijp7fSwiX3Rvb2xzRXZlbnRMaW5rSWQiOiI5ODQ1OTkzMTYzODA1NDEiLCJkZWJ1ZyI6eyJleHBsYW5hdGlvbnMiOnRydWV9fQ%3D%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x55bb783d2cea <unknown>
#1 0x55bb77e835f0 <unknown>
#2 0x55bb77e69e86 <unknown>
#3 0x55bb77e6879a <unknown>
#4 0x55bb77e68eff <unknown>
#5 0x55bb77e68e54 <unknown>
#6 0x55bb77e877ff <unknown>
#7 0x55bb77f2c9aa <unknown>
#8 0x55bb77efa662 <unknown>
#9 0x55bb77f20660 <unknown>
#10 0x55bb77efa433 <unknown>
#11 0x55bb77ec6ea3 <unknown>
#12 0x55bb77ec7b01 <unknown>
#13 0x55bb78397b3b <unknown>
#14 0x55bb7839ba21 <unknown>
#15 0x55bb7837ec32 <unknown>
#16 0x55bb7839c594 <unknown>
#17 0x55bb78362eef <unknown>
#18 0x55bb783c0d98 <unknown>
#19 0x55bb783c0f76 <unknown>
#20 0x55bb783d1b36 <unknown>
#21 0x7fae2fa9caa4 <unknown>
#22 0x7fae2fb29c3c <unknown>

ERROR    root:VerifyPersonalizationAndCapture.py:18 ❌ Error attaching screenshot to Allure: [Errno 2] No such file or directory: '/home/runner/work/QA-App-Allure/QA-App-Allure/Tests/BFV1_attempt_2.png'
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f479a964290>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5a5bda56ba4493838da14c2c7c3afcba
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f479a964b50>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5a5bda56ba4493838da14c2c7c3afcba
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f479a967b90>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/5a5bda56ba4493838da14c2c7c3afcba