ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJpdGVtQWN0aW9uIjoiVmlldyBJdGVtIiwiY2F0YWxvZyI6eyJJdGVtQ2xhc3MiOnsiX2lkIjoib3ZlcnZpZXcifX0sInVzZXIiOnsiYXR0cmlidXRlcyI6eyJnYUNsaWVudElEIjoiOTc4NjA3NjczLjE3NDU0Mzk1MTgifSwiYW5vbklkIjoiZGFjNjM5NDMyMWNlMzBkMiJ9LCJzb3VyY2UiOnsidXJsIjoiaHR0cHM6Ly93d3cubWVyY2VkZXMtYmVuei5pdC9wYXNzZW5nZXJjYXJzL21vZGVscy9oYXRjaGJhY2svYS1jbGFzcy9vdmVydmlldy5odG1sIiwidXJsUmVmZXJyZXIiOiIiLCJjaGFubmVsIjoiV2ViIiwiYmVhY29uVmVyc2lvbiI6MTYsImNvbmZpZ1ZlcnNpb24iOiI2MyIsImNvbnRlbnRab25lcyI6W119LCJjb25zZW50cyI6W10sImFjY291bnQiOnt9LCJfdG9vbHNFdmVudExpbmtJZCI6IjIyMDIxMDcxNDk0Nzg4NzM1IiwiZGVidWciOnsiZXhwbGFuYXRpb25zIjp0cnVlfX0%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x5641d1682cea <unknown>
#1 0x5641d11335f0 <unknown>
#2 0x5641d1119e86 <unknown>
#3 0x5641d111879a <unknown>
#4 0x5641d1118eff <unknown>
#5 0x5641d1118e54 <unknown>
#6 0x5641d11377ff <unknown>
#7 0x5641d11dc9aa <unknown>
#8 0x5641d11aa662 <unknown>
#9 0x5641d11d0660 <unknown>
#10 0x5641d11aa433 <unknown>
#11 0x5641d1176ea3 <unknown>
#12 0x5641d1177b01 <unknown>
#13 0x5641d1647b3b <unknown>
#14 0x5641d164ba21 <unknown>
#15 0x5641d162ec32 <unknown>
#16 0x5641d164c594 <unknown>
#17 0x5641d1612eef <unknown>
#18 0x5641d1670d98 <unknown>
#19 0x5641d1670f76 <unknown>
#20 0x5641d1681b36 <unknown>
#21 0x7f813349caa4 <unknown>
#22 0x7f8133529c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJhY3Rpb24iOiJQcm9kdWN0IEluZm9ybWF0aW9uIFBhZ2UgLSBvdmVydmlldyAxNzcwIiwiaXRlbUFjdGlvbiI6IlZpZXcgSXRlbSIsInNvdXJjZSI6eyJwYWdlVHlwZSI6InByb2R1Y3RfaW5mb3JtYXRpb24iLCJsb2NhbGUiOiJpdF9JVCIsImNvbnRlbnRab25lcyI6WyJnbG9iYWxfUElfTkwiLCJwaV9iYW5uZXJfTkwiLCJlcXMtc3BlY2lhbF9OTCJdLCJ1cmwiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56Lml0L3Bhc3NlbmdlcmNhcnMvbW9kZWxzL2hhdGNoYmFjay9hLWNsYXNzL292ZXJ2aWV3Lmh0bWwiLCJ1cmxSZWZlcnJlciI6IiIsImNoYW5uZWwiOiJXZWIiLCJiZWFjb25WZXJzaW9uIjoxNiwiY29uZmlnVmVyc2lvbiI6IjYzIn0sImZsYWdzIjp7InBhZ2VWaWV3Ijp0cnVlfSwidXNlciI6eyJhdHRyaWJ1dGVzIjp7ImdhQ2xpZW50SUQiOiI5Nzg2MDc2NzMuMTc0NTQzOTUxOCJ9LCJhbm9uSWQiOiJkYWM2Mzk0MzIxY2UzMGQyIn0sInBlcmZvcm1hbmNlIjp7InNka1BhcnNlVGltZSI6MX0sImRlYnVnIjp7ImV4cGxhbmF0aW9ucyI6dHJ1ZX0sImNhdGFsb2ciOnsiUHJvZHVjdCI6eyJfaWQiOiIxNzcwIiwiZGltZW5zaW9ucyI6eyJCYXVtdXN0ZXJTaG9ydCI6WyIxNzcwIl19fX0sImNvbnNlbnRzIjpbXSwiYWNjb3VudCI6e30sIl90b29sc0V2ZW50TGlua0lkIjoiMDAxMDczMTgyNDUwNjc5NDQ0In0%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x5641d1682cea <unknown>
#1 0x5641d11335f0 <unknown>
#2 0x5641d1119e86 <unknown>
#3 0x5641d111879a <unknown>
#4 0x5641d1118eff <unknown>
#5 0x5641d1118e54 <unknown>
#6 0x5641d11377ff <unknown>
#7 0x5641d11dc9aa <unknown>
#8 0x5641d11aa662 <unknown>
#9 0x5641d11d0660 <unknown>
#10 0x5641d11aa433 <unknown>
#11 0x5641d1176ea3 <unknown>
#12 0x5641d1177b01 <unknown>
#13 0x5641d1647b3b <unknown>
#14 0x5641d164ba21 <unknown>
#15 0x5641d162ec32 <unknown>
#16 0x5641d164c594 <unknown>
#17 0x5641d1612eef <unknown>
#18 0x5641d1670d98 <unknown>
#19 0x5641d1670f76 <unknown>
#20 0x5641d1681b36 <unknown>
#21 0x7f813349caa4 <unknown>
#22 0x7f8133529c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJhY3Rpb24iOiJWaXNpdGVkIC0gb3ZlcnZpZXciLCJ1c2VyIjp7ImF0dHJpYnV0ZXMiOnsiZ2FDbGllbnRJRCI6Ijk3ODYwNzY3My4xNzQ1NDM5NTE4In0sImFub25JZCI6ImRhYzYzOTQzMjFjZTMwZDIifSwic291cmNlIjp7InVybCI6Imh0dHBzOi8vd3d3Lm1lcmNlZGVzLWJlbnouaXQvcGFzc2VuZ2VyY2Fycy9tb2RlbHMvaGF0Y2hiYWNrL2EtY2xhc3Mvb3ZlcnZpZXcuaHRtbCIsInVybFJlZmVycmVyIjoiIiwiY2hhbm5lbCI6IldlYiIsImJlYWNvblZlcnNpb24iOjE2LCJjb25maWdWZXJzaW9uIjoiNjMiLCJjb250ZW50Wm9uZXMiOltdfSwiY29uc2VudHMiOltdLCJhY2NvdW50Ijp7fSwicGVyZm9ybWFuY2UiOnsic2RrUGFyc2VUaW1lIjoxfSwiX3Rvb2xzRXZlbnRMaW5rSWQiOiI2ODg3MDk0NDE3MzAxMTYiLCJkZWJ1ZyI6eyJleHBsYW5hdGlvbnMiOnRydWV9fQ%3D%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x5641d1682cea <unknown>
#1 0x5641d11335f0 <unknown>
#2 0x5641d1119e86 <unknown>
#3 0x5641d111879a <unknown>
#4 0x5641d1118eff <unknown>
#5 0x5641d1118e54 <unknown>
#6 0x5641d11377ff <unknown>
#7 0x5641d11dc9aa <unknown>
#8 0x5641d11aa662 <unknown>
#9 0x5641d11d0660 <unknown>
#10 0x5641d11aa433 <unknown>
#11 0x5641d1176ea3 <unknown>
#12 0x5641d1177b01 <unknown>
#13 0x5641d1647b3b <unknown>
#14 0x5641d164ba21 <unknown>
#15 0x5641d162ec32 <unknown>
#16 0x5641d164c594 <unknown>
#17 0x5641d1612eef <unknown>
#18 0x5641d1670d98 <unknown>
#19 0x5641d1670f76 <unknown>
#20 0x5641d1681b36 <unknown>
#21 0x7f813349caa4 <unknown>
#22 0x7f8133529c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJhY3Rpb24iOiJzZXRfdXNlcl9hdHRyaWJ1dGUiLCJhY2NvdW50Ijp7ImF0dHJpYnV0ZXMiOnsibGFzdFBpUGFnZSI6eyJ2ZWhpY2xlUEkiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56Lml0L3Bhc3NlbmdlcmNhcnMvbW9kZWxzL2hhdGNoYmFjay9hLWNsYXNzL292ZXJ2aWV3Lmh0bWwiLCJ2ZWhpY2xlQ29kZSI6IncxNzctZmwiLCJ2ZWhpY2xlQk0iOiIxNzcwIiwidmVoaWNsZVBJSGlzdG9yeSI6IjE3NzAiLCJ0aW1lc3RhbXAiOjE3NDU0Mzk1MjIxNjUsImV4cGlyYXRpb24iOjEyMH19fSwidXNlciI6eyJhdHRyaWJ1dGVzIjp7ImdhQ2xpZW50SUQiOiI5Nzg2MDc2NzMuMTc0NTQzOTUxOCJ9LCJhbm9uSWQiOiJkYWM2Mzk0MzIxY2UzMGQyIn0sInNvdXJjZSI6eyJ1cmwiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56Lml0L3Bhc3NlbmdlcmNhcnMvbW9kZWxzL2hhdGNoYmFjay9hLWNsYXNzL292ZXJ2aWV3Lmh0bWwiLCJ1cmxSZWZlcnJlciI6IiIsImNoYW5uZWwiOiJXZWIiLCJiZWFjb25WZXJzaW9uIjoxNiwiY29uZmlnVmVyc2lvbiI6IjYzIiwiY29udGVudFpvbmVzIjpbXX0sImNvbnNlbnRzIjpbXSwiX3Rvb2xzRXZlbnRMaW5rSWQiOiI1MTUwODU4MTM1MzgwNDAyIiwiZGVidWciOnsiZXhwbGFuYXRpb25zIjp0cnVlfX0%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x5641d1682cea <unknown>
#1 0x5641d11335f0 <unknown>
#2 0x5641d1119e86 <unknown>
#3 0x5641d111879a <unknown>
#4 0x5641d1118eff <unknown>
#5 0x5641d1118e54 <unknown>
#6 0x5641d11377ff <unknown>
#7 0x5641d11dc9aa <unknown>
#8 0x5641d11aa662 <unknown>
#9 0x5641d11d0660 <unknown>
#10 0x5641d11aa433 <unknown>
#11 0x5641d1176ea3 <unknown>
#12 0x5641d1177b01 <unknown>
#13 0x5641d1647b3b <unknown>
#14 0x5641d164ba21 <unknown>
#15 0x5641d162ec32 <unknown>
#16 0x5641d164c594 <unknown>
#17 0x5641d1612eef <unknown>
#18 0x5641d1670d98 <unknown>
#19 0x5641d1670f76 <unknown>
#20 0x5641d1681b36 <unknown>
#21 0x7f813349caa4 <unknown>
#22 0x7f8133529c3c <unknown>

ERROR    root:VerifyPersonalizationAndCapture.py:111 ❌ Image not found in the specified selector. Error: Message: 

ERROR    root:VerifyPersonalizationAndCapture.py:18 ❌ Error attaching screenshot to Allure: [Errno 2] No such file or directory: '/home/runner/work/QA-App-Allure/QA-App-Allure/Tests/BFV1_attempt_1.png'
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f73b620d9d0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/b95c35c26abe577a9362d38dfa5db359
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f73b620cc90>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/b95c35c26abe577a9362d38dfa5db359
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f73b620c8d0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/b95c35c26abe577a9362d38dfa5db359
ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJhY3Rpb24iOiJWaXNpdGVkIC0gb3ZlcnZpZXciLCJ1c2VyIjp7ImF0dHJpYnV0ZXMiOnsiZ2FDbGllbnRJRCI6IjE0Nzg3MDI3MjMuMTc0NTQzOTU1MiJ9LCJhbm9uSWQiOiI5ODE2YTFlM2QyYzgwNmZjIn0sInNvdXJjZSI6eyJ1cmwiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56Lml0L3Bhc3NlbmdlcmNhcnMvbW9kZWxzL2hhdGNoYmFjay9hLWNsYXNzL292ZXJ2aWV3Lmh0bWwiLCJ1cmxSZWZlcnJlciI6IiIsImNoYW5uZWwiOiJXZWIiLCJiZWFjb25WZXJzaW9uIjoxNiwiY29uZmlnVmVyc2lvbiI6IjYzIiwiY29udGVudFpvbmVzIjpbXX0sImNvbnNlbnRzIjpbXSwiYWNjb3VudCI6e30sIl90b29sc0V2ZW50TGlua0lkIjoiOTQ3ODgzNTA0OTg2MDQ4OCIsImRlYnVnIjp7ImV4cGxhbmF0aW9ucyI6dHJ1ZX19: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x562ad8377cea <unknown>
#1 0x562ad7e285f0 <unknown>
#2 0x562ad7e0ee86 <unknown>
#3 0x562ad7e0d79a <unknown>
#4 0x562ad7e0deff <unknown>
#5 0x562ad7e0de54 <unknown>
#6 0x562ad7e2c7ff <unknown>
#7 0x562ad7ed19aa <unknown>
#8 0x562ad7e9f662 <unknown>
#9 0x562ad7ec5660 <unknown>
#10 0x562ad7e9f433 <unknown>
#11 0x562ad7e6bea3 <unknown>
#12 0x562ad7e6cb01 <unknown>
#13 0x562ad833cb3b <unknown>
#14 0x562ad8340a21 <unknown>
#15 0x562ad8323c32 <unknown>
#16 0x562ad8341594 <unknown>
#17 0x562ad8307eef <unknown>
#18 0x562ad8365d98 <unknown>
#19 0x562ad8365f76 <unknown>
#20 0x562ad8376b36 <unknown>
#21 0x7f197f69caa4 <unknown>
#22 0x7f197f729c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJhY3Rpb24iOiJQcm9kdWN0IEluZm9ybWF0aW9uIFBhZ2UgLSBvdmVydmlldyAxNzcwIiwiaXRlbUFjdGlvbiI6IlZpZXcgSXRlbSIsInNvdXJjZSI6eyJwYWdlVHlwZSI6InByb2R1Y3RfaW5mb3JtYXRpb24iLCJsb2NhbGUiOiJpdF9JVCIsImNvbnRlbnRab25lcyI6WyJnbG9iYWxfUElfTkwiLCJwaV9iYW5uZXJfTkwiLCJlcXMtc3BlY2lhbF9OTCJdLCJ1cmwiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56Lml0L3Bhc3NlbmdlcmNhcnMvbW9kZWxzL2hhdGNoYmFjay9hLWNsYXNzL292ZXJ2aWV3Lmh0bWwiLCJ1cmxSZWZlcnJlciI6IiIsImNoYW5uZWwiOiJXZWIiLCJiZWFjb25WZXJzaW9uIjoxNiwiY29uZmlnVmVyc2lvbiI6IjYzIn0sImZsYWdzIjp7InBhZ2VWaWV3Ijp0cnVlfSwidXNlciI6eyJhdHRyaWJ1dGVzIjp7ImdhQ2xpZW50SUQiOiIxNDc4NzAyNzIzLjE3NDU0Mzk1NTIifSwiYW5vbklkIjoiOTgxNmExZTNkMmM4MDZmYyJ9LCJwZXJmb3JtYW5jZSI6eyJzZGtQYXJzZVRpbWUiOjF9LCJkZWJ1ZyI6eyJleHBsYW5hdGlvbnMiOnRydWV9LCJjYXRhbG9nIjp7IlByb2R1Y3QiOnsiX2lkIjoiMTc3MCIsImRpbWVuc2lvbnMiOnsiQmF1bXVzdGVyU2hvcnQiOlsiMTc3MCJdfX19LCJjb25zZW50cyI6W10sImFjY291bnQiOnt9LCJfdG9vbHNFdmVudExpbmtJZCI6IjUyOTk5MjA5MzA1OTAyODQifQ%3D%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x562ad8377cea <unknown>
#1 0x562ad7e285f0 <unknown>
#2 0x562ad7e0ee86 <unknown>
#3 0x562ad7e0d79a <unknown>
#4 0x562ad7e0deff <unknown>
#5 0x562ad7e0de54 <unknown>
#6 0x562ad7e2c7ff <unknown>
#7 0x562ad7ed19aa <unknown>
#8 0x562ad7e9f662 <unknown>
#9 0x562ad7ec5660 <unknown>
#10 0x562ad7e9f433 <unknown>
#11 0x562ad7e6bea3 <unknown>
#12 0x562ad7e6cb01 <unknown>
#13 0x562ad833cb3b <unknown>
#14 0x562ad8340a21 <unknown>
#15 0x562ad8323c32 <unknown>
#16 0x562ad8341594 <unknown>
#17 0x562ad8307eef <unknown>
#18 0x562ad8365d98 <unknown>
#19 0x562ad8365f76 <unknown>
#20 0x562ad8376b36 <unknown>
#21 0x7f197f69caa4 <unknown>
#22 0x7f197f729c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJpdGVtQWN0aW9uIjoiVmlldyBJdGVtIiwiY2F0YWxvZyI6eyJJdGVtQ2xhc3MiOnsiX2lkIjoib3ZlcnZpZXcifX0sInVzZXIiOnsiYXR0cmlidXRlcyI6eyJnYUNsaWVudElEIjoiMTQ3ODcwMjcyMy4xNzQ1NDM5NTUyIn0sImFub25JZCI6Ijk4MTZhMWUzZDJjODA2ZmMifSwic291cmNlIjp7InVybCI6Imh0dHBzOi8vd3d3Lm1lcmNlZGVzLWJlbnouaXQvcGFzc2VuZ2VyY2Fycy9tb2RlbHMvaGF0Y2hiYWNrL2EtY2xhc3Mvb3ZlcnZpZXcuaHRtbCIsInVybFJlZmVycmVyIjoiIiwiY2hhbm5lbCI6IldlYiIsImJlYWNvblZlcnNpb24iOjE2LCJjb25maWdWZXJzaW9uIjoiNjMiLCJjb250ZW50Wm9uZXMiOltdfSwiY29uc2VudHMiOltdLCJhY2NvdW50Ijp7fSwicGVyZm9ybWFuY2UiOnsic2RrUGFyc2VUaW1lIjoxfSwiX3Rvb2xzRXZlbnRMaW5rSWQiOiI4Mzk1ODY5NjU0MDg3NTg0IiwiZGVidWciOnsiZXhwbGFuYXRpb25zIjp0cnVlfX0%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x562ad8377cea <unknown>
#1 0x562ad7e285f0 <unknown>
#2 0x562ad7e0ee86 <unknown>
#3 0x562ad7e0d79a <unknown>
#4 0x562ad7e0deff <unknown>
#5 0x562ad7e0de54 <unknown>
#6 0x562ad7e2c7ff <unknown>
#7 0x562ad7ed19aa <unknown>
#8 0x562ad7e9f662 <unknown>
#9 0x562ad7ec5660 <unknown>
#10 0x562ad7e9f433 <unknown>
#11 0x562ad7e6bea3 <unknown>
#12 0x562ad7e6cb01 <unknown>
#13 0x562ad833cb3b <unknown>
#14 0x562ad8340a21 <unknown>
#15 0x562ad8323c32 <unknown>
#16 0x562ad8341594 <unknown>
#17 0x562ad8307eef <unknown>
#18 0x562ad8365d98 <unknown>
#19 0x562ad8365f76 <unknown>
#20 0x562ad8376b36 <unknown>
#21 0x7f197f69caa4 <unknown>
#22 0x7f197f729c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJhY3Rpb24iOiJzZXRfdXNlcl9hdHRyaWJ1dGUiLCJhY2NvdW50Ijp7ImF0dHJpYnV0ZXMiOnsibGFzdFBpUGFnZSI6eyJ2ZWhpY2xlUEkiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56Lml0L3Bhc3NlbmdlcmNhcnMvbW9kZWxzL2hhdGNoYmFjay9hLWNsYXNzL292ZXJ2aWV3Lmh0bWwiLCJ2ZWhpY2xlQ29kZSI6IncxNzctZmwiLCJ2ZWhpY2xlQk0iOiIxNzcwIiwidmVoaWNsZVBJSGlzdG9yeSI6IjE3NzAiLCJ0aW1lc3RhbXAiOjE3NDU0Mzk1NTU2MDEsImV4cGlyYXRpb24iOjEyMH19fSwidXNlciI6eyJhdHRyaWJ1dGVzIjp7ImdhQ2xpZW50SUQiOiIxNDc4NzAyNzIzLjE3NDU0Mzk1NTIifSwiYW5vbklkIjoiOTgxNmExZTNkMmM4MDZmYyJ9LCJzb3VyY2UiOnsidXJsIjoiaHR0cHM6Ly93d3cubWVyY2VkZXMtYmVuei5pdC9wYXNzZW5nZXJjYXJzL21vZGVscy9oYXRjaGJhY2svYS1jbGFzcy9vdmVydmlldy5odG1sIiwidXJsUmVmZXJyZXIiOiIiLCJjaGFubmVsIjoiV2ViIiwiYmVhY29uVmVyc2lvbiI6MTYsImNvbmZpZ1ZlcnNpb24iOiI2MyIsImNvbnRlbnRab25lcyI6W119LCJjb25zZW50cyI6W10sIl90b29sc0V2ZW50TGlua0lkIjoiNDU1ODYzMTk4OTEyODE1NTciLCJkZWJ1ZyI6eyJleHBsYW5hdGlvbnMiOnRydWV9fQ%3D%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x562ad8377cea <unknown>
#1 0x562ad7e285f0 <unknown>
#2 0x562ad7e0ee86 <unknown>
#3 0x562ad7e0d79a <unknown>
#4 0x562ad7e0deff <unknown>
#5 0x562ad7e0de54 <unknown>
#6 0x562ad7e2c7ff <unknown>
#7 0x562ad7ed19aa <unknown>
#8 0x562ad7e9f662 <unknown>
#9 0x562ad7ec5660 <unknown>
#10 0x562ad7e9f433 <unknown>
#11 0x562ad7e6bea3 <unknown>
#12 0x562ad7e6cb01 <unknown>
#13 0x562ad833cb3b <unknown>
#14 0x562ad8340a21 <unknown>
#15 0x562ad8323c32 <unknown>
#16 0x562ad8341594 <unknown>
#17 0x562ad8307eef <unknown>
#18 0x562ad8365d98 <unknown>
#19 0x562ad8365f76 <unknown>
#20 0x562ad8376b36 <unknown>
#21 0x7f197f69caa4 <unknown>
#22 0x7f197f729c3c <unknown>

ERROR    root:VerifyPersonalizationAndCapture.py:18 ❌ Error attaching screenshot to Allure: [Errno 2] No such file or directory: '/home/runner/work/QA-App-Allure/QA-App-Allure/Tests/BFV1_attempt_2.png'
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f73b6c28f50>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/b95c35c26abe577a9362d38dfa5db359
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f73b6c28050>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/b95c35c26abe577a9362d38dfa5db359
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f73b6c29850>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/b95c35c26abe577a9362d38dfa5db359