ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJhY3Rpb24iOiJWaXNpdGVkIC0gc2VhcmNoLXJlc3VsdHMiLCJ1c2VyIjp7ImF0dHJpYnV0ZXMiOnsiZ2FDbGllbnRJRCI6Ijg2MTEzMDE5Mi4xNzQ1NDUwMTAxIn0sImFub25JZCI6IjJhNmMxOGQ0MzdlOGUxMjMifSwic291cmNlIjp7InVybCI6Imh0dHBzOi8vd3d3Lm1lcmNlZGVzLWJlbnouaXQvcGFzc2VuZ2VyY2Fycy9idXkvbmV3LWNhci9zZWFyY2gtcmVzdWx0cy5odG1sL3ZlaGljbGVDYXRlZ29yeS1uZXctcGFzc2VuZ2VyLWNhcnMvYnJhbmQtTWVyY2VkZXMtQmVuei9tb2RlbElkZW50aWZpZXItR0xFX0NMQVNTLz9lbWhzb3J0VHlwZT1wcmljZS1hc2MmZW1oYm9keVR5cGU9U1VWIiwidXJsUmVmZXJyZXIiOiIiLCJjaGFubmVsIjoiV2ViIiwiYmVhY29uVmVyc2lvbiI6MTYsImNvbmZpZ1ZlcnNpb24iOiI2MyIsImNvbnRlbnRab25lcyI6W119LCJjb25zZW50cyI6W10sImFjY291bnQiOnt9LCJfdG9vbHNFdmVudExpbmtJZCI6IjkyNDg2NzI0NjgzODc2NjYiLCJkZWJ1ZyI6eyJleHBsYW5hdGlvbnMiOnRydWV9fQ%3D%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x564d8eefccea <unknown>
#1 0x564d8e9ad5f0 <unknown>
#2 0x564d8e993e86 <unknown>
#3 0x564d8e99279a <unknown>
#4 0x564d8e992eff <unknown>
#5 0x564d8e992e54 <unknown>
#6 0x564d8e9b17ff <unknown>
#7 0x564d8ea569aa <unknown>
#8 0x564d8ea24662 <unknown>
#9 0x564d8ea4a660 <unknown>
#10 0x564d8ea24433 <unknown>
#11 0x564d8e9f0ea3 <unknown>
#12 0x564d8e9f1b01 <unknown>
#13 0x564d8eec1b3b <unknown>
#14 0x564d8eec5a21 <unknown>
#15 0x564d8eea8c32 <unknown>
#16 0x564d8eec6594 <unknown>
#17 0x564d8ee8ceef <unknown>
#18 0x564d8eeead98 <unknown>
#19 0x564d8eeeaf76 <unknown>
#20 0x564d8eefbb36 <unknown>
#21 0x7f313429caa4 <unknown>
#22 0x7f3134329c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJpdGVtQWN0aW9uIjpudWxsLCJzb3VyY2UiOnsicGFnZVR5cGUiOiJkZWZhdWx0IiwibG9jYWxlIjoiaXRfSVQiLCJjb250ZW50Wm9uZXMiOltdLCJ1cmwiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56Lml0L3Bhc3NlbmdlcmNhcnMvYnV5L25ldy1jYXIvc2VhcmNoLXJlc3VsdHMuaHRtbC92ZWhpY2xlQ2F0ZWdvcnktbmV3LXBhc3Nlbmdlci1jYXJzL2JyYW5kLU1lcmNlZGVzLUJlbnovbW9kZWxJZGVudGlmaWVyLUdMRV9DTEFTUy8%2FZW1oc29ydFR5cGU9cHJpY2UtYXNjJmVtaGJvZHlUeXBlPVNVViIsInVybFJlZmVycmVyIjoiIiwiY2hhbm5lbCI6IldlYiIsImJlYWNvblZlcnNpb24iOjE2LCJjb25maWdWZXJzaW9uIjoiNjMifSwiZmxhZ3MiOnsicGFnZVZpZXciOnRydWV9LCJ1c2VyIjp7ImF0dHJpYnV0ZXMiOnsiZ2FDbGllbnRJRCI6Ijg2MTEzMDE5Mi4xNzQ1NDUwMTAxIn0sImFub25JZCI6IjJhNmMxOGQ0MzdlOGUxMjMifSwicGVyZm9ybWFuY2UiOnt9LCJkZWJ1ZyI6eyJleHBsYW5hdGlvbnMiOnRydWV9LCJjYXRhbG9nIjp7fSwiY29uc2VudHMiOltdLCJhY2NvdW50Ijp7fSwiX3Rvb2xzRXZlbnRMaW5rSWQiOiI3MTcxODcwODg2MjM1MTc5In0%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x564d8eefccea <unknown>
#1 0x564d8e9ad5f0 <unknown>
#2 0x564d8e993e86 <unknown>
#3 0x564d8e99279a <unknown>
#4 0x564d8e992eff <unknown>
#5 0x564d8e992e54 <unknown>
#6 0x564d8e9b17ff <unknown>
#7 0x564d8ea569aa <unknown>
#8 0x564d8ea24662 <unknown>
#9 0x564d8ea4a660 <unknown>
#10 0x564d8ea24433 <unknown>
#11 0x564d8e9f0ea3 <unknown>
#12 0x564d8e9f1b01 <unknown>
#13 0x564d8eec1b3b <unknown>
#14 0x564d8eec5a21 <unknown>
#15 0x564d8eea8c32 <unknown>
#16 0x564d8eec6594 <unknown>
#17 0x564d8ee8ceef <unknown>
#18 0x564d8eeead98 <unknown>
#19 0x564d8eeeaf76 <unknown>
#20 0x564d8eefbb36 <unknown>
#21 0x7f313429caa4 <unknown>
#22 0x7f3134329c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJhY3Rpb24iOiJTZWFyY2ggUmVzdWx0IFBhZ2UgLSBDYXJzIiwidXNlciI6eyJhdHRyaWJ1dGVzIjp7ImdhQ2xpZW50SUQiOiI4NjExMzAxOTIuMTc0NTQ1MDEwMSJ9LCJhbm9uSWQiOiIyYTZjMThkNDM3ZThlMTIzIn0sInNvdXJjZSI6eyJ1cmwiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56Lml0L3Bhc3NlbmdlcmNhcnMvYnV5L25ldy1jYXIvc2VhcmNoLXJlc3VsdHMuaHRtbC92ZWhpY2xlQ2F0ZWdvcnktbmV3LXBhc3Nlbmdlci1jYXJzL2JyYW5kLU1lcmNlZGVzLUJlbnovbW9kZWxJZGVudGlmaWVyLUdMRV9DTEFTUz9lbWhzb3J0VHlwZT1wcmljZS1hc2MmZW1oYm9keVR5cGU9U1VWIiwidXJsUmVmZXJyZXIiOiIiLCJjaGFubmVsIjoiV2ViIiwiYmVhY29uVmVyc2lvbiI6MTYsImNvbmZpZ1ZlcnNpb24iOiI2MyIsImNvbnRlbnRab25lcyI6W119LCJjb25zZW50cyI6W10sImFjY291bnQiOnt9LCJfdG9vbHNFdmVudExpbmtJZCI6IjE4NzcwODgyODkzMjY3NDYiLCJkZWJ1ZyI6eyJleHBsYW5hdGlvbnMiOnRydWV9fQ%3D%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x564d8eefccea <unknown>
#1 0x564d8e9ad5f0 <unknown>
#2 0x564d8e993e86 <unknown>
#3 0x564d8e99279a <unknown>
#4 0x564d8e992eff <unknown>
#5 0x564d8e992e54 <unknown>
#6 0x564d8e9b17ff <unknown>
#7 0x564d8ea569aa <unknown>
#8 0x564d8ea24662 <unknown>
#9 0x564d8ea4a660 <unknown>
#10 0x564d8ea24433 <unknown>
#11 0x564d8e9f0ea3 <unknown>
#12 0x564d8e9f1b01 <unknown>
#13 0x564d8eec1b3b <unknown>
#14 0x564d8eec5a21 <unknown>
#15 0x564d8eea8c32 <unknown>
#16 0x564d8eec6594 <unknown>
#17 0x564d8ee8ceef <unknown>
#18 0x564d8eeead98 <unknown>
#19 0x564d8eeeaf76 <unknown>
#20 0x564d8eefbb36 <unknown>
#21 0x7f313429caa4 <unknown>
#22 0x7f3134329c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJpdGVtQWN0aW9uIjpudWxsLCJzb3VyY2UiOnsicGFnZVR5cGUiOiJzZWFyY2hfcmVzdWx0IiwibG9jYWxlIjoiaXRfSVQiLCJjb250ZW50Wm9uZXMiOltdLCJ1cmwiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56Lml0L3Bhc3NlbmdlcmNhcnMvYnV5L25ldy1jYXIvc2VhcmNoLXJlc3VsdHMuaHRtbC92ZWhpY2xlQ2F0ZWdvcnktbmV3LXBhc3Nlbmdlci1jYXJzL2JyYW5kLU1lcmNlZGVzLUJlbnovbW9kZWxJZGVudGlmaWVyLUdMRV9DTEFTUz9lbWhzb3J0VHlwZT1wcmljZS1hc2MmZW1oYm9keVR5cGU9U1VWIiwidXJsUmVmZXJyZXIiOiIiLCJjaGFubmVsIjoiV2ViIiwiYmVhY29uVmVyc2lvbiI6MTYsImNvbmZpZ1ZlcnNpb24iOiI2MyJ9LCJmbGFncyI6eyJwYWdlVmlldyI6dHJ1ZX0sInVzZXIiOnsiYXR0cmlidXRlcyI6eyJnYUNsaWVudElEIjoiODYxMTMwMTkyLjE3NDU0NTAxMDEifSwiYW5vbklkIjoiMmE2YzE4ZDQzN2U4ZTEyMyJ9LCJwZXJmb3JtYW5jZSI6e30sImRlYnVnIjp7ImV4cGxhbmF0aW9ucyI6dHJ1ZX0sImNhdGFsb2ciOnt9LCJjb25zZW50cyI6W10sImFjY291bnQiOnt9LCJfdG9vbHNFdmVudExpbmtJZCI6IjYzNDkwNzQxODE2MTUxMjYifQ%3D%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x564d8eefccea <unknown>
#1 0x564d8e9ad5f0 <unknown>
#2 0x564d8e993e86 <unknown>
#3 0x564d8e99279a <unknown>
#4 0x564d8e992eff <unknown>
#5 0x564d8e992e54 <unknown>
#6 0x564d8e9b17ff <unknown>
#7 0x564d8ea569aa <unknown>
#8 0x564d8ea24662 <unknown>
#9 0x564d8ea4a660 <unknown>
#10 0x564d8ea24433 <unknown>
#11 0x564d8e9f0ea3 <unknown>
#12 0x564d8e9f1b01 <unknown>
#13 0x564d8eec1b3b <unknown>
#14 0x564d8eec5a21 <unknown>
#15 0x564d8eea8c32 <unknown>
#16 0x564d8eec6594 <unknown>
#17 0x564d8ee8ceef <unknown>
#18 0x564d8eeead98 <unknown>
#19 0x564d8eeeaf76 <unknown>
#20 0x564d8eefbb36 <unknown>
#21 0x7f313429caa4 <unknown>
#22 0x7f3134329c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJhY3Rpb24iOiJWaXNpdGVkIC0gcHJvZHVjdCIsInVzZXIiOnsiYXR0cmlidXRlcyI6eyJnYUNsaWVudElEIjoiODYxMTMwMTkyLjE3NDU0NTAxMDEifSwiYW5vbklkIjoiMmE2YzE4ZDQzN2U4ZTEyMyJ9LCJzb3VyY2UiOnsidXJsIjoiaHR0cHM6Ly93d3cubWVyY2VkZXMtYmVuei5pdC9wYXNzZW5nZXJjYXJzL2J1eS9uZXctY2FyL3Byb2R1Y3QuaHRtbC9HTEUtMzAwLWQtNE1BVElDXzA0NTQzNDA4MjZfSVRfMzU0YWUyZjUiLCJ1cmxSZWZlcnJlciI6IiIsImNoYW5uZWwiOiJXZWIiLCJiZWFjb25WZXJzaW9uIjoxNiwiY29uZmlnVmVyc2lvbiI6IjYzIiwiY29udGVudFpvbmVzIjpbXX0sImNvbnNlbnRzIjpbXSwiYWNjb3VudCI6e30sIl90b29sc0V2ZW50TGlua0lkIjoiNDgxMjgyMzE1MDgxNjEzIiwiZGVidWciOnsiZXhwbGFuYXRpb25zIjp0cnVlfX0%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x564d8eefccea <unknown>
#1 0x564d8e9ad5f0 <unknown>
#2 0x564d8e993e86 <unknown>
#3 0x564d8e99279a <unknown>
#4 0x564d8e992eff <unknown>
#5 0x564d8e992e54 <unknown>
#6 0x564d8e9b17ff <unknown>
#7 0x564d8ea569aa <unknown>
#8 0x564d8ea24662 <unknown>
#9 0x564d8ea4a660 <unknown>
#10 0x564d8ea24433 <unknown>
#11 0x564d8e9f0ea3 <unknown>
#12 0x564d8e9f1b01 <unknown>
#13 0x564d8eec1b3b <unknown>
#14 0x564d8eec5a21 <unknown>
#15 0x564d8eea8c32 <unknown>
#16 0x564d8eec6594 <unknown>
#17 0x564d8ee8ceef <unknown>
#18 0x564d8eeead98 <unknown>
#19 0x564d8eeeaf76 <unknown>
#20 0x564d8eefbb36 <unknown>
#21 0x7f313429caa4 <unknown>
#22 0x7f3134329c3c <unknown>

WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6252449550>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/010c2ec6ff2c125970c579235c70071b
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f62524486d0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/010c2ec6ff2c125970c579235c70071b
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f625244a5d0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/010c2ec6ff2c125970c579235c70071b
ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJpdGVtQWN0aW9uIjpudWxsLCJzb3VyY2UiOnsicGFnZVR5cGUiOiJkZWZhdWx0IiwibG9jYWxlIjoiaXRfSVQiLCJjb250ZW50Wm9uZXMiOltdLCJ1cmwiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56Lml0L3Bhc3NlbmdlcmNhcnMvYnV5L25ldy1jYXIvc2VhcmNoLXJlc3VsdHMuaHRtbC92ZWhpY2xlQ2F0ZWdvcnktbmV3LXBhc3Nlbmdlci1jYXJzL2JyYW5kLU1lcmNlZGVzLUJlbnovbW9kZWxJZGVudGlmaWVyLUdMRV9DTEFTUy8%2FZW1oc29ydFR5cGU9cHJpY2UtYXNjJmVtaGJvZHlUeXBlPVNVViIsInVybFJlZmVycmVyIjoiIiwiY2hhbm5lbCI6IldlYiIsImJlYWNvblZlcnNpb24iOjE2LCJjb25maWdWZXJzaW9uIjoiNjMifSwiZmxhZ3MiOnsicGFnZVZpZXciOnRydWV9LCJ1c2VyIjp7ImF0dHJpYnV0ZXMiOnsiZ2FDbGllbnRJRCI6IjY5Nzg0MzI5Mi4xNzQ1NDUwMTM1In0sImFub25JZCI6IjhjNDI0NDZmMjgwNDdhNDMifSwicGVyZm9ybWFuY2UiOnt9LCJkZWJ1ZyI6eyJleHBsYW5hdGlvbnMiOnRydWV9LCJjYXRhbG9nIjp7fSwiY29uc2VudHMiOltdLCJhY2NvdW50Ijp7fSwiX3Rvb2xzRXZlbnRMaW5rSWQiOiI5Nzc5NDM2NDU2ODAxNDkifQ%3D%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x5608d5f94cea <unknown>
#1 0x5608d5a455f0 <unknown>
#2 0x5608d5a2be86 <unknown>
#3 0x5608d5a2a79a <unknown>
#4 0x5608d5a2aeff <unknown>
#5 0x5608d5a2ae54 <unknown>
#6 0x5608d5a497ff <unknown>
#7 0x5608d5aee9aa <unknown>
#8 0x5608d5abc662 <unknown>
#9 0x5608d5ae2660 <unknown>
#10 0x5608d5abc433 <unknown>
#11 0x5608d5a88ea3 <unknown>
#12 0x5608d5a89b01 <unknown>
#13 0x5608d5f59b3b <unknown>
#14 0x5608d5f5da21 <unknown>
#15 0x5608d5f40c32 <unknown>
#16 0x5608d5f5e594 <unknown>
#17 0x5608d5f24eef <unknown>
#18 0x5608d5f82d98 <unknown>
#19 0x5608d5f82f76 <unknown>
#20 0x5608d5f93b36 <unknown>
#21 0x7ff3e829caa4 <unknown>
#22 0x7ff3e8329c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJhY3Rpb24iOiJWaXNpdGVkIC0gc2VhcmNoLXJlc3VsdHMiLCJ1c2VyIjp7ImF0dHJpYnV0ZXMiOnsiZ2FDbGllbnRJRCI6IjY5Nzg0MzI5Mi4xNzQ1NDUwMTM1In0sImFub25JZCI6IjhjNDI0NDZmMjgwNDdhNDMifSwic291cmNlIjp7InVybCI6Imh0dHBzOi8vd3d3Lm1lcmNlZGVzLWJlbnouaXQvcGFzc2VuZ2VyY2Fycy9idXkvbmV3LWNhci9zZWFyY2gtcmVzdWx0cy5odG1sL3ZlaGljbGVDYXRlZ29yeS1uZXctcGFzc2VuZ2VyLWNhcnMvYnJhbmQtTWVyY2VkZXMtQmVuei9tb2RlbElkZW50aWZpZXItR0xFX0NMQVNTLz9lbWhzb3J0VHlwZT1wcmljZS1hc2MmZW1oYm9keVR5cGU9U1VWIiwidXJsUmVmZXJyZXIiOiIiLCJjaGFubmVsIjoiV2ViIiwiYmVhY29uVmVyc2lvbiI6MTYsImNvbmZpZ1ZlcnNpb24iOiI2MyIsImNvbnRlbnRab25lcyI6W119LCJjb25zZW50cyI6W10sImFjY291bnQiOnt9LCJfdG9vbHNFdmVudExpbmtJZCI6IjU3Njg2MTEyNjk3NjY0MzgiLCJkZWJ1ZyI6eyJleHBsYW5hdGlvbnMiOnRydWV9fQ%3D%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x5608d5f94cea <unknown>
#1 0x5608d5a455f0 <unknown>
#2 0x5608d5a2be86 <unknown>
#3 0x5608d5a2a79a <unknown>
#4 0x5608d5a2aeff <unknown>
#5 0x5608d5a2ae54 <unknown>
#6 0x5608d5a497ff <unknown>
#7 0x5608d5aee9aa <unknown>
#8 0x5608d5abc662 <unknown>
#9 0x5608d5ae2660 <unknown>
#10 0x5608d5abc433 <unknown>
#11 0x5608d5a88ea3 <unknown>
#12 0x5608d5a89b01 <unknown>
#13 0x5608d5f59b3b <unknown>
#14 0x5608d5f5da21 <unknown>
#15 0x5608d5f40c32 <unknown>
#16 0x5608d5f5e594 <unknown>
#17 0x5608d5f24eef <unknown>
#18 0x5608d5f82d98 <unknown>
#19 0x5608d5f82f76 <unknown>
#20 0x5608d5f93b36 <unknown>
#21 0x7ff3e829caa4 <unknown>
#22 0x7ff3e8329c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJhY3Rpb24iOiJTZWFyY2ggUmVzdWx0IFBhZ2UgLSBDYXJzIiwidXNlciI6eyJhdHRyaWJ1dGVzIjp7ImdhQ2xpZW50SUQiOiI2OTc4NDMyOTIuMTc0NTQ1MDEzNSJ9LCJhbm9uSWQiOiI4YzQyNDQ2ZjI4MDQ3YTQzIn0sInNvdXJjZSI6eyJ1cmwiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56Lml0L3Bhc3NlbmdlcmNhcnMvYnV5L25ldy1jYXIvc2VhcmNoLXJlc3VsdHMuaHRtbC92ZWhpY2xlQ2F0ZWdvcnktbmV3LXBhc3Nlbmdlci1jYXJzL2JyYW5kLU1lcmNlZGVzLUJlbnovbW9kZWxJZGVudGlmaWVyLUdMRV9DTEFTUz9lbWhzb3J0VHlwZT1wcmljZS1hc2MmZW1oYm9keVR5cGU9U1VWIiwidXJsUmVmZXJyZXIiOiIiLCJjaGFubmVsIjoiV2ViIiwiYmVhY29uVmVyc2lvbiI6MTYsImNvbmZpZ1ZlcnNpb24iOiI2MyIsImNvbnRlbnRab25lcyI6W119LCJjb25zZW50cyI6W10sImFjY291bnQiOnt9LCJfdG9vbHNFdmVudExpbmtJZCI6Ijg0OTAyNDgwMTc4MDgxMTciLCJkZWJ1ZyI6eyJleHBsYW5hdGlvbnMiOnRydWV9fQ%3D%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x5608d5f94cea <unknown>
#1 0x5608d5a455f0 <unknown>
#2 0x5608d5a2be86 <unknown>
#3 0x5608d5a2a79a <unknown>
#4 0x5608d5a2aeff <unknown>
#5 0x5608d5a2ae54 <unknown>
#6 0x5608d5a497ff <unknown>
#7 0x5608d5aee9aa <unknown>
#8 0x5608d5abc662 <unknown>
#9 0x5608d5ae2660 <unknown>
#10 0x5608d5abc433 <unknown>
#11 0x5608d5a88ea3 <unknown>
#12 0x5608d5a89b01 <unknown>
#13 0x5608d5f59b3b <unknown>
#14 0x5608d5f5da21 <unknown>
#15 0x5608d5f40c32 <unknown>
#16 0x5608d5f5e594 <unknown>
#17 0x5608d5f24eef <unknown>
#18 0x5608d5f82d98 <unknown>
#19 0x5608d5f82f76 <unknown>
#20 0x5608d5f93b36 <unknown>
#21 0x7ff3e829caa4 <unknown>
#22 0x7ff3e8329c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJpdGVtQWN0aW9uIjpudWxsLCJzb3VyY2UiOnsicGFnZVR5cGUiOiJzZWFyY2hfcmVzdWx0IiwibG9jYWxlIjoiaXRfSVQiLCJjb250ZW50Wm9uZXMiOltdLCJ1cmwiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56Lml0L3Bhc3NlbmdlcmNhcnMvYnV5L25ldy1jYXIvc2VhcmNoLXJlc3VsdHMuaHRtbC92ZWhpY2xlQ2F0ZWdvcnktbmV3LXBhc3Nlbmdlci1jYXJzL2JyYW5kLU1lcmNlZGVzLUJlbnovbW9kZWxJZGVudGlmaWVyLUdMRV9DTEFTUz9lbWhzb3J0VHlwZT1wcmljZS1hc2MmZW1oYm9keVR5cGU9U1VWIiwidXJsUmVmZXJyZXIiOiIiLCJjaGFubmVsIjoiV2ViIiwiYmVhY29uVmVyc2lvbiI6MTYsImNvbmZpZ1ZlcnNpb24iOiI2MyJ9LCJmbGFncyI6eyJwYWdlVmlldyI6dHJ1ZX0sInVzZXIiOnsiYXR0cmlidXRlcyI6eyJnYUNsaWVudElEIjoiNjk3ODQzMjkyLjE3NDU0NTAxMzUifSwiYW5vbklkIjoiOGM0MjQ0NmYyODA0N2E0MyJ9LCJwZXJmb3JtYW5jZSI6e30sImRlYnVnIjp7ImV4cGxhbmF0aW9ucyI6dHJ1ZX0sImNhdGFsb2ciOnt9LCJjb25zZW50cyI6W10sImFjY291bnQiOnt9LCJfdG9vbHNFdmVudExpbmtJZCI6Ijg3MTg5MzA4NTc4Nzk2OCJ9: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x5608d5f94cea <unknown>
#1 0x5608d5a455f0 <unknown>
#2 0x5608d5a2be86 <unknown>
#3 0x5608d5a2a79a <unknown>
#4 0x5608d5a2aeff <unknown>
#5 0x5608d5a2ae54 <unknown>
#6 0x5608d5a497ff <unknown>
#7 0x5608d5aee9aa <unknown>
#8 0x5608d5abc662 <unknown>
#9 0x5608d5ae2660 <unknown>
#10 0x5608d5abc433 <unknown>
#11 0x5608d5a88ea3 <unknown>
#12 0x5608d5a89b01 <unknown>
#13 0x5608d5f59b3b <unknown>
#14 0x5608d5f5da21 <unknown>
#15 0x5608d5f40c32 <unknown>
#16 0x5608d5f5e594 <unknown>
#17 0x5608d5f24eef <unknown>
#18 0x5608d5f82d98 <unknown>
#19 0x5608d5f82f76 <unknown>
#20 0x5608d5f93b36 <unknown>
#21 0x7ff3e829caa4 <unknown>
#22 0x7ff3e8329c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJhY3Rpb24iOiJzZXRfdXNlcl9hdHRyaWJ1dGUiLCJhY2NvdW50Ijp7ImF0dHJpYnV0ZXMiOnsibGFzdFNSUE1vZGVsRmlsdGVyIjoie1wiZGNwX2xhc3RfbW9kZWxmaWx0ZXJcIjpcImdsZS1jbGFzc1wiLFwiZGNwX2xhc3RfYm9keXR5cGVmaWx0ZXJcIjpcInN1dlwiLFwiZGNwX2xhc3Rfc2VhcmNoX3VybFwiOlwiaHR0cHM6Ly93d3cubWVyY2VkZXMtYmVuei5pdC9wYXNzZW5nZXJjYXJzL2J1eS9uZXctY2FyL3NlYXJjaC1yZXN1bHRzLmh0bWwvdmVoaWNsZUNhdGVnb3J5LW5ldy1wYXNzZW5nZXItY2Fycy9icmFuZC1NZXJjZWRlcy1CZW56L21vZGVsSWRlbnRpZmllci1HTEVfQ0xBU1M%2FZW1oc29ydFR5cGU9cHJpY2UtYXNjJmVtaGJvZHlUeXBlPVNVVlwiLFwidGltZXN0YW1wXCI6MTc0NTQ1MDE0NTEzNCxcImV4cGlyYXRpb25cIjoxMjB9In19LCJ1c2VyIjp7ImF0dHJpYnV0ZXMiOnsiZ2FDbGllbnRJRCI6IjY5Nzg0MzI5Mi4xNzQ1NDUwMTM1In0sImFub25JZCI6IjhjNDI0NDZmMjgwNDdhNDMifSwic291cmNlIjp7InVybCI6Imh0dHBzOi8vd3d3Lm1lcmNlZGVzLWJlbnouaXQvcGFzc2VuZ2VyY2Fycy9idXkvbmV3LWNhci9zZWFyY2gtcmVzdWx0cy5odG1sL3ZlaGljbGVDYXRlZ29yeS1uZXctcGFzc2VuZ2VyLWNhcnMvYnJhbmQtTWVyY2VkZXMtQmVuei9tb2RlbElkZW50aWZpZXItR0xFX0NMQVNTP2VtaHNvcnRUeXBlPXByaWNlLWFzYyZlbWhib2R5VHlwZT1TVVYiLCJ1cmxSZWZlcnJlciI6IiIsImNoYW5uZWwiOiJXZWIiLCJiZWFjb25WZXJzaW9uIjoxNiwiY29uZmlnVmVyc2lvbiI6IjYzIiwiY29udGVudFpvbmVzIjpbXX0sImNvbnNlbnRzIjpbXSwiX3Rvb2xzRXZlbnRMaW5rSWQiOiI4OTI1MzgwNDQ2MjkwMzU3IiwiZGVidWciOnsiZXhwbGFuYXRpb25zIjp0cnVlfX0%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x5608d5f94cea <unknown>
#1 0x5608d5a455f0 <unknown>
#2 0x5608d5a2be86 <unknown>
#3 0x5608d5a2a79a <unknown>
#4 0x5608d5a2aeff <unknown>
#5 0x5608d5a2ae54 <unknown>
#6 0x5608d5a497ff <unknown>
#7 0x5608d5aee9aa <unknown>
#8 0x5608d5abc662 <unknown>
#9 0x5608d5ae2660 <unknown>
#10 0x5608d5abc433 <unknown>
#11 0x5608d5a88ea3 <unknown>
#12 0x5608d5a89b01 <unknown>
#13 0x5608d5f59b3b <unknown>
#14 0x5608d5f5da21 <unknown>
#15 0x5608d5f40c32 <unknown>
#16 0x5608d5f5e594 <unknown>
#17 0x5608d5f24eef <unknown>
#18 0x5608d5f82d98 <unknown>
#19 0x5608d5f82f76 <unknown>
#20 0x5608d5f93b36 <unknown>
#21 0x7ff3e829caa4 <unknown>
#22 0x7ff3e8329c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJhY3Rpb24iOiJWaXNpdGVkIC0gcHJvZHVjdCIsInVzZXIiOnsiYXR0cmlidXRlcyI6eyJnYUNsaWVudElEIjoiNjk3ODQzMjkyLjE3NDU0NTAxMzUifSwiYW5vbklkIjoiOGM0MjQ0NmYyODA0N2E0MyJ9LCJzb3VyY2UiOnsidXJsIjoiaHR0cHM6Ly93d3cubWVyY2VkZXMtYmVuei5pdC9wYXNzZW5nZXJjYXJzL2J1eS9uZXctY2FyL3Byb2R1Y3QuaHRtbC9HTEUtMzAwLWQtNE1BVElDXzA0NTQzNDA4MjZfSVRfMzU0YWUyZjUiLCJ1cmxSZWZlcnJlciI6IiIsImNoYW5uZWwiOiJXZWIiLCJiZWFjb25WZXJzaW9uIjoxNiwiY29uZmlnVmVyc2lvbiI6IjYzIiwiY29udGVudFpvbmVzIjpbXX0sImNvbnNlbnRzIjpbXSwiYWNjb3VudCI6e30sIl90b29sc0V2ZW50TGlua0lkIjoiNDk2NjcwMzE5Njc2NDExNiIsImRlYnVnIjp7ImV4cGxhbmF0aW9ucyI6dHJ1ZX19: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x5608d5f94cea <unknown>
#1 0x5608d5a455f0 <unknown>
#2 0x5608d5a2be86 <unknown>
#3 0x5608d5a2a79a <unknown>
#4 0x5608d5a2aeff <unknown>
#5 0x5608d5a2ae54 <unknown>
#6 0x5608d5a497ff <unknown>
#7 0x5608d5aee9aa <unknown>
#8 0x5608d5abc662 <unknown>
#9 0x5608d5ae2660 <unknown>
#10 0x5608d5abc433 <unknown>
#11 0x5608d5a88ea3 <unknown>
#12 0x5608d5a89b01 <unknown>
#13 0x5608d5f59b3b <unknown>
#14 0x5608d5f5da21 <unknown>
#15 0x5608d5f40c32 <unknown>
#16 0x5608d5f5e594 <unknown>
#17 0x5608d5f24eef <unknown>
#18 0x5608d5f82d98 <unknown>
#19 0x5608d5f82f76 <unknown>
#20 0x5608d5f93b36 <unknown>
#21 0x7ff3e829caa4 <unknown>
#22 0x7ff3e8329c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJhY3Rpb24iOiJQcm9kdWN0IERldGFpbCBQYWdlIC0gMTY3MSIsInVzZXIiOnsiYXR0cmlidXRlcyI6eyJnYUNsaWVudElEIjoiNjk3ODQzMjkyLjE3NDU0NTAxMzUifSwiYW5vbklkIjoiOGM0MjQ0NmYyODA0N2E0MyJ9LCJzb3VyY2UiOnsidXJsIjoiaHR0cHM6Ly93d3cubWVyY2VkZXMtYmVuei5pdC9wYXNzZW5nZXJjYXJzL2J1eS9uZXctY2FyL3Byb2R1Y3QuaHRtbC9HTEUtMzAwLWQtNE1BVElDXzA0NTQzNDA4MjZfSVRfMzU0YWUyZjUiLCJ1cmxSZWZlcnJlciI6IiIsImNoYW5uZWwiOiJXZWIiLCJiZWFjb25WZXJzaW9uIjoxNiwiY29uZmlnVmVyc2lvbiI6IjYzIiwiY29udGVudFpvbmVzIjpbXX0sImNvbnNlbnRzIjpbXSwiYWNjb3VudCI6e30sInBlcmZvcm1hbmNlIjp7InNka1BhcnNlVGltZSI6MSwic2RrTG9hZFRpbWUiOjF9LCJfdG9vbHNFdmVudExpbmtJZCI6IjYwNDMzMzIxMTYxMzYyMyIsImRlYnVnIjp7ImV4cGxhbmF0aW9ucyI6dHJ1ZX19: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x5608d5f94cea <unknown>
#1 0x5608d5a455f0 <unknown>
#2 0x5608d5a2be86 <unknown>
#3 0x5608d5a2a79a <unknown>
#4 0x5608d5a2aeff <unknown>
#5 0x5608d5a2ae54 <unknown>
#6 0x5608d5a497ff <unknown>
#7 0x5608d5aee9aa <unknown>
#8 0x5608d5abc662 <unknown>
#9 0x5608d5ae2660 <unknown>
#10 0x5608d5abc433 <unknown>
#11 0x5608d5a88ea3 <unknown>
#12 0x5608d5a89b01 <unknown>
#13 0x5608d5f59b3b <unknown>
#14 0x5608d5f5da21 <unknown>
#15 0x5608d5f40c32 <unknown>
#16 0x5608d5f5e594 <unknown>
#17 0x5608d5f24eef <unknown>
#18 0x5608d5f82d98 <unknown>
#19 0x5608d5f82f76 <unknown>
#20 0x5608d5f93b36 <unknown>
#21 0x7ff3e829caa4 <unknown>
#22 0x7ff3e8329c3c <unknown>

ERROR    root:VerifyPersonalizationAndCapture.py:18 ❌ Error attaching screenshot to Allure: [Errno 2] No such file or directory: '/home/runner/work/QA-App-Allure/QA-App-Allure/Tests/Last Seen PDP_attempt_2.png'
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f624f267190>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/010c2ec6ff2c125970c579235c70071b
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f624f264b90>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/010c2ec6ff2c125970c579235c70071b
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f624f266010>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/010c2ec6ff2c125970c579235c70071b